// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0

//! CONTEXT: OS-lite backend for the execd (execution daemon) service. Handles process
//! execution, crash reporting with minidump artifacts, and crash record forwarding to logd
//! via budgeted IPC. Provides the cooperative service main loop for the lite runtime.
//! OWNERS: @runtime
//! STATUS: Functional
//! API_STABILITY: Unstable
//! TEST_COVERAGE: No tests
//! ADR: docs/adr/0007-executable-payloads-architecture.md

#![cfg(all(nexus_env = "os", feature = "os-lite"))]

extern crate alloc;

use alloc::boxed::Box;
use alloc::string::String;
use alloc::vec::Vec;

use core::fmt;
use core::sync::atomic::{AtomicU64, Ordering};

use crate::crash_fields::{
    append_field, append_field_i32, append_field_u32, append_field_u64, push_i32_dec, push_u32_dec,
};
use nexus_abi::{
    debug_putc, exec, nsec, service_id_from_name, wait_nohang_with_reason, wait_with_reason,
    yield_, ExitReason, Pid,
};
use nexus_ipc::{KernelServer, Server as _, Wait};
use nexus_metrics::client::MetricsClient;
use nexus_metrics::{DeterministicIdSource, SpanId};
use nexus_service_topology::slots::execd as topo;

mod recv_wake_probe;
use recv_wake_probe::run_recv_wake_probe;

use crash::{
    deterministic_build_id, normalize_dump_path, validate_dump_path, write_dump_to_statefs,
    MinidumpFrame,
};
use demo_exit0::{DEMO_EXIT0_ELF, DEMO_MINIDUMP_ELF};
use exec_payloads::HELLO_ELF;
use nexus_log;

/// Result alias surfaced by the lite execd backend.
pub type LiteResult<T> = Result<T, ServerError>;

/// Restart policy for launched services.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RestartPolicy {
    /// Never restart the service after exit.
    Never,
    /// Always restart the service when it exits.
    Always,
}

/// Ready notifier invoked once execd finishes initialization.
pub struct ReadyNotifier(Box<dyn FnOnce() + Send>);

impl ReadyNotifier {
    /// Creates a notifier from the provided closure.
    pub fn new<F>(func: F) -> Self
    where
        F: FnOnce() + Send + 'static,
    {
        Self(Box::new(func))
    }

    /// Signals readiness to the caller.
    pub fn notify(self) {
        (self.0)();
    }
}

/// Errors surfaced by the lite execd backend.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ServerError {
    /// Placeholder error until the lite backend is implemented.
    Unsupported,
}

impl fmt::Display for ServerError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unsupported => write!(f, "execd unsupported"),
        }
    }
}

/// Errors returned by exec helpers on the lite backend.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ExecError {
    /// Functionality not available yet.
    Unsupported,
}

impl fmt::Display for ExecError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unsupported => write!(f, "exec unsupported"),
        }
    }
}

/// Schema warmer placeholder retained for parity.
pub fn touch_schemas() {}

const MAGIC0: u8 = b'E';
const MAGIC1: u8 = b'X';
const VERSION: u8 = 1;

const OP_EXEC_IMAGE: u8 = 1;
const OP_REPORT_EXIT: u8 = 2;
const OP_WAIT_PID: u8 = 3;

use crate::sched_recipe::apply_sched_recipe;

pub(crate) const IMG_HELLO: u8 = 1;
const IMG_EXIT0: u8 = 2;
const IMG_EXIT42: u8 = 3;
/// ADR-0056 fault-truth proof child: prints its marker, then dereferences
/// VA 0 — the kernel kills it with `ExitReason::Fault` (TASK-0049).
const IMG_FAULT: u8 = 5;
/// TASK-0080D R1: the app-host runtime (ADR-0042 transport probe). The ELF is
/// embedded by `build.rs` when `scripts/build.sh` provides it; empty ⇒
/// UNSUPPORTED (fail-closed, never a fake payload).
pub(crate) const IMG_APPHOST: u8 = 4;

// Generated by build.rs: `APPHOST_ELF` (may be empty on plain cargo builds).
mod apphost_payload {
    include!(concat!(env!("OUT_DIR"), "/apphost_payload.rs"));
}

// Generated by build.rs: `RECVWAKE_ELF` (may be empty on plain cargo builds).
mod recvwake_payload {
    include!(concat!(env!("OUT_DIR"), "/recvwake_payload.rs"));
}

// Generated by build.rs: `APP_MANIFEST_CAPS` (app → declared caps) from the
// real bundle manifests — the SSOT that gates which service routes execd
// provisions for a spawned app-host (TASK-0080C declarative routing).
mod app_caps {
    include!(concat!(env!("OUT_DIR"), "/app_manifest_caps.rs"));
}

/// GET_PAYLOAD (TASK-0080D): execd's own slot holding the bundlemgrd request
/// SEND cap. Init PINS it here (TASK-0324 P4e-2); the boot line
/// `init: execd bundle slot send=0xa` reports what the declaration says.
const BUNDLE_SEND_SLOT: u32 = topo::BUNDLEMGRD.send;
/// Payload VMO budget: header + 512KB NXLC container (transport CONTRACT,
/// = app-host `PAYLOAD_MAX_LEN`; settings hit 93% of 256KB, probe alarms 90%).
const PAYLOAD_VMO_BYTES: usize = 16 + 512 * 1024;
/// P0.2 recv-wake regression gate: TWO one-way endpoints for the probe handshake —
/// ping (execd SENDs, the child RECVs) and reply (the child SENDs, execd RECVs).
/// Two endpoints because a single shared queue would let execd's reply-wait steal
/// the ping it just sent to the parked child. Init mints both and pins them where
/// the topology declares (`init: execd recv-wake slots …` reports the same numbers).
const PROBE_PING_SEND_SLOT: u32 = topo::PROBE_PING.send;
const PROBE_PING_RECV_SLOT: u32 = topo::PROBE_PING.recv;
const PROBE_REPLY_SEND_SLOT: u32 = topo::PROBE_REPLY.send;
const PROBE_REPLY_RECV_SLOT: u32 = topo::PROBE_REPLY.recv;
/// The probe CHILD's slots — declared once and read by the probe binary too.
const PROBE_CHILD_PING_RECV_SLOT: u32 = nexus_service_topology::slots::recv_wake_probe::PING_RECV;
const PROBE_CHILD_REPLY_SEND_SLOT: u32 = nexus_service_topology::slots::recv_wake_probe::REPLY_SEND;
/// Probe wire bytes (pinned in recv-wake-probe/src/main.rs).
const PROBE_MSG_ARMED: u8 = 0xA1;
const PROBE_MSG_WOKE: u8 = 0xA2;
// Bring-up alias: kernel currently reports selftest-client under this stable sender ID.
// Keep identity binding strict by accepting only this exact alternate for that requester.
const SID_SELFTEST_CLIENT_ALT: u64 = 0x68c1_66c3_7bcd_7154;

const STATUS_OK: u8 = 0;
const STATUS_MALFORMED: u8 = 1;
const STATUS_UNSUPPORTED: u8 = 2;
const STATUS_FAILED: u8 = 3;
const STATUS_DENIED: u8 = 4;
static EXEC_SPAN_LOCAL: AtomicU64 = AtomicU64::new(1);
const RUNTIME_APP_CAPS: [&str; 4] = ["vfsd", "samgrd", "policyd", "logd"];

/// Stubbed service loop that reports readiness and yields forever.
/// Builds the `OP_WAIT_PID` success reply
/// `[E,X,ver,OP|0x80, STATUS_OK, pid:u32le, code:i32le, reason:u8, cause:u8]`.
/// The two ADR-0056 tail bytes are additive (v1 replies were 13 bytes);
/// reason byte = 0 clean / 1 error / 2 fault / 3 killed / 0xFF unknown.
fn wait_ok_response(pid: u32, code: i32, reason: ExitReason) -> Vec<u8> {
    let (tag, cause): (u8, u8) = match reason {
        ExitReason::Clean => (0, 0),
        ExitReason::Error => (1, 0),
        ExitReason::Fault { cause } => (2, cause),
        ExitReason::Killed => (3, 0),
        ExitReason::Unknown => (0xFF, 0),
    };
    let mut out = Vec::with_capacity(15);
    out.extend_from_slice(&[MAGIC0, MAGIC1, VERSION, OP_WAIT_PID | 0x80, STATUS_OK]);
    out.extend_from_slice(&pid.to_le_bytes());
    out.extend_from_slice(&code.to_le_bytes());
    out.push(tag);
    out.push(cause);
    out
}

/// RFC-0081: reaper-of-record sweep. Drains every child that has exited since
/// the last call, non-blocking — each `wait_nohang` reap frees that child's
/// address space (heap-backed page tables) in the kernel, and records the exit
/// (idempotent crash handling) so a later `OP_WAIT_PID` answers from cache.
/// Bounded by the tracked-child count; human-rate, so the per-reap marker and
/// `format!` are acceptable (same discipline as the spawn markers).
fn reap_ready_children(state: &mut State) {
    // Children are bounded to 16; 32 iterations covers any transient burst.
    for _ in 0..32 {
        match wait_nohang_with_reason() {
            Ok(Some((pid, code, reason))) => {
                state.handle_child_exit(pid, code, reason);
                let _ = nexus_abi::debug_println(&alloc::format!(
                    "execd: reaped pid={pid} code={code}"
                ));
            }
            Ok(None) | Err(_) => break,
        }
    }
}

pub fn service_main_loop(notifier: ReadyNotifier) -> LiteResult<()> {
    // Verdict folding → `execd N/N` (interactive); flushed at ready, later exec markers print raw.
    nexus_abi::service_verdict_arm();
    notifier.notify();
    let _ = nexus_service_entry::ready("execd: ready");
    nexus_abi::service_verdict_flush("execd");
    // P0.2 regression gate: one bounded probe run per boot (post-flush so its
    // markers print raw). Proves — or loudly reproduces — the sender-wake of
    // an exec'd child parked in a blocking ipc recv (#102 family).
    run_recv_wake_probe();
    // The declared server pair (TASK-0324 P4), pinned before this task runs. No route ask at
    // start-up (P7-b): an ask has no clock and init may be blocked in a synchronous exchange
    // with a service that, in turn, waits for THIS server — the ask made that a deadlock.
    let server = KernelServer::new_with_slots(topo::SERVER.recv, topo::SERVER.send)
        .map_err(|_| ServerError::Unsupported)?;
    // The logd sink on the declared leg (ask-free, TASK-0324 P7-b).
    nexus_log::configure_sink_logd(topo::LOGD.send);
    let mut state = State::new();
    // RFC-0080: create the shared glyph-atlas VMO ONCE (RO-cloned per spawn).
    state.atlas_vmo = crate::atlas_vmo::create();
    let mut recv_frame = alloc::vec![0u8; nexus_abi::IPC_PAYLOAD_MAX]; // ONE buffer (P5b)
    loop {
        match server.recv_request_with_meta_into(Wait::Blocking, &mut recv_frame) {
            Ok((n, sender_service_id, _reply)) => {
                // RFC-0081: reap children that exited since the last request so a spawn first
                // reclaims their AS — the app-launch ALLOC-FAIL fix. Non-blocking, bounded.
                reap_ready_children(&mut state);
                let rsp = handle_frame(&mut state, sender_service_id, &recv_frame[..n]);
                let _ = server.send(rsp.as_slice(), Wait::Blocking);
            }
            Err(nexus_ipc::IpcError::WouldBlock) | Err(nexus_ipc::IpcError::Timeout) => {
                let _ = yield_();
            }
            Err(_) => {
                let _ = yield_();
            }
        }
    }
}

struct TrackedChild {
    pid: u32,
    image_id: u8,
    /// RFC-0081: exit code + ADR-0056 reason once reaped (by the auto-sweep
    /// or an `OP_WAIT_PID`); `None` while still running. Lets `OP_WAIT_PID`
    /// answer from cache after the sweep already reaped the child.
    exit: Option<(i32, ExitReason)>,
    /// The crash-marker / minidump / nexus-log path ran for this exit (once).
    reported: bool,
}

struct State {
    children: Vec<TrackedChild>,
    policy_nonce: u32,
    /// RFC-0080: cap slot of the SHARED atlas VMO (`atlas_vmo` module); RO-cloned per spawn.
    atlas_vmo: Option<u32>,
}

impl State {
    fn new() -> Self {
        Self { children: Vec::new(), policy_nonce: 1, atlas_vmo: None }
    }

    fn track_child(&mut self, pid: u32, image_id: u8) {
        // Keep bounded to avoid unbounded memory; drop oldest.
        const MAX: usize = 16;
        if self.children.len() >= MAX {
            self.children.remove(0);
        }
        self.children.push(TrackedChild { pid, image_id, exit: None, reported: false });
    }

    fn child_name(image_id: u8) -> &'static str {
        match image_id {
            IMG_HELLO => "demo.hello",
            IMG_EXIT0 => "demo.exit0",
            IMG_APPHOST => "app.probe",
            IMG_EXIT42 => "demo.minidump",
            IMG_FAULT => "demo.fault",
            _ => "unknown",
        }
    }

    /// RFC-0081: records a reaped child's exit and runs the crash-marker /
    /// minidump / nexus-log path EXACTLY once (idempotent via `reported`).
    /// Called by both the auto-reap sweep and `OP_WAIT_PID` so exit handling
    /// happens once regardless of which observed the exit first.
    fn handle_child_exit(&mut self, pid: u32, code: i32, reason: ExitReason) {
        let (image_id, already) = match self.children.iter_mut().find(|c| c.pid == pid) {
            Some(child) => {
                let already = child.reported;
                child.exit = Some((code, reason));
                child.reported = true;
                (Some(child.image_id), already)
            }
            None => (None, false),
        };
        if already {
            return;
        }
        // ADR-0056: one exit-truth line per child, exactly once — the reason
        // is kernel-attributed, so a fault kill is no longer indistinguishable
        // from a voluntary `exit(-22)`.
        emit_exit_reason_marker(pid, code, reason);
        // Crash decision on the REAL reason: fault/kill is always a crash,
        // a voluntary non-zero exit stays one (unchanged v1 semantics),
        // a clean exit never is.
        let crashed = matches!(reason, ExitReason::Fault { .. } | ExitReason::Killed) || code != 0;
        if crashed {
            let name = image_id.map(State::child_name).unwrap_or("unknown");
            // For minidump-managed payloads, crash publication is deferred to
            // OP_REPORT_EXIT so dump metadata can be validated before markers.
            if name != "demo.minidump" {
                let build_id = deterministic_build_id(name);
                let dump_path = write_minidump_artifact(pid, code, name, &build_id, reason.label());
                emit_crash_marker(pid, code, name);
                self.log_crash_via_nexus_log(
                    pid,
                    code,
                    name,
                    &build_id,
                    dump_path.as_deref(),
                    reason,
                );
            }
        }
    }

    fn log_crash_via_nexus_log(
        &mut self,
        pid: u32,
        code: i32,
        name: &str,
        build_id: &str,
        dump_path: Option<&str>,
        reason: ExitReason,
    ) {
        // Best-effort: if sink-logd isn't routable, it will fall back to UART-only.
        // Keep the message bounded; sink-logd enforces v1 caps.
        if name == "demo.minidump" && code == 42 {
            // Selftest intentionally executes demo.minidump; keep test-all logs warning-free.
            nexus_log::info("execd", |line| {
                line.text("crash pid=");
                line.dec(pid as u64);
                line.text(" code=");
                // No signed integer helper; emit negative with a prefix.
                if code < 0 {
                    line.text("-");
                    line.dec((-code) as u64);
                } else {
                    line.dec(code as u64);
                }
                line.text(" name=");
                line.text(name);
            });
        } else {
            nexus_log::warn("execd", |line| {
                line.text("crash pid=");
                line.dec(pid as u64);
                line.text(" code=");
                // No signed integer helper; emit negative with a prefix.
                if code < 0 {
                    line.text("-");
                    line.dec((-code) as u64);
                } else {
                    line.dec(code as u64);
                }
                line.text(" name=");
                line.text(name);
            });
        }
        // Append directly to logd (independent of the global sink) so the crash-report selftest can query it.
        let mut ok = false;
        for _ in 0..8 {
            if append_crash_to_logd(pid, code, name, build_id, dump_path, reason).is_ok() {
                ok = true;
                break;
            }
            let _ = yield_();
        }
        if !ok {
            emit_line("execd: crash logd append fail");
        } else {
            emit_line("execd: crash logd append ok");
        }
    }
}

fn append_crash_to_logd(
    pid: u32,
    code: i32,
    name: &str,
    build_id: &str,
    dump_path: Option<&str>,
    reason: ExitReason,
) -> Result<(), ()> {
    const MAGIC0: u8 = b'L';
    const MAGIC1: u8 = b'O';
    const VERSION: u8 = 1;
    const OP_APPEND: u8 = 1;
    const LEVEL_WARN: u8 = 1;
    // The declared logd route slot init pins for execd (TASK-0324 P4e-2).
    const LOGD_SEND_SLOT: u32 = topo::LOGD.send;

    let scope = b"execd";

    // Construct a small, bounded message matching what the selftest searches for ("crash pid=").
    let mut msg = Vec::with_capacity(64);
    msg.extend_from_slice(b"crash pid=");
    push_u32_dec(&mut msg, pid);
    msg.extend_from_slice(b" code=");
    push_i32_dec(&mut msg, code);
    msg.extend_from_slice(b" name=");
    msg.extend_from_slice(name.as_bytes());
    if msg.len() > 256 {
        msg.truncate(256);
    }
    let mut fields = Vec::with_capacity(192);
    // ADR-0056: kernel-attributed exit reason rides the crash.v1 envelope
    // (RFC-0011 reserved extensibility for exactly this kind of field).
    append_field(&mut fields, b"reason=", reason.label().as_bytes());
    append_field(&mut fields, b"build_id=", build_id.as_bytes());
    append_field_i32(&mut fields, b"code=", code);
    if let Some(path) = dump_path {
        append_field(&mut fields, b"dump_path=", path.as_bytes());
    }
    append_field(&mut fields, b"event=", b"crash.v1");
    append_field(&mut fields, b"name=", name.as_bytes());
    append_field_u32(&mut fields, b"pid=", pid);
    append_field_u32(&mut fields, b"recent_count=", 0);
    append_field_u64(&mut fields, b"recent_window_nsec=", 0);
    if fields.len() > 512 {
        fields.truncate(512);
    }

    let mut frame = Vec::with_capacity(10 + scope.len() + msg.len() + fields.len());
    frame.extend_from_slice(&[MAGIC0, MAGIC1, VERSION, OP_APPEND]);
    frame.push(LEVEL_WARN);
    frame.push(scope.len() as u8);
    frame.extend_from_slice(&(msg.len() as u16).to_le_bytes());
    frame.extend_from_slice(&(fields.len() as u16).to_le_bytes());
    frame.extend_from_slice(scope);
    frame.extend_from_slice(&msg);
    frame.extend_from_slice(&fields);

    // Determinism: the crash append is fire-and-forget. logd reply delivery via
    // CAP_MOVE isn't relied on (the reply inbox can be flaky under QEMU); the
    // selftest proves persistence by QUERYING logd for the crash record.
    let hdr = nexus_abi::MsgHeader::new(0, 0, 0, 0, frame.len() as u32);

    nexus_ipc::budget::raw::send_blocking(LOGD_SEND_SLOT, &hdr, &frame).map_err(|e| match e {
        nexus_ipc::IpcError::Timeout => emit_line("execd: crash logd send timeout"),
        nexus_ipc::IpcError::Kernel(inner) => {
            emit_line_no_nl("execd: crash logd send kernel=");
            emit_line(ipc_error_label(inner));
            if inner == nexus_abi::IpcError::NoSuchEndpoint {
                let mut info = nexus_abi::CapQuery { kind_tag: 0, irq: 0, base: 0, len: 0 };
                match nexus_abi::cap_query(LOGD_SEND_SLOT, &mut info) {
                    Ok(()) => {
                        emit_line_no_nl("execd: crash logd slot kind=");
                        emit_u64(info.kind_tag as u64);
                        emit_line("");
                    }
                    Err(_) => emit_line("execd: crash logd slot query err"),
                }
            }
        }
        nexus_ipc::IpcError::NoSpace => emit_line("execd: crash logd send nospace"),
        _ => emit_line("execd: crash logd send err"),
    })?;
    Ok(())
}

fn ipc_error_label(err: nexus_abi::IpcError) -> &'static str {
    match err {
        nexus_abi::IpcError::PermissionDenied => "PermissionDenied",
        nexus_abi::IpcError::NoSuchEndpoint => "NoSuchEndpoint",
        nexus_abi::IpcError::QueueFull => "QueueFull",
        nexus_abi::IpcError::QueueEmpty => "QueueEmpty",
        nexus_abi::IpcError::NoSpace => "NoSpace",
        nexus_abi::IpcError::TooBig => "TooBig",
        nexus_abi::IpcError::TimedOut => "TimedOut",
        nexus_abi::IpcError::PeerClosed => "PeerClosed",
        nexus_abi::IpcError::Unsupported => "Unsupported",
    }
}

fn write_minidump_artifact(
    pid: u32,
    code: i32,
    name: &str,
    build_id: &str,
    reason_label: &str,
) -> Option<String> {
    let ts = nsec().ok().unwrap_or(0);
    let path = normalize_dump_path(ts, pid, name).ok()?;
    let frame = MinidumpFrame {
        timestamp_nsec: ts,
        pid,
        code,
        name: String::from(name),
        build_id: String::from(build_id),
        pcs: Vec::new(),
        stack_preview: Vec::new(),
        code_preview: Vec::new(),
    };
    let bytes = frame.encode().ok()?;
    // TASK-0051B: the canonical at-rest artifact is the `.nxcd` container —
    // written directly (this frame only ever existed in RAM, no
    // intermediate). On degrade the raw NMD1 is persisted instead so crash
    // evidence is never lost (the degrade marker already fired).
    if let Some(key) = crate::crash_store::container_key(path.as_str()) {
        if let Some(published) =
            crate::crash_os::publish_container(&key, &bytes, None, reason_label)
        {
            return Some(published);
        }
    }
    if write_dump_to_statefs(path.as_str(), &bytes).is_err() {
        return None;
    }
    emit_minidump_written(path.as_str());
    Some(path)
}

fn emit_minidump_written(path: &str) {
    emit_line_no_nl("execd: minidump written ");
    for b in path.as_bytes().iter().copied() {
        let _ = debug_putc(b);
    }
    let _ = debug_putc(b'\n');
}

#[must_use]
fn verify_reported_minidump(
    path: &str,
    pid: u32,
    code: i32,
    name: &str,
    build_id: &str,
    dump_bytes: &[u8],
) -> bool {
    if validate_dump_path(path).is_err() {
        return false;
    }
    if !crate::reported_minidump_path_matches_name(path, name) {
        return false;
    }
    let expected_build_id = deterministic_build_id(name);
    if expected_build_id.as_str() != build_id {
        return false;
    }
    let frame = match MinidumpFrame::decode(dump_bytes) {
        Ok(v) => v,
        Err(_) => return false,
    };
    if !crate::reported_minidump_frame_matches_expected(
        crate::MinidumpFrameMetadata {
            pid: frame.pid,
            code: frame.code,
            name: frame.name.as_str(),
            build_id: frame.build_id.as_str(),
        },
        crate::MinidumpFrameMetadata { pid, code, name, build_id },
    ) {
        return false;
    }
    frame.validate().is_ok()
}

fn handle_frame(state: &mut State, sender_service_id: u64, frame: &[u8]) -> Vec<u8> {
    // Request v1: [E, X, ver, op, image_id, stack_pages:u8, requester_len:u8, requester...]
    // Response:   [E, X, ver, op|0x80, status, pid:u32le]
    if frame.len() < 4 || frame[0] != MAGIC0 || frame[1] != MAGIC1 {
        return rsp(OP_EXEC_IMAGE, STATUS_MALFORMED, 0).to_vec();
    }
    if frame[2] != VERSION {
        return rsp(frame[3], STATUS_UNSUPPORTED, 0).to_vec();
    }
    let op = frame[3];
    if op == OP_WAIT_PID {
        // Wait v1: [E,X,ver,OP_WAIT_PID, pid:u32le]
        // Rsp: [E,X,ver,OP_WAIT_PID|0x80, status:u8, pid:u32le, code:i32le]
        if frame.len() != 8 {
            return rsp(op, STATUS_MALFORMED, 0).to_vec();
        }
        let pid = u32::from_le_bytes([frame[4], frame[5], frame[6], frame[7]]) as i32;
        // RFC-0081: the auto-reap sweep may have already reaped this child (its
        // AS freed, exit handled once). Answer from the cached record so a
        // client wait still succeeds instead of failing on a gone kernel zombie.
        if pid > 0 {
            if let Some((code, reason)) =
                state.children.iter().find(|c| c.pid == pid as u32).and_then(|c| c.exit)
            {
                return wait_ok_response(pid as u32, code, reason);
            }
        }
        return match wait_with_reason(pid) {
            Ok((got, code, reason)) => {
                state.handle_child_exit(got, code, reason);
                wait_ok_response(got, code, reason)
            }
            Err(_) => {
                let mut out = Vec::with_capacity(13);
                out.extend_from_slice(&[
                    MAGIC0,
                    MAGIC1,
                    VERSION,
                    OP_WAIT_PID | 0x80,
                    STATUS_FAILED,
                ]);
                out.extend_from_slice(&(pid as u32).to_le_bytes());
                out.extend_from_slice(&(-1i32).to_le_bytes());
                out
            }
        };
    }
    if op == OP_REPORT_EXIT {
        // Report v1: [E,X,ver,OP, pid:u32le, code:i32le]
        // Report v2: [E,X,ver,OP, pid:u32le, code:i32le, build_len:u8, path_len:u16le,
        //             dump_len:u16le, build, path, dump]
        if frame.len() < 4 + 4 + 4 {
            return rsp(op, STATUS_MALFORMED, 0).to_vec();
        }
        let pid = u32::from_le_bytes([frame[4], frame[5], frame[6], frame[7]]);
        let code = i32::from_le_bytes([frame[8], frame[9], frame[10], frame[11]]);
        let trusted_sender = service_id_from_name(b"selftest-client");
        if !crate::crash_event_publish_allowed(
            sender_service_id,
            trusted_sender,
            SID_SELFTEST_CLIENT_ALT,
        ) {
            return rsp(op, STATUS_DENIED, pid).to_vec();
        }

        let reported_meta = if frame.len() == 12 {
            None
        } else {
            if frame.len() < 17 {
                return rsp(op, STATUS_MALFORMED, pid).to_vec();
            }
            let build_len = frame[12] as usize;
            let path_len = u16::from_le_bytes([frame[13], frame[14]]) as usize;
            let dump_len = u16::from_le_bytes([frame[15], frame[16]]) as usize;
            if build_len == 0
                || build_len > 64
                || path_len == 0
                || path_len > 255
                || dump_len == 0
                || dump_len > 4096
                || frame.len() != 17 + build_len + path_len + dump_len
            {
                return rsp(op, STATUS_MALFORMED, pid).to_vec();
            }
            let build_start = 17;
            let build_end = build_start + build_len;
            let path_start = build_end;
            let path_end = path_start + path_len;
            let dump_start = path_end;
            let dump_end = dump_start + dump_len;
            let build_id = match core::str::from_utf8(&frame[build_start..build_end]) {
                Ok(v) => v,
                Err(_) => return rsp(op, STATUS_MALFORMED, pid).to_vec(),
            };
            let dump_path = match core::str::from_utf8(&frame[path_start..path_end]) {
                Ok(v) => v,
                Err(_) => return rsp(op, STATUS_MALFORMED, pid).to_vec(),
            };
            if validate_dump_path(dump_path).is_err() {
                return rsp(op, STATUS_DENIED, pid).to_vec();
            }
            Some((build_id, dump_path, &frame[dump_start..dump_end]))
        };

        let image_id = state.children.iter().find(|c| c.pid == pid).map(|c| c.image_id);
        if let Some(img) = image_id {
            if code != 0 {
                let name = State::child_name(img);
                // ADR-0056 reason as recorded at reap time (voluntary
                // non-zero exits report as "error" when unobserved).
                let reason_label = state
                    .children
                    .iter()
                    .find(|c| c.pid == pid)
                    .and_then(|c| c.exit.map(|(_, r)| r.label()))
                    .unwrap_or("error");
                let (build_id, dump_path) = if let Some((build_id, dump_path, dump_bytes)) =
                    reported_meta
                {
                    if !verify_reported_minidump(dump_path, pid, code, name, build_id, dump_bytes) {
                        return rsp(op, STATUS_FAILED, pid).to_vec();
                    }
                    emit_minidump_written(dump_path);
                    // TASK-0051B: close the NMD1 seam — the verified child
                    // dump converts to the canonical container and the
                    // intermediate is deleted; crash.v1 carries the
                    // artifact that actually remains at rest.
                    let published = crate::crash_store::container_key(dump_path).and_then(|key| {
                        crate::crash_os::publish_container(
                            &key,
                            dump_bytes,
                            Some(dump_path),
                            reason_label,
                        )
                    });
                    (String::from(build_id), published.or(Some(String::from(dump_path))))
                } else if name == "demo.minidump" {
                    // v1 minidump flow requires explicit metadata handoff for managed payloads.
                    return rsp(op, STATUS_FAILED, pid).to_vec();
                } else {
                    let build_id = deterministic_build_id(name);
                    let dump_path =
                        write_minidump_artifact(pid, code, name, &build_id, reason_label);
                    (build_id, dump_path)
                };
                emit_crash_marker(pid, code, name);
                // Reason comes from the reap cache (kernel truth); a report
                // for a child the sweep has not reaped yet falls back to the
                // voluntary reading of the reported code (v1 semantics).
                let reason = state
                    .children
                    .iter()
                    .find(|c| c.pid == pid)
                    .and_then(|c| c.exit)
                    .map(|(_, reason)| reason)
                    .unwrap_or(if code == 0 { ExitReason::Clean } else { ExitReason::Error });
                state.log_crash_via_nexus_log(
                    pid,
                    code,
                    name,
                    build_id.as_str(),
                    dump_path.as_deref(),
                    reason,
                );
            }
            return rsp(op, STATUS_OK, pid).to_vec();
        }
        return rsp(op, STATUS_FAILED, pid).to_vec();
    }
    if op != OP_EXEC_IMAGE {
        return rsp(op, STATUS_UNSUPPORTED, 0).to_vec();
    }
    if frame.len() < 7 {
        return rsp(op, STATUS_MALFORMED, 0).to_vec();
    }
    let image_id = frame[4];
    let stack_pages = frame[5].max(1) as usize;
    let req_len = frame[6] as usize;
    if req_len == 0 || req_len > 48 || frame.len() < 7 + req_len {
        return rsp(op, STATUS_MALFORMED, 0).to_vec();
    }
    let requester = &frame[7..7 + req_len];
    // Append-only extension (TASK-0080D GET_PAYLOAD): an optional app id
    // (`app_len:u8, app...`) names the ui-program payload to fetch from
    // bundlemgrd for the spawned app-host. Absent = legacy frame.
    let app_id = match frame.len() - (7 + req_len) {
        0 => None,
        n if n >= 2 => {
            let alen = frame[7 + req_len] as usize;
            if alen == 0 || alen > 48 || n != 1 + alen {
                return rsp(op, STATUS_MALFORMED, 0).to_vec();
            }
            Some(&frame[8 + req_len..])
        }
        _ => return rsp(op, STATUS_MALFORMED, 0).to_vec(),
    };

    // Security hardening: bind requester identity to the IPC channel.
    // The requester string is treated as *display* only; the authoritative identity is the
    // kernel-derived sender_service_id returned via ipc_recv_v2 metadata.
    let expected_sender_id = service_id_from_name(requester);
    let sender_matches = expected_sender_id == sender_service_id
        || (requester == b"selftest-client" && sender_service_id == SID_SELFTEST_CLIENT_ALT);
    if !sender_matches {
        metrics_counter_inc_best_effort("execd.spawn.deny");
        emit_line_no_nl("execd: spawn id mismatch sender=");
        emit_u64(sender_service_id);
        emit_line_no_nl(" expected=");
        emit_u64(expected_sender_id);
        emit_line_no_nl(" requester=");
        for b in requester.iter().copied().take(48) {
            let _ = debug_putc(b);
        }
        let _ = debug_putc(b'\n');
        emit_line("execd: spawn denied (id mismatch)");
        return rsp(op, STATUS_DENIED, 0).to_vec();
    }

    // Ask init-lite (control channel) to authorize this exec via policyd.
    let nonce: nexus_abi::policy::Nonce = {
        let n = state.policy_nonce;
        state.policy_nonce = state.policy_nonce.wrapping_add(1);
        if state.policy_nonce == 0 {
            state.policy_nonce = 1;
        }
        n
    };
    let mut q = [0u8; 10 + 48];
    let qn = match nexus_abi::policy::encode_exec_check(nonce, requester, image_id, &mut q) {
        Some(n) => n,
        None => return rsp(op, STATUS_MALFORMED, 0).to_vec(),
    };
    // Init-lite may be busy answering ROUTE_GET queries (policyd-gated) during early bring-up:
    // the send waits for queue space, the receive for init's answer — no clock (P7-d). init
    // answers on execd's control channel, which also carries its route answers, so the answer
    // is the frame that decodes as an exec check with OUR nonce (TASK-0054C P2-d). The
    // `ReplyBuffer` that used to sit here could only ever have held a SECOND exec-check answer,
    // which a single-threaded execd handling one spawn at a time never produces — and it
    // dropped a route answer rather than parking it, exactly as `route_with_nonce` drops an
    // exec-check answer in the other direction.
    let ctrl = nexus_service_topology::CTRL_SLOTS;
    if nexus_ipc::exchange::send_request(ctrl.send, &q[..qn]).is_err() {
        return rsp(op, STATUS_FAILED, 0).to_vec();
    }
    let mut rb = [0u8; 16];
    let answer = loop {
        let Ok(n) = nexus_ipc::exchange::recv_response(ctrl.recv, &mut rb) else {
            return rsp(op, STATUS_FAILED, 0).to_vec();
        };
        let n = n.min(rb.len());
        if let Some((got, _)) = nexus_abi::policy::decode_exec_check_rsp(&rb[..n]) {
            if got == nonce {
                break n;
            }
        }
    };
    let rb = &rb[..answer];
    let decision = match crate::decode_exec_policy_decision(rb, nonce) {
        Some(v) => v,
        None => {
            metrics_counter_inc_best_effort("execd.spawn.deny");
            emit_line("execd: spawn denied (policy malformed)");
            return rsp(op, STATUS_DENIED, 0).to_vec();
        }
    };
    if decision != nexus_abi::policy::STATUS_ALLOW {
        metrics_counter_inc_best_effort("execd.spawn.deny");
        emit_line("execd: spawn denied (policy)");
        return rsp(op, STATUS_DENIED, 0).to_vec();
    }
    if !crate::spawn_caps_respect_vfs_boundary(&RUNTIME_APP_CAPS) {
        metrics_counter_inc_best_effort("execd.spawn.deny");
        emit_line("execd: spawn denied (fs cap boundary)");
        return rsp(op, STATUS_DENIED, 0).to_vec();
    }

    let elf = match image_id {
        IMG_HELLO => HELLO_ELF,
        IMG_EXIT0 => DEMO_EXIT0_ELF,
        IMG_EXIT42 => DEMO_MINIDUMP_ELF,
        IMG_FAULT => demo_exit0::DEMO_FAULT_ELF,
        IMG_APPHOST if !apphost_payload::APPHOST_ELF.is_empty() => apphost_payload::APPHOST_ELF,
        _ => return rsp(op, STATUS_UNSUPPORTED, 0).to_vec(),
    };
    // GET_PAYLOAD (TASK-0080D): kick the payload fetch BEFORE the ELF load so
    // bundlemgrd fills the VMO while we spawn; its answer is waited for right before
    // the child is resumed (P7-d) — the child reads a complete header, never polls.
    // `None` = the child fails closed (visibly marked on both sides).
    let payload_vmo = match (image_id, app_id) {
        (IMG_APPHOST, Some(app)) => fetch_app_payload(app),
        _ => None,
    };
    let start_ns = nsec().ok().unwrap_or(0);
    let local = EXEC_SPAN_LOCAL.fetch_add(1, Ordering::Relaxed);
    let span_id = SpanId(((sender_service_id & 0xffff_ffff) << 32) | (local & 0xffff_ffff));
    let mut ids = DeterministicIdSource::new(sender_service_id);
    let trace_id = ids.next_trace_id();
    metrics_span_start_best_effort(span_id, trace_id, "execd.exec", b"svc=execd\n");
    // RFC-0086 identity keystone: app-hosts spawn via exec_v2 with a
    // kernel-attributed service name `app:<bundle_id>` — execd (the spawner)
    // is the ONLY naming authority, and the `app:` prefix makes impersonating
    // a boot service impossible by construction. Every later ipc_recv_v2
    // then carries a real `sender_service_id` for this child (windowd's
    // `owner_sid` capture, taskbar verbs, CONTROL_WIN_* owner checks).
    // Non-app images and a malformed app id keep the legacy nameless exec
    // (sid 0 = no window authority — fail-closed, never fail-open).
    let spawned = match (image_id, app_id) {
        (IMG_APPHOST, Some(app)) => match crate::identity::app_service_name(app) {
            Some(name) => nexus_abi::exec_v2(elf, stack_pages, 0, name.as_str()),
            None => exec(elf, stack_pages, 0),
        },
        _ => exec(elf, stack_pages, 0),
    };
    match spawned {
        Ok(pid) => {
            state.track_child(pid as u32, image_id);
            apply_sched_recipe(pid as u32, image_id);
            if image_id == IMG_APPHOST {
                crate::child_grants::grant_windowd_route(pid as u32);
                if let Some(vmo) = payload_vmo {
                    crate::child_grants::grant_payload_vmo(pid as u32, vmo);
                }
                // Dedicated event channel: attach windowd's SEND half FIRST
                // (same request queue the child's SURFACE_CREATE uses, so
                // windowd holds the channel before the create), then hand
                // the RECV half to the child — all before resume.
                crate::child_grants::grant_event_channel(pid as u32);
                crate::child_grants::grant_timer_channel(pid as u32);
                // RFC-0080: RO clone of the shared atlas VMO (before resume).
                crate::atlas_vmo::grant(pid as u32, state.atlas_vmo);
                // TASK-0080C: provision the app's DECLARED service routes
                // (@reply inbox + one SEND per routable manifest cap) into the
                // child's fixed SDK slots — cap-gated, before resume.
                if let Some(app) = app_id {
                    provision_app_service_routes(pid as u32, app);
                }
            }
            // TASK-0049 reanimation: the demo.minidump payload PUTs its own
            // NMD1 dump via statefs slots 7/8 (in-process capture, RFC-0031).
            // Under the #102 resume fix children run immediately, so the old
            // post-spawn transfer from the selftest raced the child's exit
            // (transfer into a reaped task collapses to EPERM). The SPAWNER
            // installs the route before resume — same grants-before-resume
            // discipline as the app-host grants above.
            if image_id == IMG_EXIT42 {
                crate::child_grants::grant_minidump_statefs_route(pid as u32);
            }
            // #102 ROOT CAUSE FIX: `spawn_inner` starts EVERY task Suspended
            // (the grants-before-resume hardening); nexus-init resumes its
            // services explicitly after cap wiring — execd never did, so its
            // children loaded but never executed. Resume AFTER the grants
            // above (same grants-before-resume discipline).
            // The payload answer (TASK-0324 P7-d): bundlemgrd wrote the header LAST and
            // replied — the child starts with a complete payload or a marked failure.
            if payload_vmo.is_some() && !await_app_payload() {
                emit_line("execd: FAIL app payload (unserved)");
            }
            if nexus_abi::task_resume(pid as u32).is_err() {
                emit_line("execd: FAIL child resume");
            }
            metrics_counter_inc_best_effort("execd.spawn.ok");
            let end_ns = nsec().ok().unwrap_or(start_ns);
            metrics_span_end_best_effort(span_id, end_ns, 0, b"result=ok\n");
            rsp(op, STATUS_OK, pid as u32).to_vec()
        }
        Err(_) => {
            if let Some(vmo) = payload_vmo {
                let _ = nexus_abi::cap_close(vmo);
            }
            metrics_counter_inc_best_effort("execd.spawn.fail");
            let end_ns = nsec().ok().unwrap_or(start_ns);
            metrics_span_end_best_effort(span_id, end_ns, 1, b"result=fail\n");
            rsp(op, STATUS_FAILED, 0).to_vec()
        }
    }
}

/// GET_PAYLOAD (TASK-0080D, TASK-0324 P7-d): creates the payload VMO, ARMS it at bundlemgrd
/// (`OP_ARM_VMO`, a clone as the moved cap) and asks for the payload with a reply-cap clone
/// riding the request. bundlemgrd fills the VMO while we spawn; `await_app_payload` waits for
/// its answer before the child is resumed. Both sends wait for queue space — no clock.
/// Returns the ORIGINAL VMO cap (destined for child slot 7), or `None` on any failure
/// (marked; the child fails closed at its header read).
fn fetch_app_payload(app_id: &[u8]) -> Option<u32> {
    let vmo = match nexus_abi::vmo_create(PAYLOAD_VMO_BYTES) {
        Ok(v) => v,
        Err(_) => {
            emit_line("execd: FAIL app payload (vmo create)");
            return None;
        }
    };
    let close_all = |extra: Option<u32>| {
        if let Some(c) = extra {
            let _ = nexus_abi::cap_close(c);
        }
        let _ = nexus_abi::cap_close(vmo);
    };
    let mut frame = [0u8; 64];
    let Some(len) = nexus_abi::bundlemgrd::encode_get_payload(app_id, &mut frame) else {
        emit_line("execd: FAIL app payload (encode)");
        close_all(None);
        return None;
    };
    let Ok(clone) = nexus_abi::cap_clone(vmo) else {
        emit_line("execd: FAIL app payload (cap clone)");
        close_all(None);
        return None;
    };
    let mut arm = [0u8; 4];
    nexus_abi::bundlemgrd::encode_arm_vmo(&mut arm);
    // The moved cap is the destination VMO — data, not an inbox.
    if nexus_ipc::exchange::send_with_cap(BUNDLE_SEND_SLOT, &arm, clone).is_err() {
        emit_line("execd: FAIL app payload (arm send)");
        close_all(Some(clone));
        return None;
    }
    // The ask is started here and COLLECTED in `await_app_payload` below: bundlemgrd streams
    // into the armed VMO while execd loads the ELF. A started exchange whose answer is read
    // later is `send_call`; a send whose answer nobody reads is the defect P2-c removed.
    if nexus_ipc::exchange::send_call(BUNDLE_SEND_SLOT, topo::REPLY, &frame[..len]).is_err() {
        emit_line("execd: FAIL app payload (send)");
        close_all(None);
        return None;
    }
    emit_line("execd: app payload requested");
    Some(vmo)
}

/// Waits for bundlemgrd's GET_PAYLOAD answer on the reply inbox (TASK-0324 P7-d): the header
/// is complete when it arrives; bundlemgrd's death ends the wait (EOF). Foreign frames on the
/// shared inbox (late acks) are skipped. `true` = the payload is served OK.
fn await_app_payload() -> bool {
    let mut buf = [0u8; 64];
    loop {
        let Ok(n) = nexus_ipc::exchange::recv_reply(topo::REPLY.recv, &mut buf) else {
            emit_line("execd: FAIL app payload (no answer)");
            return false;
        };
        let n = n.min(buf.len());
        if let Some((status, _)) = nexus_abi::bundlemgrd::decode_payload_done_rsp(
            &buf[..n],
            nexus_abi::bundlemgrd::OP_GET_PAYLOAD,
        ) {
            if status != nexus_abi::status::CODE_OK {
                emit_line("execd: FAIL app payload (status)");
            }
            return status == nexus_abi::status::CODE_OK;
        }
    }
}

// The execd-side attach is DELETED: the child attaches its OWN channel to
// windowd, nonce-tagged (deterministic channel↔surface binding — the execd
// attach carried no identity and crossed under concurrent launches).

fn rsp(op: u8, status: u8, pid: u32) -> [u8; 9] {
    let mut out = [0u8; 9];
    out[0] = MAGIC0;
    out[1] = MAGIC1;
    out[2] = VERSION;
    out[3] = op | 0x80;
    out[4] = status;
    out[5..9].copy_from_slice(&pid.to_le_bytes());
    out
}

/// The caps a spawned app's manifest declares (generated table), or `&[]` if
/// the app has no manifest entry — the fail-closed set execd provisions routes
/// for (a cap not declared here is never wired, even if the SDK maps it).
fn caps_for(app_id: &str) -> &'static [&'static str] {
    app_caps::APP_MANIFEST_CAPS
        .iter()
        .find(|(id, _)| *id == app_id)
        .map(|(_, caps)| *caps)
        .unwrap_or(&[])
}

/// Resolves a service (or `@reply`) name to its `(send, recv)` slots via
/// execd's init control channel — the same responder bahn
/// windowd/abilitymgr route through. `None` on any routing failure (policyd
/// deny, timeout, exhausted nonce budget); the caller then skips that route.
pub(crate) fn route_ctrl(name: &[u8]) -> Option<(u32, u32)> {
    use nexus_ipc::budget::{self, NonceMismatchBudget, RouteRetryOutcome};
    match budget::route_with_nonce(name, NonceMismatchBudget::new(64)) {
        RouteRetryOutcome::Success { send_slot, recv_slot } => Some((send_slot, recv_slot)),
        _ => None,
    }
}

/// TASK-0080C declarative routing: provisions the spawned app-host child's
/// service routes from its manifest caps. For every declared cap that
/// `nexus-sdk-routes` maps to a backing OS service, execd resolves the route
/// via its control channel and grants a SEND clone into the child's FIXED SDK
/// slot (`ServiceRoute::child_slot`). It also resolves a FRESH `@reply` inbox
/// for the child (RECV → slot 9, SEND → slot 10) so the child can move a reply
/// cap per request without sharing execd's own inbox. Cap-gated + fail-soft:
/// an app with no routable cap is a no-op; an unresolvable route is skipped
/// with a marker and the child presence-probes the empty slot.
fn provision_app_service_routes(child_pid: u32, app_id: &[u8]) {
    let Ok(app) = core::str::from_utf8(app_id) else {
        return;
    };
    let caps = caps_for(app);
    if !caps.iter().any(|c| nexus_sdk_routes::route_for_permission(c).is_some()) {
        // No system-service cap ⇒ nothing to route (the common app case).
        return;
    }

    // Fresh per-launch PRIVATE reply inbox: init mints a new pair
    // (`@mint-pair`); both halves go to the child (it clones the SEND per
    // request; service replies land on the RECV half). NEVER `@reply` here —
    // that returns execd's own PERSISTENT shared inbox: granting it put every
    // child on ONE reply queue (cross-process reply theft), and closing it
    // after the grant destroyed execd's inbox slots, so launch 2+ logged
    // `FAIL app reply inbox grant` (boot-proven 2026-07-10).
    match route_ctrl(b"@mint-pair") {
        Some((send_slot, recv_slot)) => {
            let ok_recv = crate::child_grants::grant_clone(
                child_pid,
                recv_slot,
                nexus_abi::Rights::RECV,
                nexus_sdk_routes::CHILD_REPLY_RECV_SLOT,
            );
            let ok_send = crate::child_grants::grant_clone(
                child_pid,
                send_slot,
                nexus_abi::Rights::SEND,
                nexus_sdk_routes::CHILD_REPLY_SEND_SLOT,
            );
            if ok_recv && ok_send {
                let _ = nexus_abi::debug_println("execd: app reply inbox granted (minted)");
            } else {
                let _ = nexus_abi::debug_println("execd: FAIL app reply inbox grant");
            }
            // Close execd's own halves of the MINTED pair post-grant — the
            // child holds the only live references (mint→grant→close, zero
            // cap-table accumulation).
            let _ = nexus_abi::cap_close(send_slot);
            let _ = nexus_abi::cap_close(recv_slot);
        }
        None => {
            let _ = nexus_abi::debug_println("execd: FAIL app reply inbox mint");
        }
    }

    // One SEND route per declared + routable cap → its fixed child SDK slot.
    for cap in caps {
        let Some(route) = nexus_sdk_routes::route_for_permission(cap) else {
            continue;
        };
        match route_ctrl(route.route.as_bytes()) {
            Some((send_slot, _recv_slot)) => {
                let ok = crate::child_grants::grant_clone(
                    child_pid,
                    send_slot,
                    nexus_abi::Rights::SEND,
                    route.child_slot,
                );
                // Do NOT close these slots: named routes resolve to execd's
                // PERSISTENT route-table slots (recorded once at wiring) — the
                // responder answers every later resolve with the SAME slot
                // numbers. Closing them poisoned the table: launch 2+ cloned
                // empty (or worse, REUSED) slots. Resolving mints nothing, so
                // there is nothing to free.
                emit_line_no_nl(if ok {
                    "execd: app route granted svc="
                } else {
                    "execd: FAIL app route grant svc="
                });
                emit_line_no_nl(route.svc);
                let _ = debug_putc(b'\n');
            }
            None => {
                emit_line_no_nl("execd: FAIL app route resolve svc=");
                emit_line_no_nl(route.svc);
                let _ = debug_putc(b'\n');
            }
        }
    }
}

/// Stubbed bundle exec helper exposed for API compatibility.
pub fn exec_elf(
    _bundle: &str,
    _argv: &[&str],
    _env: &[&str],
    _restart: RestartPolicy,
) -> Result<Pid, ExecError> {
    Err(ExecError::Unsupported)
}

pub(crate) fn emit_line(message: &str) {
    // Verdict folding: pre-`ready` markers tally into `execd N/N`; post-`ready` runtime lines fold
    // into recall-only detail (`NEXUS_LOG_EXPAND=execd`). Failures & proof boots print live & raw.
    // One atomic `debug_write` (via `debug_println`, which also owns the verdict
    // folding): the per-byte `debug_putc` fallback tears mid-line against the
    // kernel's locked log records and DROPS the tail — a torn ready marker is a
    // red ladder gate.
    let _ = nexus_abi::debug_println(message);
}

/// ADR-0056 exit-truth line — one per reaped child, exactly once:
/// `execd: exit pid=<p> reason=<label> code=<c>`.
fn emit_exit_reason_marker(pid: u32, code: i32, reason: ExitReason) {
    emit_line_no_nl("execd: exit pid=");
    emit_u64(pid as u64);
    emit_line_no_nl(" reason=");
    emit_line_no_nl(reason.label());
    emit_line_no_nl(" code=");
    emit_i64(code as i64);
    let _ = debug_putc(b'\n');
}

fn emit_crash_marker(pid: u32, code: i32, name: &str) {
    emit_line_no_nl("execd: crash report pid=");
    emit_u64(pid as u64);
    emit_line_no_nl(" code=");
    emit_i64(code as i64);
    emit_line_no_nl(" name=");
    for b in name.as_bytes() {
        let _ = debug_putc(*b);
    }
    let _ = debug_putc(b'\n');
}

fn emit_line_no_nl(message: &str) {
    for byte in message.as_bytes().iter().copied() {
        let _ = debug_putc(byte);
    }
}

fn metrics_counter_inc_best_effort(name: &str) {
    let Ok(metrics) = MetricsClient::new() else {
        return;
    };
    let _ = metrics.counter_inc(name, b"svc=execd\n", 1);
}

fn metrics_span_start_best_effort(
    span_id: SpanId,
    trace_id: nexus_metrics::TraceId,
    name: &str,
    attrs: &[u8],
) {
    let Ok(metrics) = MetricsClient::new() else {
        return;
    };
    let _ = metrics.span_start(span_id, trace_id, SpanId(0), nsec().ok().unwrap_or(0), name, attrs);
}

fn metrics_span_end_best_effort(span_id: SpanId, end_ns: u64, status: u8, attrs: &[u8]) {
    let Ok(metrics) = MetricsClient::new() else {
        return;
    };
    let _ = metrics.span_end(span_id, end_ns, status, attrs);
}

fn emit_u64(mut value: u64) {
    let mut buf = [0u8; 20];
    let mut idx = buf.len();
    if value == 0 {
        idx -= 1;
        buf[idx] = b'0';
    } else {
        while value != 0 {
            idx -= 1;
            buf[idx] = b'0' + (value % 10) as u8;
            value /= 10;
        }
    }
    for &b in &buf[idx..] {
        let _ = debug_putc(b);
    }
}

fn emit_i64(value: i64) {
    if value < 0 {
        let _ = debug_putc(b'-');
        emit_u64((-value) as u64);
    } else {
        emit_u64(value as u64);
    }
}

// (helpers removed; crash record is emitted through nexus-log sink-logd)
