// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0

//! CONTEXT: OS-lite backend for the execd (execution daemon) service. Handles process
//! execution, crash reporting with minidump artifacts, and crash record forwarding to logd
//! via budgeted IPC. Provides the cooperative service main loop for the lite runtime.
//! OWNERS: @runtime
//! STATUS: Functional
//! API_STABILITY: Unstable
//! TEST_COVERAGE: No tests
//! ADR: docs/adr/0007-executable-payloads-architecture.md

#![cfg(all(nexus_env = "os", feature = "os-lite"))]

extern crate alloc;

use alloc::boxed::Box;
use alloc::string::String;
use alloc::vec::Vec;

use core::fmt;
use core::sync::atomic::{AtomicU64, Ordering};
use core::time::Duration;

use nexus_abi::{debug_putc, exec, nsec, service_id_from_name, wait, yield_, Pid};
use nexus_ipc::budget::{deadline_after, OsClock};
use nexus_ipc::reqrep::{recv_match_until, ReplyBuffer};
use nexus_ipc::{KernelServer, Server as _, Wait};
use nexus_metrics::client::MetricsClient;
use nexus_metrics::{DeterministicIdSource, SpanId};

use crash::{
    deterministic_build_id, normalize_dump_path, validate_dump_path, write_dump_to_statefs,
    MinidumpFrame,
};
use demo_exit0::{DEMO_EXIT0_ELF, DEMO_MINIDUMP_ELF};
use exec_payloads::HELLO_ELF;
use nexus_log;

/// Result alias surfaced by the lite execd backend.
pub type LiteResult<T> = Result<T, ServerError>;

/// Restart policy for launched services.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RestartPolicy {
    /// Never restart the service after exit.
    Never,
    /// Always restart the service when it exits.
    Always,
}

/// Ready notifier invoked once execd finishes initialization.
pub struct ReadyNotifier(Box<dyn FnOnce() + Send>);

impl ReadyNotifier {
    /// Creates a notifier from the provided closure.
    pub fn new<F>(func: F) -> Self
    where
        F: FnOnce() + Send + 'static,
    {
        Self(Box::new(func))
    }

    /// Signals readiness to the caller.
    pub fn notify(self) {
        (self.0)();
    }
}

/// Errors surfaced by the lite execd backend.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ServerError {
    /// Placeholder error until the lite backend is implemented.
    Unsupported,
}

impl fmt::Display for ServerError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unsupported => write!(f, "execd unsupported"),
        }
    }
}

/// Errors returned by exec helpers on the lite backend.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ExecError {
    /// Functionality not available yet.
    Unsupported,
}

impl fmt::Display for ExecError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unsupported => write!(f, "exec unsupported"),
        }
    }
}

/// Schema warmer placeholder retained for parity.
pub fn touch_schemas() {}

const MAGIC0: u8 = b'E';
const MAGIC1: u8 = b'X';
const VERSION: u8 = 1;

const OP_EXEC_IMAGE: u8 = 1;
const OP_REPORT_EXIT: u8 = 2;
const OP_WAIT_PID: u8 = 3;

const IMG_HELLO: u8 = 1;
const IMG_EXIT0: u8 = 2;
const IMG_EXIT42: u8 = 3;
/// TASK-0080D R1: the app-host runtime (ADR-0042 transport probe). The ELF is
/// embedded by `build.rs` when `scripts/build.sh` provides it; empty ⇒
/// UNSUPPORTED (fail-closed, never a fake payload).
const IMG_APPHOST: u8 = 4;

// Generated by build.rs: `APPHOST_ELF` (may be empty on plain cargo builds).
mod apphost_payload {
    include!(concat!(env!("OUT_DIR"), "/apphost_payload.rs"));
}

// Generated by build.rs: `RECVWAKE_ELF` (may be empty on plain cargo builds).
mod recvwake_payload {
    include!(concat!(env!("OUT_DIR"), "/recvwake_payload.rs"));
}

// Generated by build.rs: `APP_MANIFEST_CAPS` (app → declared caps) from the
// real bundle manifests — the SSOT that gates which service routes execd
// provisions for a spawned app-host (TASK-0080C declarative routing).
mod app_caps {
    include!(concat!(env!("OUT_DIR"), "/app_manifest_caps.rs"));
}

/// execd's own capability slots holding the windowd client route for spawned
/// app processes (granted by nexus-init in the execd wiring arm, slot-order
/// convention like `LOGD_SEND_SLOT`; init logs `init: execd windowd slots`).
const APP_WINDOWD_SEND_SLOT: u32 = 8;
const APP_WINDOWD_RECV_SLOT: u32 = 9;
/// The child slots the app-host expects them in (its fixed constants).
const CHILD_WINDOWD_SEND_SLOT: u32 = 5;
const CHILD_WINDOWD_RECV_SLOT: u32 = 6;
/// GET_PAYLOAD (TASK-0080D): execd's own slot holding the bundlemgrd request
/// SEND cap (granted by nexus-init in the execd arm — slot-order contract,
/// proven by `init: execd bundle slot send=0xa`).
const BUNDLE_SEND_SLOT: u32 = 10;
/// The child slot receiving the payload VMO (app-host's fixed constant).
const CHILD_PAYLOAD_SLOT: u32 = 7;
/// Payload VMO budget: 16-byte header + up to ~256KB canonical `.nxir`
/// (counter is ~4KB; the bound is the transport contract, not a hint).
const PAYLOAD_VMO_BYTES: usize = 16 + 256 * 1024;
/// ADR-0042 per-app event channel (init-minted pair; slot-order contract,
/// proven by `init: execd app-event slots send=0xb recv=0xc`): windowd gets
/// a SEND clone (`OP_SURFACE_EVENTS`, cap-move) and delivers input events +
/// surface acks on it; the child gets a RECV clone. Replaces the shared
/// `window_rsp` delivery, which raced with inputd's ack drain (taps were
/// consumed by inputd before the app ever saw them).
// Per-app event channels are minted DYNAMICALLY per launch via init's ctrl
// plane (`@mint-pair`): init — the EndpointFactory holder — mints a fresh
// PRIVATE pair on demand; execd does mint→grant→close (zero cap-table
// accumulation). No static pair, no pool sizing, no slot-order contract —
// the whole "adjust the pool after every feature" class is retired.
/// The child slot receiving the event-channel RECV (app-host's constant).
const CHILD_EVENTS_SLOT: u32 = 8;
/// SEND clone of the child's OWN event channel (it attaches this to windowd
/// itself, nonce-tagged). After the service SEND slots 11..13 (nexus-sdk-routes).
const CHILD_EVENTS_SEND_SLOT: u32 = 14;
/// P0.2 recv-wake regression gate (init-minted pairs; slot-order contract,
/// proven by `init: execd recv-wake slots …`): TWO one-way endpoints for the
/// probe handshake — ping (execd SEND @13, child RECV granted into child
/// slot 5) and reply (child SEND granted into child slot 6, execd RECV @16).
/// Two endpoints because a single shared queue would let execd's reply-wait
/// steal the ping it just sent to the parked child.
const PROBE_PING_SEND_SLOT: u32 = 11;
const PROBE_PING_RECV_SLOT: u32 = 12;
const PROBE_REPLY_SEND_SLOT: u32 = 13;
const PROBE_REPLY_RECV_SLOT: u32 = 14;
/// The probe child's fixed slots (recv-wake-probe's constants).
const PROBE_CHILD_PING_RECV_SLOT: u32 = 5;
const PROBE_CHILD_REPLY_SEND_SLOT: u32 = 6;
/// Probe wire bytes (pinned in recv-wake-probe/src/main.rs).
const PROBE_MSG_ARMED: u8 = 0xA1;
const PROBE_MSG_WOKE: u8 = 0xA2;
// Bring-up alias: kernel currently reports selftest-client under this stable sender ID.
// Keep identity binding strict by accepting only this exact alternate for that requester.
const SID_SELFTEST_CLIENT_ALT: u64 = 0x68c1_66c3_7bcd_7154;

const STATUS_OK: u8 = 0;
const STATUS_MALFORMED: u8 = 1;
const STATUS_UNSUPPORTED: u8 = 2;
const STATUS_FAILED: u8 = 3;
const STATUS_DENIED: u8 = 4;
static EXEC_SPAN_LOCAL: AtomicU64 = AtomicU64::new(1);
const RUNTIME_APP_CAPS: [&str; 4] = ["vfsd", "samgrd", "policyd", "logd"];

/// Stubbed service loop that reports readiness and yields forever.
pub fn service_main_loop(notifier: ReadyNotifier) -> LiteResult<()> {
    // Verdict folding → `execd N/N` (interactive); flushed at ready, later exec markers print raw.
    nexus_abi::service_verdict_arm();
    notifier.notify();
    emit_line("execd: ready");
    nexus_abi::service_verdict_flush("execd");
    // P0.2 regression gate: one bounded probe run per boot (post-flush so its
    // markers print raw). Proves — or loudly reproduces — the sender-wake of
    // an exec'd child parked in a blocking ipc recv (#102 family).
    run_recv_wake_probe();
    let server = match KernelServer::new_for("execd") {
        Ok(server) => server,
        Err(_) => KernelServer::new_with_slots(3, 4).map_err(|_| ServerError::Unsupported)?,
    };
    let mut state = State::new();
    loop {
        match server.recv_with_header_meta(Wait::Blocking) {
            Ok((_hdr, sender_service_id, frame)) => {
                let rsp = handle_frame(&mut state, sender_service_id, frame.as_slice());
                let _ = server.send(rsp.as_slice(), Wait::Blocking);
            }
            Err(nexus_ipc::IpcError::WouldBlock) | Err(nexus_ipc::IpcError::Timeout) => {
                let _ = yield_();
            }
            Err(_) => {
                let _ = yield_();
            }
        }
    }
}

struct TrackedChild {
    pid: u32,
    image_id: u8,
}

struct State {
    children: Vec<TrackedChild>,
    policy_nonce: u32,
    pending_policy: ReplyBuffer<8, 16>,
}

impl State {
    fn new() -> Self {
        Self { children: Vec::new(), policy_nonce: 1, pending_policy: ReplyBuffer::new() }
    }

    fn track_child(&mut self, pid: u32, image_id: u8) {
        // Keep bounded to avoid unbounded memory; drop oldest.
        const MAX: usize = 16;
        if self.children.len() >= MAX {
            self.children.remove(0);
        }
        self.children.push(TrackedChild { pid, image_id });
    }

    fn child_name(image_id: u8) -> &'static str {
        match image_id {
            IMG_HELLO => "demo.hello",
            IMG_EXIT0 => "demo.exit0",
            IMG_APPHOST => "app.probe",
            IMG_EXIT42 => "demo.minidump",
            _ => "unknown",
        }
    }

    fn log_crash_via_nexus_log(
        &mut self,
        pid: u32,
        code: i32,
        name: &str,
        build_id: &str,
        dump_path: Option<&str>,
    ) {
        // Best-effort: if sink-logd isn't routable, it will fall back to UART-only.
        // Keep the message bounded; sink-logd enforces v1 caps.
        if name == "demo.minidump" && code == 42 {
            // Selftest intentionally executes demo.minidump; keep test-all logs warning-free.
            nexus_log::info("execd", |line| {
                line.text("crash pid=");
                line.dec(pid as u64);
                line.text(" code=");
                // No signed integer helper; emit negative with a prefix.
                if code < 0 {
                    line.text("-");
                    line.dec((-code) as u64);
                } else {
                    line.dec(code as u64);
                }
                line.text(" name=");
                line.text(name);
            });
        } else {
            nexus_log::warn("execd", |line| {
                line.text("crash pid=");
                line.dec(pid as u64);
                line.text(" code=");
                // No signed integer helper; emit negative with a prefix.
                if code < 0 {
                    line.text("-");
                    line.dec((-code) as u64);
                } else {
                    line.dec(code as u64);
                }
                line.text(" name=");
                line.text(name);
            });
        }
        // Also append directly to logd so the crash-report selftest can deterministically query it,
        // independent of the global nexus-log sink wiring.
        let mut ok = false;
        for _ in 0..8 {
            if append_crash_to_logd(pid, code, name, build_id, dump_path).is_ok() {
                ok = true;
                break;
            }
            let _ = yield_();
        }
        if !ok {
            emit_line("execd: crash logd append fail");
        } else {
            emit_line("execd: crash logd append ok");
        }
    }
}

fn append_crash_to_logd(
    pid: u32,
    code: i32,
    name: &str,
    build_id: &str,
    dump_path: Option<&str>,
) -> Result<(), ()> {
    const MAGIC0: u8 = b'L';
    const MAGIC1: u8 = b'O';
    const VERSION: u8 = 1;
    const OP_APPEND: u8 = 1;
    const LEVEL_WARN: u8 = 1;
    // Deterministic logd send slot distributed by init-lite for execd.
    const LOGD_SEND_SLOT: u32 = 7;

    let scope = b"execd";

    // Construct a small, bounded message matching what the selftest searches for ("crash pid=").
    let mut msg = Vec::with_capacity(64);
    msg.extend_from_slice(b"crash pid=");
    push_u32_dec(&mut msg, pid);
    msg.extend_from_slice(b" code=");
    push_i32_dec(&mut msg, code);
    msg.extend_from_slice(b" name=");
    msg.extend_from_slice(name.as_bytes());
    if msg.len() > 256 {
        msg.truncate(256);
    }
    let mut fields = Vec::with_capacity(192);
    append_field(&mut fields, b"build_id=", build_id.as_bytes());
    append_field_i32(&mut fields, b"code=", code);
    if let Some(path) = dump_path {
        append_field(&mut fields, b"dump_path=", path.as_bytes());
    }
    append_field(&mut fields, b"event=", b"crash.v1");
    append_field(&mut fields, b"name=", name.as_bytes());
    append_field_u32(&mut fields, b"pid=", pid);
    append_field_u32(&mut fields, b"recent_count=", 0);
    append_field_u64(&mut fields, b"recent_window_nsec=", 0);
    if fields.len() > 512 {
        fields.truncate(512);
    }

    let mut frame = Vec::with_capacity(10 + scope.len() + msg.len() + fields.len());
    frame.extend_from_slice(&[MAGIC0, MAGIC1, VERSION, OP_APPEND]);
    frame.push(LEVEL_WARN);
    frame.push(scope.len() as u8);
    frame.extend_from_slice(&(msg.len() as u16).to_le_bytes());
    frame.extend_from_slice(&(fields.len() as u16).to_le_bytes());
    frame.extend_from_slice(scope);
    frame.extend_from_slice(&msg);
    frame.extend_from_slice(&fields);

    // Determinism: treat the crash append as fire-and-forget.
    //
    // logd reply delivery via CAP_MOVE is not relied upon here because the reply inbox
    // plumbing can be flaky under QEMU. The selftest proves persistence by querying logd
    // for the crash record contents (not by receiving the APPEND response).
    let hdr = nexus_abi::MsgHeader::new(0, 0, 0, 0, frame.len() as u32);
    let clock = nexus_ipc::budget::OsClock;
    let deadline_ns = nexus_ipc::budget::deadline_after(&clock, core::time::Duration::from_secs(2))
        .map_err(|_| ())?;

    nexus_ipc::budget::raw::send_budgeted(&clock, LOGD_SEND_SLOT, &hdr, &frame, deadline_ns)
        .map_err(|e| {
            match e {
                nexus_ipc::IpcError::Timeout => emit_line("execd: crash logd send timeout"),
                nexus_ipc::IpcError::Kernel(inner) => {
                    emit_line_no_nl("execd: crash logd send kernel=");
                    emit_line(ipc_error_label(inner));
                    if inner == nexus_abi::IpcError::NoSuchEndpoint {
                        let mut info =
                            nexus_abi::CapQuery { kind_tag: 0, reserved: 0, base: 0, len: 0 };
                        match nexus_abi::cap_query(LOGD_SEND_SLOT, &mut info) {
                            Ok(()) => {
                                emit_line_no_nl("execd: crash logd slot kind=");
                                emit_u64(info.kind_tag as u64);
                                emit_line("");
                            }
                            Err(_) => emit_line("execd: crash logd slot query err"),
                        }
                    }
                }
                nexus_ipc::IpcError::NoSpace => emit_line("execd: crash logd send nospace"),
                other => {
                    let _ = other;
                    emit_line("execd: crash logd send err");
                }
            }
            ()
        })?;
    Ok(())
}

fn ipc_error_label(err: nexus_abi::IpcError) -> &'static str {
    match err {
        nexus_abi::IpcError::PermissionDenied => "PermissionDenied",
        nexus_abi::IpcError::NoSuchEndpoint => "NoSuchEndpoint",
        nexus_abi::IpcError::QueueFull => "QueueFull",
        nexus_abi::IpcError::QueueEmpty => "QueueEmpty",
        nexus_abi::IpcError::NoSpace => "NoSpace",
        nexus_abi::IpcError::TimedOut => "TimedOut",
        nexus_abi::IpcError::Unsupported => "Unsupported",
    }
}

fn push_u32_dec(out: &mut Vec<u8>, mut value: u32) {
    let mut tmp = [0u8; 10];
    let mut i = tmp.len();
    if value == 0 {
        out.push(b'0');
        return;
    }
    while value != 0 && i != 0 {
        let digit = (value % 10) as u8;
        value /= 10;
        i -= 1;
        tmp[i] = b'0' + digit;
    }
    out.extend_from_slice(&tmp[i..]);
}

fn push_i32_dec(out: &mut Vec<u8>, value: i32) {
    if value < 0 {
        out.push(b'-');
        push_u32_dec(out, (-value) as u32);
    } else {
        push_u32_dec(out, value as u32);
    }
}

fn append_field(out: &mut Vec<u8>, key: &[u8], value: &[u8]) {
    out.extend_from_slice(key);
    out.extend_from_slice(value);
    out.push(b'\n');
}

fn append_field_u32(out: &mut Vec<u8>, key: &[u8], value: u32) {
    out.extend_from_slice(key);
    push_u32_dec(out, value);
    out.push(b'\n');
}

fn append_field_u64(out: &mut Vec<u8>, key: &[u8], mut value: u64) {
    out.extend_from_slice(key);
    let mut tmp = [0u8; 20];
    let mut i = tmp.len();
    if value == 0 {
        out.push(b'0');
        out.push(b'\n');
        return;
    }
    while value != 0 && i != 0 {
        i -= 1;
        tmp[i] = b'0' + (value % 10) as u8;
        value /= 10;
    }
    out.extend_from_slice(&tmp[i..]);
    out.push(b'\n');
}

fn append_field_i32(out: &mut Vec<u8>, key: &[u8], value: i32) {
    out.extend_from_slice(key);
    push_i32_dec(out, value);
    out.push(b'\n');
}

fn write_minidump_artifact(pid: u32, code: i32, name: &str, build_id: &str) -> Option<String> {
    let ts = nsec().ok().unwrap_or(0);
    let path = normalize_dump_path(ts, pid, name).ok()?;
    let frame = MinidumpFrame {
        timestamp_nsec: ts,
        pid,
        code,
        name: String::from(name),
        build_id: String::from(build_id),
        pcs: Vec::new(),
        stack_preview: Vec::new(),
        code_preview: Vec::new(),
    };
    let bytes = frame.encode().ok()?;
    if write_dump_to_statefs(path.as_str(), &bytes).is_err() {
        return None;
    }
    emit_minidump_written(path.as_str());
    Some(path)
}

fn emit_minidump_written(path: &str) {
    emit_line_no_nl("execd: minidump written ");
    for b in path.as_bytes().iter().copied() {
        let _ = debug_putc(b);
    }
    let _ = debug_putc(b'\n');
}

#[must_use]
fn verify_reported_minidump(
    path: &str,
    pid: u32,
    code: i32,
    name: &str,
    build_id: &str,
    dump_bytes: &[u8],
) -> bool {
    if validate_dump_path(path).is_err() {
        return false;
    }
    if !crate::reported_minidump_path_matches_name(path, name) {
        return false;
    }
    let expected_build_id = deterministic_build_id(name);
    if expected_build_id.as_str() != build_id {
        return false;
    }
    let frame = match MinidumpFrame::decode(dump_bytes) {
        Ok(v) => v,
        Err(_) => return false,
    };
    if !crate::reported_minidump_frame_matches_expected(
        crate::MinidumpFrameMetadata {
            pid: frame.pid,
            code: frame.code,
            name: frame.name.as_str(),
            build_id: frame.build_id.as_str(),
        },
        crate::MinidumpFrameMetadata { pid, code, name, build_id },
    ) {
        return false;
    }
    frame.validate().is_ok()
}

fn handle_frame(state: &mut State, sender_service_id: u64, frame: &[u8]) -> Vec<u8> {
    // Request v1: [E, X, ver, op, image_id, stack_pages:u8, requester_len:u8, requester...]
    // Response:   [E, X, ver, op|0x80, status, pid:u32le]
    if frame.len() < 4 || frame[0] != MAGIC0 || frame[1] != MAGIC1 {
        return rsp(OP_EXEC_IMAGE, STATUS_MALFORMED, 0).to_vec();
    }
    if frame[2] != VERSION {
        return rsp(frame[3], STATUS_UNSUPPORTED, 0).to_vec();
    }
    let op = frame[3];
    if op == OP_WAIT_PID {
        // Wait v1: [E,X,ver,OP_WAIT_PID, pid:u32le]
        // Rsp: [E,X,ver,OP_WAIT_PID|0x80, status:u8, pid:u32le, code:i32le]
        if frame.len() != 8 {
            return rsp(op, STATUS_MALFORMED, 0).to_vec();
        }
        let pid = u32::from_le_bytes([frame[4], frame[5], frame[6], frame[7]]) as i32;
        return match wait(pid) {
            Ok((got, code)) => {
                let got_u32 = got as u32;
                if code != 0 {
                    let image_id =
                        state.children.iter().find(|c| c.pid == got_u32).map(|c| c.image_id);
                    let name = image_id.map(State::child_name).unwrap_or("unknown");
                    // For minidump-managed payloads, crash publication is deferred to OP_REPORT_EXIT
                    // so dump metadata can be validated before emitting success markers.
                    if name != "demo.minidump" {
                        let build_id = deterministic_build_id(name);
                        let dump_path = write_minidump_artifact(got_u32, code, name, &build_id);
                        emit_crash_marker(got_u32, code, name);
                        state.log_crash_via_nexus_log(
                            got_u32,
                            code,
                            name,
                            &build_id,
                            dump_path.as_deref(),
                        );
                    }
                }
                let mut out = Vec::with_capacity(13);
                out.extend_from_slice(&[MAGIC0, MAGIC1, VERSION, OP_WAIT_PID | 0x80, STATUS_OK]);
                out.extend_from_slice(&(got as u32).to_le_bytes());
                out.extend_from_slice(&code.to_le_bytes());
                out
            }
            Err(_) => {
                let mut out = Vec::with_capacity(13);
                out.extend_from_slice(&[
                    MAGIC0,
                    MAGIC1,
                    VERSION,
                    OP_WAIT_PID | 0x80,
                    STATUS_FAILED,
                ]);
                out.extend_from_slice(&(pid as u32).to_le_bytes());
                out.extend_from_slice(&(-1i32).to_le_bytes());
                out
            }
        };
    }
    if op == OP_REPORT_EXIT {
        // Report v1: [E,X,ver,OP, pid:u32le, code:i32le]
        // Report v2: [E,X,ver,OP, pid:u32le, code:i32le, build_len:u8, path_len:u16le,
        //             dump_len:u16le, build, path, dump]
        if frame.len() < 4 + 4 + 4 {
            return rsp(op, STATUS_MALFORMED, 0).to_vec();
        }
        let pid = u32::from_le_bytes([frame[4], frame[5], frame[6], frame[7]]);
        let code = i32::from_le_bytes([frame[8], frame[9], frame[10], frame[11]]);
        let trusted_sender = service_id_from_name(b"selftest-client");
        if !crate::crash_event_publish_allowed(
            sender_service_id,
            trusted_sender,
            SID_SELFTEST_CLIENT_ALT,
        ) {
            return rsp(op, STATUS_DENIED, pid).to_vec();
        }

        let reported_meta = if frame.len() == 12 {
            None
        } else {
            if frame.len() < 17 {
                return rsp(op, STATUS_MALFORMED, pid).to_vec();
            }
            let build_len = frame[12] as usize;
            let path_len = u16::from_le_bytes([frame[13], frame[14]]) as usize;
            let dump_len = u16::from_le_bytes([frame[15], frame[16]]) as usize;
            if build_len == 0
                || build_len > 64
                || path_len == 0
                || path_len > 255
                || dump_len == 0
                || dump_len > 4096
                || frame.len() != 17 + build_len + path_len + dump_len
            {
                return rsp(op, STATUS_MALFORMED, pid).to_vec();
            }
            let build_start = 17;
            let build_end = build_start + build_len;
            let path_start = build_end;
            let path_end = path_start + path_len;
            let dump_start = path_end;
            let dump_end = dump_start + dump_len;
            let build_id = match core::str::from_utf8(&frame[build_start..build_end]) {
                Ok(v) => v,
                Err(_) => return rsp(op, STATUS_MALFORMED, pid).to_vec(),
            };
            let dump_path = match core::str::from_utf8(&frame[path_start..path_end]) {
                Ok(v) => v,
                Err(_) => return rsp(op, STATUS_MALFORMED, pid).to_vec(),
            };
            if validate_dump_path(dump_path).is_err() {
                return rsp(op, STATUS_DENIED, pid).to_vec();
            }
            Some((build_id, dump_path, &frame[dump_start..dump_end]))
        };

        let image_id = state.children.iter().find(|c| c.pid == pid).map(|c| c.image_id);
        if let Some(img) = image_id {
            if code != 0 {
                let name = State::child_name(img);
                let (build_id, dump_path) = if let Some((build_id, dump_path, dump_bytes)) =
                    reported_meta
                {
                    if !verify_reported_minidump(dump_path, pid, code, name, build_id, dump_bytes) {
                        return rsp(op, STATUS_FAILED, pid).to_vec();
                    }
                    emit_minidump_written(dump_path);
                    (String::from(build_id), Some(String::from(dump_path)))
                } else if name == "demo.minidump" {
                    // v1 minidump flow requires explicit metadata handoff for managed payloads.
                    return rsp(op, STATUS_FAILED, pid).to_vec();
                } else {
                    let build_id = deterministic_build_id(name);
                    let dump_path = write_minidump_artifact(pid, code, name, &build_id);
                    (build_id, dump_path)
                };
                emit_crash_marker(pid, code, name);
                state.log_crash_via_nexus_log(
                    pid,
                    code,
                    name,
                    build_id.as_str(),
                    dump_path.as_deref(),
                );
            }
            return rsp(op, STATUS_OK, pid).to_vec();
        }
        return rsp(op, STATUS_FAILED, pid).to_vec();
    }
    if op != OP_EXEC_IMAGE {
        return rsp(op, STATUS_UNSUPPORTED, 0).to_vec();
    }
    if frame.len() < 7 {
        return rsp(op, STATUS_MALFORMED, 0).to_vec();
    }
    let image_id = frame[4];
    let stack_pages = frame[5].max(1) as usize;
    let req_len = frame[6] as usize;
    if req_len == 0 || req_len > 48 || frame.len() < 7 + req_len {
        return rsp(op, STATUS_MALFORMED, 0).to_vec();
    }
    let requester = &frame[7..7 + req_len];
    // Append-only extension (TASK-0080D GET_PAYLOAD): an optional app id
    // (`app_len:u8, app...`) names the ui-program payload to fetch from
    // bundlemgrd for the spawned app-host. Absent = legacy frame.
    let app_id = match frame.len() - (7 + req_len) {
        0 => None,
        n if n >= 2 => {
            let alen = frame[7 + req_len] as usize;
            if alen == 0 || alen > 48 || n != 1 + alen {
                return rsp(op, STATUS_MALFORMED, 0).to_vec();
            }
            Some(&frame[8 + req_len..])
        }
        _ => return rsp(op, STATUS_MALFORMED, 0).to_vec(),
    };

    // Security hardening: bind requester identity to the IPC channel.
    // The requester string is treated as *display* only; the authoritative identity is the
    // kernel-derived sender_service_id returned via ipc_recv_v2 metadata.
    let expected_sender_id = service_id_from_name(requester);
    let sender_matches = expected_sender_id == sender_service_id
        || (requester == b"selftest-client" && sender_service_id == SID_SELFTEST_CLIENT_ALT);
    if !sender_matches {
        metrics_counter_inc_best_effort("execd.spawn.deny");
        emit_line_no_nl("execd: spawn id mismatch sender=");
        emit_u64(sender_service_id);
        emit_line_no_nl(" expected=");
        emit_u64(expected_sender_id);
        emit_line_no_nl(" requester=");
        for b in requester.iter().copied().take(48) {
            let _ = debug_putc(b);
        }
        let _ = debug_putc(b'\n');
        emit_line("execd: spawn denied (id mismatch)");
        return rsp(op, STATUS_DENIED, 0).to_vec();
    }

    // Ask init-lite (control channel) to authorize this exec via policyd.
    let nonce: nexus_abi::policy::Nonce = {
        let n = state.policy_nonce;
        state.policy_nonce = state.policy_nonce.wrapping_add(1);
        if state.policy_nonce == 0 {
            state.policy_nonce = 1;
        }
        n
    };
    let mut q = [0u8; 10 + 48];
    let qn = match nexus_abi::policy::encode_exec_check(nonce, requester, image_id, &mut q) {
        Some(n) => n,
        None => return rsp(op, STATUS_MALFORMED, 0).to_vec(),
    };
    let hdr = nexus_abi::MsgHeader::new(0, 0, 0, 0, qn as u32);
    // Init-lite may be busy answering ROUTE_GET queries (policyd-gated) during early bring-up.
    // Keep send path bounded and deterministic.
    let clock = OsClock;
    let deadline_ns = match deadline_after(&clock, Duration::from_secs(2)) {
        Ok(v) => v,
        Err(_) => return rsp(op, STATUS_FAILED, 0).to_vec(),
    };
    if nexus_ipc::budget::raw::send_budgeted(&clock, 1, &hdr, &q[..qn], deadline_ns).is_err() {
        return rsp(op, STATUS_FAILED, 0).to_vec();
    }
    struct CtlInbox;
    impl nexus_ipc::Client for CtlInbox {
        fn send(&self, _frame: &[u8], _wait: Wait) -> nexus_ipc::Result<()> {
            Err(nexus_ipc::IpcError::Unsupported)
        }

        fn recv(&self, _wait: Wait) -> nexus_ipc::Result<Vec<u8>> {
            let mut rh = nexus_abi::MsgHeader::new(0, 0, 0, 0, 0);
            let mut rb = [0u8; 16];
            match nexus_abi::ipc_recv_v1(
                2,
                &mut rh,
                &mut rb,
                nexus_abi::IPC_SYS_NONBLOCK | nexus_abi::IPC_SYS_TRUNCATE,
                0,
            ) {
                Ok(n) => Ok(rb[..core::cmp::min(n as usize, rb.len())].to_vec()),
                Err(nexus_abi::IpcError::QueueEmpty) => Err(nexus_ipc::IpcError::WouldBlock),
                Err(other) => Err(nexus_ipc::IpcError::Kernel(other)),
            }
        }
    }

    let rb = match recv_match_until(
        &clock,
        &CtlInbox,
        &mut state.pending_policy,
        nonce as u64,
        deadline_ns,
        |frame| nexus_abi::policy::decode_exec_check_rsp(frame).map(|(n, _)| n as u64),
    ) {
        Ok(v) => v,
        Err(_) => return rsp(op, STATUS_FAILED, 0).to_vec(),
    };
    let decision = match crate::decode_exec_policy_decision(&rb, nonce) {
        Some(v) => v,
        None => {
            metrics_counter_inc_best_effort("execd.spawn.deny");
            emit_line("execd: spawn denied (policy malformed)");
            return rsp(op, STATUS_DENIED, 0).to_vec();
        }
    };
    if decision != nexus_abi::policy::STATUS_ALLOW {
        metrics_counter_inc_best_effort("execd.spawn.deny");
        emit_line("execd: spawn denied (policy)");
        return rsp(op, STATUS_DENIED, 0).to_vec();
    }
    if !crate::spawn_caps_respect_vfs_boundary(&RUNTIME_APP_CAPS) {
        metrics_counter_inc_best_effort("execd.spawn.deny");
        emit_line("execd: spawn denied (fs cap boundary)");
        return rsp(op, STATUS_DENIED, 0).to_vec();
    }

    let elf = match image_id {
        IMG_HELLO => HELLO_ELF,
        IMG_EXIT0 => DEMO_EXIT0_ELF,
        IMG_EXIT42 => DEMO_MINIDUMP_ELF,
        IMG_APPHOST if !apphost_payload::APPHOST_ELF.is_empty() => apphost_payload::APPHOST_ELF,
        _ => return rsp(op, STATUS_UNSUPPORTED, 0).to_vec(),
    };
    // GET_PAYLOAD (TASK-0080D): kick the payload fetch BEFORE the ELF load so
    // bundlemgrd fills the VMO while we spawn; the child polls the VMO header,
    // so no wait is needed here. `None` = the child falls back to its embedded
    // payload (fail-closed, visibly marked on both sides).
    let payload_vmo = match (image_id, app_id) {
        (IMG_APPHOST, Some(app)) => fetch_app_payload(app),
        _ => None,
    };
    let start_ns = nsec().ok().unwrap_or(0);
    let local = EXEC_SPAN_LOCAL.fetch_add(1, Ordering::Relaxed);
    let span_id = SpanId(((sender_service_id & 0xffff_ffff) << 32) | (local & 0xffff_ffff));
    let mut ids = DeterministicIdSource::new(sender_service_id);
    let trace_id = ids.next_trace_id();
    metrics_span_start_best_effort(span_id, trace_id, "execd.exec", b"svc=execd\n");
    match exec(elf, stack_pages, 0) {
        Ok(pid) => {
            state.track_child(pid as u32, image_id);
            if image_id == IMG_APPHOST {
                grant_windowd_route(pid as u32);
                if let Some(vmo) = payload_vmo {
                    grant_payload_vmo(pid as u32, vmo);
                }
                // Dedicated event channel: attach windowd's SEND half FIRST
                // (same request queue the child's SURFACE_CREATE uses, so
                // windowd holds the channel before the create), then hand
                // the RECV half to the child — all before resume.
                grant_event_channel(pid as u32);
                // TASK-0080C: provision the app's DECLARED service routes
                // (@reply inbox + one SEND per routable manifest cap) into the
                // child's fixed SDK slots — cap-gated, before resume.
                if let Some(app) = app_id {
                    provision_app_service_routes(pid as u32, app);
                }
            }
            // #102 ROOT CAUSE FIX: `spawn_inner` starts EVERY task Suspended
            // (the grants-before-resume hardening); nexus-init resumes its
            // services explicitly after cap wiring — execd never did, so its
            // children loaded but never executed. Resume AFTER the grants
            // above (same grants-before-resume discipline).
            if nexus_abi::task_resume(pid as u32).is_err() {
                emit_line("execd: FAIL child resume");
            }
            metrics_counter_inc_best_effort("execd.spawn.ok");
            let end_ns = nsec().ok().unwrap_or(start_ns);
            metrics_span_end_best_effort(span_id, end_ns, 0, b"result=ok\n");
            rsp(op, STATUS_OK, pid as u32).to_vec()
        }
        Err(_) => {
            if let Some(vmo) = payload_vmo {
                let _ = nexus_abi::cap_close(vmo);
            }
            metrics_counter_inc_best_effort("execd.spawn.fail");
            let end_ns = nsec().ok().unwrap_or(start_ns);
            metrics_span_end_best_effort(span_id, end_ns, 1, b"result=fail\n");
            rsp(op, STATUS_FAILED, 0).to_vec()
        }
    }
}

/// GET_PAYLOAD (TASK-0080D): creates the payload VMO and asks bundlemgrd to
/// fill it (request + CAP_MOVE of a VMO clone — the message's single cap slot
/// carries the VMO, so bundlemgrd's reply is the header IT writes into the
/// VMO, header-last). Fire-and-forget: the child polls the header with its
/// own budget. Returns the ORIGINAL VMO cap (destined for child slot 7), or
/// `None` on any failure (marked; the child falls back to its embed).
fn fetch_app_payload(app_id: &[u8]) -> Option<u32> {
    let vmo = match nexus_abi::vmo_create(PAYLOAD_VMO_BYTES) {
        Ok(v) => v,
        Err(_) => {
            emit_line("execd: FAIL app payload (vmo create)");
            return None;
        }
    };
    let mut frame = [0u8; 64];
    let Some(len) = nexus_abi::bundlemgrd::encode_get_payload(app_id, &mut frame) else {
        emit_line("execd: FAIL app payload (encode)");
        let _ = nexus_abi::cap_close(vmo);
        return None;
    };
    let clone = match nexus_abi::cap_clone(vmo) {
        Ok(c) => c,
        Err(_) => {
            emit_line("execd: FAIL app payload (cap clone)");
            let _ = nexus_abi::cap_close(vmo);
            return None;
        }
    };
    let hdr = nexus_abi::MsgHeader::new(
        clone,
        0,
        0,
        nexus_abi::ipc_hdr::CAP_MOVE,
        len as u32,
    );
    // Bounded non-blocking send (bundlemgrd may be busy; never stall execd).
    let deadline = nsec().ok().unwrap_or(0).saturating_add(2_000_000_000);
    loop {
        match nexus_abi::ipc_send_v1(
            BUNDLE_SEND_SLOT,
            &hdr,
            &frame[..len],
            nexus_abi::IPC_SYS_NONBLOCK,
            0,
        ) {
            Ok(_) => {
                emit_line("execd: app payload requested");
                return Some(vmo);
            }
            Err(nexus_abi::IpcError::QueueFull) => {
                if nsec().ok().unwrap_or(u64::MAX) >= deadline {
                    emit_line("execd: FAIL app payload (send timeout)");
                    let _ = nexus_abi::cap_close(clone);
                    let _ = nexus_abi::cap_close(vmo);
                    return None;
                }
                let _ = yield_();
            }
            Err(_) => {
                emit_line("execd: FAIL app payload (send)");
                let _ = nexus_abi::cap_close(clone);
                let _ = nexus_abi::cap_close(vmo);
                return None;
            }
        }
    }
}

// The execd-side attach is DELETED: the child attaches its OWN channel to
// windowd, nonce-tagged (deterministic channel↔surface binding — the execd
// attach carried no identity and crossed under concurrent launches).

/// Diagnostic (only on probe grant failure): probe execd's cap slots 4..24
/// via cap_clone+cap_close (cap_query answers only Vmo/DeviceMmio) and print
/// one compact line naming the occupied slots — a slot-order drift between
/// nexus-init's transfer order and the PROBE_*_SLOT convention names itself.
fn probe_dump_cap_slots() {
    let mut line = [0u8; 96];
    let prefix = b"execd: probe slots present:";
    let mut p = 0usize;
    for &b in prefix {
        line[p] = b;
        p += 1;
    }
    for slot in 4u32..24 {
        if let Ok(clone) = nexus_abi::cap_clone(slot) {
            let _ = nexus_abi::cap_close(clone);
            if p + 4 < line.len() {
                line[p] = b' ';
                p += 1;
                if slot >= 10 {
                    line[p] = b'0' + (slot / 10) as u8;
                    p += 1;
                }
                line[p] = b'0' + (slot % 10) as u8;
                p += 1;
            }
        }
    }
    if p < line.len() {
        line[p] = b'\n';
        p += 1;
    }
    let _ = nexus_abi::debug_write(&line[..p]);
}

/// P0.2 recv-wake regression gate: spawn the probe child, let it PARK in a
/// plain blocking ipc recv, then send it one message — the child must wake
/// and reply. Runs ONCE after `ready`, bounded (~2s worst case, ~50ms
/// healthy), headless, no user interaction. This is the deterministic
/// reproducer for the #102-family finding (proof boot 2026-07-07T12-12-27:
/// exec'd children parked in blocking recv were never woken by senders;
/// messages sat in their queue until a NonBlocking poll). Verdict markers:
/// `SELFTEST: exec child blocking recv wake ok` on success, a
/// `execd: FAIL recv-wake probe (…)` naming the failing hop otherwise.
fn run_recv_wake_probe() {
    if recvwake_payload::RECVWAKE_ELF.is_empty() {
        emit_line("execd: recv-wake probe skipped (no elf)");
        return;
    }
    // #123 empty-slot lesson: execd RESUMES before nexus-init's wiring arm
    // finishes its cap transfers (proven: the first probe run found slots
    // 4..24 ALL empty at 0.124s while `init: settingsd slots` printed later).
    // Wait bounded for the LAST probe transfer (reply RECV @16 — transfer
    // order ping S/R, reply S/R means 16 present ⇒ all four present).
    let wired_deadline = nsec().ok().unwrap_or(0).saturating_add(5_000_000_000);
    loop {
        if let Ok(clone) = nexus_abi::cap_clone(PROBE_REPLY_RECV_SLOT) {
            let _ = nexus_abi::cap_close(clone);
            break;
        }
        if nsec().ok().unwrap_or(u64::MAX) >= wired_deadline {
            emit_line("execd: FAIL recv-wake probe (slots not wired)");
            probe_dump_cap_slots();
            return;
        }
        let _ = yield_();
    }
    let pid = match exec(recvwake_payload::RECVWAKE_ELF, 16, 0) {
        Ok(pid) => pid as u32,
        Err(_) => {
            emit_line("execd: FAIL recv-wake probe (spawn)");
            return;
        }
    };
    // Grants BEFORE resume (#102 discipline): ping RECV → child slot 5,
    // reply SEND → child slot 6. Each hop fails LOUD with its own marker;
    // a clone failure additionally dumps which execd slots actually hold
    // clonable caps (cap_clone+close probe — cap_query answers only
    // Vmo/DeviceMmio), so a slot-order drift names itself in the log.
    let ping_clone = nexus_abi::cap_clone(PROBE_PING_RECV_SLOT);
    let reply_clone = nexus_abi::cap_clone(PROBE_REPLY_SEND_SLOT);
    if ping_clone.is_err() || reply_clone.is_err() {
        emit_line("execd: FAIL recv-wake probe (grant clone)");
        probe_dump_cap_slots();
        return;
    }
    let ping_ok = ping_clone
        .and_then(|clone| {
            nexus_abi::cap_transfer_to_slot(
                pid as nexus_abi::Pid,
                clone,
                nexus_abi::Rights::RECV,
                PROBE_CHILD_PING_RECV_SLOT,
            )
            .map_err(|_| nexus_abi::AbiError::Unsupported)
        })
        .is_ok();
    let reply_ok = reply_clone
        .and_then(|clone| {
            nexus_abi::cap_transfer_to_slot(
                pid as nexus_abi::Pid,
                clone,
                nexus_abi::Rights::SEND,
                PROBE_CHILD_REPLY_SEND_SLOT,
            )
            .map_err(|_| nexus_abi::AbiError::Unsupported)
        })
        .is_ok();
    if !ping_ok || !reply_ok {
        emit_line(if !ping_ok {
            "execd: FAIL recv-wake probe (grant ping xfer)"
        } else {
            "execd: FAIL recv-wake probe (grant reply xfer)"
        });
        return;
    }
    if nexus_abi::task_resume(pid).is_err() {
        emit_line("execd: FAIL recv-wake probe (resume)");
        return;
    }
    // 1. Wait for the child's ARMED byte (bounded 2s).
    let mut hdr = nexus_abi::MsgHeader::new(0, 0, 0, 0, 0);
    let mut buf = [0u8; 16];
    let deadline = nsec().ok().unwrap_or(0).saturating_add(2_000_000_000);
    match nexus_abi::ipc_recv_v1(
        PROBE_REPLY_RECV_SLOT,
        &mut hdr,
        &mut buf,
        nexus_abi::IPC_SYS_TRUNCATE,
        deadline,
    ) {
        Ok(n) if n >= 1 && buf[0] == PROBE_MSG_ARMED => {}
        Ok(_) => {
            emit_line("execd: FAIL recv-wake probe (protocol armed)");
            return;
        }
        Err(_) => {
            emit_line("execd: FAIL recv-wake probe (armed timeout)");
            return;
        }
    }
    // 2. TWO park/wake cycles (the counter repro proved wake 1 can succeed
    //    while the SECOND park is never woken again — wake-then-lost class;
    //    a single-cycle gate is half a gate). Per cycle: bounded park window
    //    (timed recv EXPECTED to time out), one ping to the parked child,
    //    bounded wait for its woke-reply.
    for cycle in 0..2u32 {
        let park_deadline = nsec().ok().unwrap_or(0).saturating_add(30_000_000);
        match nexus_abi::ipc_recv_v1(
            PROBE_REPLY_RECV_SLOT,
            &mut hdr,
            &mut buf,
            nexus_abi::IPC_SYS_TRUNCATE,
            park_deadline,
        ) {
            Ok(_) => {
                emit_line("execd: FAIL recv-wake probe (early reply)");
                return;
            }
            Err(_) => {}
        }
        let ping = [0xB1u8];
        let ping_hdr = nexus_abi::MsgHeader::new(0, 0, 0, 0, ping.len() as u32);
        let send_deadline = nsec().ok().unwrap_or(0).saturating_add(1_000_000_000);
        loop {
            match nexus_abi::ipc_send_v1(
                PROBE_PING_SEND_SLOT,
                &ping_hdr,
                &ping,
                nexus_abi::IPC_SYS_NONBLOCK,
                0,
            ) {
                Ok(_) => break,
                Err(nexus_abi::IpcError::QueueFull) => {
                    if nsec().ok().unwrap_or(u64::MAX) >= send_deadline {
                        emit_line("execd: FAIL recv-wake probe (ping send timeout)");
                        return;
                    }
                    let _ = yield_();
                }
                Err(_) => {
                    emit_line("execd: FAIL recv-wake probe (ping send)");
                    return;
                }
            }
        }
        let woke_deadline = nsec().ok().unwrap_or(0).saturating_add(2_000_000_000);
        match nexus_abi::ipc_recv_v1(
            PROBE_REPLY_RECV_SLOT,
            &mut hdr,
            &mut buf,
            nexus_abi::IPC_SYS_TRUNCATE,
            woke_deadline,
        ) {
            Ok(n) if n >= 1 && buf[0] == PROBE_MSG_WOKE => {}
            Ok(_) => {
                emit_line("execd: FAIL recv-wake probe (protocol woke)");
                return;
            }
            Err(_) => {
                emit_line(if cycle == 0 {
                    "execd: FAIL recv-wake probe (child never woke from blocking recv)"
                } else {
                    "execd: FAIL recv-wake probe (child never woke AGAIN — second park lost)"
                });
                return;
            }
        }
    }
    emit_line("execd: recv-wake probe ok");
    let _ = nexus_abi::debug_println("SELFTEST: exec child blocking recv wake ok");
}

/// Hands the child its RECV half of the dedicated event channel
/// (`CHILD_EVENTS_SLOT`).
fn grant_event_channel(child_pid: u32) {
    // Mint a fresh PRIVATE pair via init's ctrl plane (`@mint-pair`); the
    // child gets BOTH halves: RECV→slot 8 (its event inbox) and a SEND clone→
    // slot 14 — the child attaches that to windowd ITSELF, tagged with its
    // nonce (deterministic channel↔surface binding). execd closes its own
    // halves after the grants: mint→grant→close, zero accumulation.
    let Some((send_slot, recv_slot)) = route_ctrl(b"@mint-pair") else {
        let _ = nexus_abi::debug_println("execd: FAIL app event channel mint");
        return;
    };
    let recv_ok = nexus_abi::cap_clone(recv_slot)
        .and_then(|clone| {
            nexus_abi::cap_transfer_to_slot(
                child_pid as nexus_abi::Pid,
                clone,
                nexus_abi::Rights::RECV,
                CHILD_EVENTS_SLOT,
            )
            .map_err(|_| nexus_abi::AbiError::Unsupported)
        })
        .is_ok();
    let send_ok = nexus_abi::cap_clone(send_slot)
        .and_then(|clone| {
            nexus_abi::cap_transfer_to_slot(
                child_pid as nexus_abi::Pid,
                clone,
                nexus_abi::Rights::SEND,
                CHILD_EVENTS_SEND_SLOT,
            )
            .map_err(|_| nexus_abi::AbiError::Unsupported)
        })
        .is_ok();
    // Close execd's own halves (the child holds the live ones).
    let _ = nexus_abi::cap_close(send_slot);
    let _ = nexus_abi::cap_close(recv_slot);
    if recv_ok && send_ok {
        let _ = nexus_abi::debug_println("execd: app event channel granted (minted)");
    } else {
        let _ = nexus_abi::debug_println("execd: FAIL app event channel grant (minted)");
    }
}

/// Moves the payload VMO into the child's fixed payload slot
/// (`CHILD_PAYLOAD_SLOT`, Rights::MAP — `vmo_read` is all the child needs).
fn grant_payload_vmo(child_pid: u32, vmo: u32) {
    match nexus_abi::cap_transfer_to_slot(
        child_pid as nexus_abi::Pid,
        vmo,
        nexus_abi::Rights::MAP,
        CHILD_PAYLOAD_SLOT,
    ) {
        Ok(_) => {
            let _ = nexus_abi::debug_println("execd: app payload granted");
        }
        Err(_) => {
            let _ = nexus_abi::debug_println("execd: FAIL app payload grant");
            let _ = nexus_abi::cap_close(vmo);
        }
    }
}

fn rsp(op: u8, status: u8, pid: u32) -> [u8; 9] {
    let mut out = [0u8; 9];
    out[0] = MAGIC0;
    out[1] = MAGIC1;
    out[2] = VERSION;
    out[3] = op | 0x80;
    out[4] = status;
    out[5..9].copy_from_slice(&pid.to_le_bytes());
    out
}

/// ADR-0042: hands the spawned app process its windowd client route —
/// clones of execd's own granted caps, placed into the child's FIXED slots
/// (the app-host constants). The child retries its first sends bounded, so
/// the transfer landing moments after resume is safe (#123 lesson).
fn grant_windowd_route(child_pid: u32) {
    let send = nexus_abi::cap_clone(APP_WINDOWD_SEND_SLOT)
        .and_then(|clone| {
            nexus_abi::cap_transfer_to_slot(
                child_pid as nexus_abi::Pid,
                clone,
                nexus_abi::Rights::SEND,
                CHILD_WINDOWD_SEND_SLOT,
            )
            .map_err(|_| nexus_abi::AbiError::Unsupported)
        })
        .is_ok();
    let recv = nexus_abi::cap_clone(APP_WINDOWD_RECV_SLOT)
        .and_then(|clone| {
            nexus_abi::cap_transfer_to_slot(
                child_pid as nexus_abi::Pid,
                clone,
                nexus_abi::Rights::RECV,
                CHILD_WINDOWD_RECV_SLOT,
            )
            .map_err(|_| nexus_abi::AbiError::Unsupported)
        })
        .is_ok();
    if send && recv {
        let _ = nexus_abi::debug_println("execd: apphost windowd route granted");
    } else {
        // Values, not guesses: the probe's send retries will exhaust next.
        let _ = nexus_abi::debug_println("execd: FAIL apphost windowd route grant");
    }
}

/// The caps a spawned app's manifest declares (generated table), or `&[]` if
/// the app has no manifest entry — the fail-closed set execd provisions routes
/// for (a cap not declared here is never wired, even if the SDK maps it).
fn caps_for(app_id: &str) -> &'static [&'static str] {
    app_caps::APP_MANIFEST_CAPS
        .iter()
        .find(|(id, _)| *id == app_id)
        .map(|(_, caps)| *caps)
        .unwrap_or(&[])
}

/// Resolves a service (or `@reply`) name to its `(send, recv)` slots via
/// execd's init control channel (slots 1/2) — the same responder bahn
/// windowd/abilitymgr route through. `None` on any routing failure (policyd
/// deny, timeout, exhausted nonce budget); the caller then skips that route.
fn route_ctrl(name: &[u8]) -> Option<(u32, u32)> {
    use nexus_ipc::budget::{self, NonceMismatchBudget, RouteRetryOutcome};
    match budget::route_with_nonce_budgeted(
        name,
        1,
        2,
        Duration::from_secs(2),
        NonceMismatchBudget::new(64),
    ) {
        RouteRetryOutcome::Success { send_slot, recv_slot } => Some((send_slot, recv_slot)),
        _ => None,
    }
}

/// Clones `src_slot` and transfers the clone into the child's `child_slot`
/// with `rights`; returns whether the grant landed.
fn grant_clone(child_pid: u32, src_slot: u32, rights: nexus_abi::Rights, child_slot: u32) -> bool {
    nexus_abi::cap_clone(src_slot)
        .and_then(|clone| {
            nexus_abi::cap_transfer_to_slot(child_pid as nexus_abi::Pid, clone, rights, child_slot)
                .map_err(|_| nexus_abi::AbiError::Unsupported)
        })
        .is_ok()
}

/// TASK-0080C declarative routing: provisions the spawned app-host child's
/// service routes from its manifest caps. For every declared cap that
/// `nexus-sdk-routes` maps to a backing OS service, execd resolves the route
/// via its control channel and grants a SEND clone into the child's FIXED SDK
/// slot (`ServiceRoute::child_slot`). It also resolves a FRESH `@reply` inbox
/// for the child (RECV → slot 9, SEND → slot 10) so the child can move a reply
/// cap per request without sharing execd's own inbox. Cap-gated + fail-soft:
/// an app with no routable cap is a no-op; an unresolvable route is skipped
/// with a marker and the child presence-probes the empty slot.
fn provision_app_service_routes(child_pid: u32, app_id: &[u8]) {
    let Ok(app) = core::str::from_utf8(app_id) else {
        return;
    };
    let caps = caps_for(app);
    if !caps
        .iter()
        .any(|c| nexus_sdk_routes::route_for_permission(c).is_some())
    {
        // No system-service cap ⇒ nothing to route (the common app case).
        return;
    }

    // Fresh per-launch PRIVATE reply inbox: init mints a new pair
    // (`@mint-pair`); both halves go to the child (it clones the SEND per
    // request; service replies land on the RECV half). NEVER `@reply` here —
    // that returns execd's own PERSISTENT shared inbox: granting it put every
    // child on ONE reply queue (cross-process reply theft), and closing it
    // after the grant destroyed execd's inbox slots, so launch 2+ logged
    // `FAIL app reply inbox grant` (boot-proven 2026-07-10).
    match route_ctrl(b"@mint-pair") {
        Some((send_slot, recv_slot)) => {
            let ok_recv = grant_clone(
                child_pid,
                recv_slot,
                nexus_abi::Rights::RECV,
                nexus_sdk_routes::CHILD_REPLY_RECV_SLOT,
            );
            let ok_send = grant_clone(
                child_pid,
                send_slot,
                nexus_abi::Rights::SEND,
                nexus_sdk_routes::CHILD_REPLY_SEND_SLOT,
            );
            if ok_recv && ok_send {
                let _ = nexus_abi::debug_println("execd: app reply inbox granted (minted)");
            } else {
                let _ = nexus_abi::debug_println("execd: FAIL app reply inbox grant");
            }
            // Close execd's own halves of the MINTED pair post-grant — the
            // child holds the only live references (mint→grant→close, zero
            // cap-table accumulation).
            let _ = nexus_abi::cap_close(send_slot);
            let _ = nexus_abi::cap_close(recv_slot);
        }
        None => {
            let _ = nexus_abi::debug_println("execd: FAIL app reply inbox mint");
        }
    }

    // One SEND route per declared + routable cap → its fixed child SDK slot.
    for cap in caps {
        let Some(route) = nexus_sdk_routes::route_for_permission(cap) else {
            continue;
        };
        match route_ctrl(route.route.as_bytes()) {
            Some((send_slot, _recv_slot)) => {
                let ok = grant_clone(
                    child_pid,
                    send_slot,
                    nexus_abi::Rights::SEND,
                    route.child_slot,
                );
                // Do NOT close these slots: named routes resolve to execd's
                // PERSISTENT route-table slots (recorded once at wiring) — the
                // responder answers every later resolve with the SAME slot
                // numbers. Closing them poisoned the table: launch 2+ cloned
                // empty (or worse, REUSED) slots. Resolving mints nothing, so
                // there is nothing to free.
                emit_line_no_nl(if ok {
                    "execd: app route granted svc="
                } else {
                    "execd: FAIL app route grant svc="
                });
                emit_line_no_nl(route.svc);
                let _ = debug_putc(b'\n');
            }
            None => {
                emit_line_no_nl("execd: FAIL app route resolve svc=");
                emit_line_no_nl(route.svc);
                let _ = debug_putc(b'\n');
            }
        }
    }
}

/// Stubbed bundle exec helper exposed for API compatibility.
pub fn exec_elf(
    _bundle: &str,
    _argv: &[&str],
    _env: &[&str],
    _restart: RestartPolicy,
) -> Result<Pid, ExecError> {
    Err(ExecError::Unsupported)
}

fn emit_line(message: &str) {
    // Verdict folding: pre-`ready` markers tally into `execd N/N`; post-`ready` runtime lines fold
    // into recall-only detail (`NEXUS_LOG_EXPAND=execd`). Failures & proof boots print live & raw.
    if nexus_abi::service_line(message.as_bytes()) {
        return;
    }
    for byte in message.as_bytes().iter().copied().chain(core::iter::once(b'\n')) {
        let _ = debug_putc(byte);
    }
}

fn emit_crash_marker(pid: u32, code: i32, name: &str) {
    emit_line_no_nl("execd: crash report pid=");
    emit_u64(pid as u64);
    emit_line_no_nl(" code=");
    emit_i64(code as i64);
    emit_line_no_nl(" name=");
    for b in name.as_bytes() {
        let _ = debug_putc(*b);
    }
    let _ = debug_putc(b'\n');
}

fn emit_line_no_nl(message: &str) {
    for byte in message.as_bytes().iter().copied() {
        let _ = debug_putc(byte);
    }
}

fn metrics_counter_inc_best_effort(name: &str) {
    let Ok(metrics) = MetricsClient::new() else {
        return;
    };
    let _ = metrics.counter_inc(name, b"svc=execd\n", 1);
}

fn metrics_span_start_best_effort(
    span_id: SpanId,
    trace_id: nexus_metrics::TraceId,
    name: &str,
    attrs: &[u8],
) {
    let Ok(metrics) = MetricsClient::new() else {
        return;
    };
    let _ = metrics.span_start(span_id, trace_id, SpanId(0), nsec().ok().unwrap_or(0), name, attrs);
}

fn metrics_span_end_best_effort(span_id: SpanId, end_ns: u64, status: u8, attrs: &[u8]) {
    let Ok(metrics) = MetricsClient::new() else {
        return;
    };
    let _ = metrics.span_end(span_id, end_ns, status, attrs);
}

fn emit_u64(mut value: u64) {
    let mut buf = [0u8; 20];
    let mut idx = buf.len();
    if value == 0 {
        idx -= 1;
        buf[idx] = b'0';
    } else {
        while value != 0 {
            idx -= 1;
            buf[idx] = b'0' + (value % 10) as u8;
            value /= 10;
        }
    }
    for &b in &buf[idx..] {
        let _ = debug_putc(b);
    }
}

fn emit_i64(value: i64) {
    if value < 0 {
        let _ = debug_putc(b'-');
        emit_u64((-value) as u64);
    } else {
        emit_u64(value as u64);
    }
}

// (helpers removed; crash record is emitted through nexus-log sink-logd)
