[package]
name = "nexus_login"
version = "0.1.0"
edition = "2021"

[dependencies]
#nexus = "*"
#redox_users = { version = "0.4", default-features = false }
log = "0.4"
redox-log = "0.1"
orbclient = "0.3"
orbfont = "0.1"
orbimage = "0.1"