[package]
name = "resmgrd"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
resmgr = { path = "../../../userspace/resmgr", default-features = false, features = ["backend-os"] }

