[package]
name = "clipboardd"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
clipboard = { path = "../../../userspace/clipboard", default-features = false, features = ["backend-os"] }

