[package]
name = "bootanim"
version = "0.1.0"
kind = "service"

[source]
type = "path"
path = "../../../source/services/systemui"

[deps]
requires = ["compositor"]

[build]
features = []

[run]
cmd = "systemui --boot-animation"

[tests]
host = true
qemu = ["smoke"]

[policy]
caps = ["graphics.compose"]

[semver]
api_guard = true
