// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0
//
//! CONTEXT: Build-time policy table generator for policyd OS-lite runtime.
//! OWNERS: @runtime @security
//! STATUS: Experimental
//! TEST_COVERAGE: Indirectly covered by policyd host/unit tests and OS build gates.
//! INVARIANTS:
//! - policy file parsing remains bounded and deterministic
//! - generated entries preserve single policy authority source (`policies/*`)
//! - ABI profile defaults remain deny-by-default for subjects without explicit profile rows

// Build scripts are allowed to panic on misconfiguration.
#![allow(clippy::expect_used)]

use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

/// RFC-0091 schema SSOT — the SAME file the host `policy` crate compiles;
/// included by path so policyd's table can never drift from the host grammar.
#[path = "../../../userspace/policy/src/schema.rs"]
#[allow(dead_code)]
mod schema;

use schema::{Action, AddressClass, Profile, Rule};

#[derive(Debug, Default, Deserialize)]
#[serde(deny_unknown_fields)]
struct RawPolicy {
    #[serde(default)]
    allow: BTreeMap<String, Vec<String>>,
    #[serde(default)]
    abi_profile: BTreeMap<String, schema::RawAbiProfile>,
}

#[derive(Debug, Deserialize)]
struct RawPolicyRoot {
    version: u32,
    #[serde(default)]
    include: Vec<String>,
}

fn main() {
    println!("cargo::rustc-check-cfg=cfg(nexus_env, values(\"os\",\"host\"))");
    // RFC-0068: `emit_decision` reads NEXUS_LOG_EXPAND via option_env! — rebuild when it changes
    // so `NEXUS_LOG_EXPAND=policyd` recalls the folded MMIO decision log.
    println!("cargo:rerun-if-env-changed=NEXUS_LOG_EXPAND");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR missing");
    let policy_dir = Path::new(&manifest_dir)
        .join("../../../policies")
        .canonicalize()
        .expect("failed to resolve policies");

    let (policy, abi_profiles) = load_policy_dir(&policy_dir);
    emit_policy_table(&policy, &abi_profiles);
}

fn load_policy_dir(dir: &Path) -> (BTreeMap<String, BTreeSet<String>>, BTreeMap<String, Profile>) {
    let mut files = Vec::new();
    let root_path = dir.join("nexus.policy.toml");
    let root_data =
        fs::read_to_string(&root_path).expect("failed to read policies/nexus.policy.toml");
    let root: RawPolicyRoot =
        toml::from_str(&root_data).expect("failed to parse policies/nexus.policy.toml");
    assert!(root.version == 1, "unsupported policy root version");
    for include in root.include {
        assert!(
            !include.contains("..") && !Path::new(&include).is_absolute(),
            "policy include escapes policies root"
        );
        let path = dir.join(include);
        assert!(
            path.is_file() && path.extension().and_then(|s| s.to_str()) == Some("toml"),
            "policy include is not a TOML file"
        );
        files.push(path);
    }
    files.sort();
    println!("cargo::rerun-if-changed={}", root_path.display());
    println!(
        "cargo::rerun-if-changed={}",
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../../userspace/policy/src/schema.rs")
            .display()
    );
    for file in &files {
        println!("cargo::rerun-if-changed={}", file.display());
    }

    let mut merged: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    let mut abi_profiles: BTreeMap<String, Profile> = BTreeMap::new();
    for path in files {
        let data = fs::read_to_string(&path).expect("failed to read policy file");
        let parsed: RawPolicy =
            toml::from_str(&data).unwrap_or_else(|_| panic!("failed to parse {}", path.display()));
        for (service, caps) in parsed.allow {
            let service_key = canonical(&service);
            let mut set = BTreeSet::new();
            for cap in caps {
                set.insert(canonical(&cap));
            }
            merged.insert(service_key, set);
        }
        for (service, raw_profile) in parsed.abi_profile {
            let profile = schema::compile(&raw_profile).unwrap_or_else(|err| {
                panic!("invalid abi_profile for {service} in {}: {err}", path.display())
            });
            abi_profiles.insert(canonical(&service), profile);
        }
    }
    (merged, abi_profiles)
}

fn emit_policy_table(
    policy: &BTreeMap<String, BTreeSet<String>>,
    abi_profiles: &BTreeMap<String, Profile>,
) {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR missing"));
    let dest = out_dir.join("policy_table.rs");
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by policyd/build.rs. DO NOT EDIT.\n");
    out.push_str("use nexus_sel::PolicyEntry;\n");
    out.push_str("use crate::abi_profile::{AbiProfileEntry, AbiRuleEntry};\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub const POLICY_ENTRIES: &[PolicyEntry] = &[\n");
    for (service, caps) in policy {
        let service_id = service_id_from_name(service.as_bytes());
        out.push_str(&format!(
            "    PolicyEntry {{ service_id: 0x{service_id:016x}u64, capabilities: &["
        ));
        let mut first = true;
        for cap in caps {
            if !first {
                out.push_str(", ");
            }
            first = false;
            out.push('"');
            out.push_str(cap);
            out.push('"');
        }
        out.push_str("] },\n");
    }
    out.push_str("];\n");
    out.push('\n');
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub const ABI_PROFILE_ENTRIES: &[AbiProfileEntry] = &[\n");
    for (service, profile) in abi_profiles {
        let service_id = service_id_from_name(service.as_bytes());
        let limits = match profile.limits {
            Some(l) => format!("Some(({}u32, {}u32))", l.deadline_ms, l.max_payload),
            None => "None".to_string(),
        };
        out.push_str(&format!(
            "    AbiProfileEntry {{ subject_id: 0x{service_id:016x}u64, epoch: {}u32, limits: {limits}, rules: &[\n",
            profile.epoch
        ));
        for rule in &profile.rules {
            out.push_str("        ");
            out.push_str(&rule_literal(rule));
            out.push_str(",\n");
        }
        out.push_str("    ] },\n");
    }
    out.push_str("];\n");
    fs::write(&dest, out).expect("failed to write policy_table.rs");
}

fn action_literal(action: Action) -> u8 {
    match action {
        Action::Deny => 0,
        Action::Allow => 1,
    }
}

fn ports_literal(ports: &[schema::PortRange]) -> String {
    let items: Vec<String> =
        ports.iter().map(|r| format!("({}u16, {}u16)", r.min, r.max)).collect();
    format!("&[{}]", items.join(", "))
}

fn rule_literal(rule: &Rule) -> String {
    match rule {
        Rule::Statefs { action, prefix, max_payload } => format!(
            "AbiRuleEntry::Statefs {{ action: {}, prefix: \"{}\", max_payload: {max_payload}u32 }}",
            action_literal(*action),
            prefix.escape_default()
        ),
        Rule::NetBind { action, address, ports } => format!(
            "AbiRuleEntry::NetBind {{ action: {}, address: {}, ports: {} }}",
            action_literal(*action),
            match address {
                AddressClass::Loopback => 0,
                AddressClass::Any => 1,
            },
            ports_literal(ports)
        ),
        Rule::NetConnect { action, cidr, cidr_len, ports } => format!(
            "AbiRuleEntry::NetConnect {{ action: {}, cidr: [{}, {}, {}, {}], cidr_len: {cidr_len}u8, ports: {} }}",
            action_literal(*action),
            cidr[0],
            cidr[1],
            cidr[2],
            cidr[3],
            ports_literal(ports)
        ),
    }
}

fn canonical(input: &str) -> String {
    input.trim().to_ascii_lowercase()
}

fn service_id_from_name(name: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325u64;
    for &b in name {
        h ^= b as u64;
        h = h.wrapping_mul(0x100000001b3u64);
    }
    h
}
