// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0

//! Import a curated set of **line-based** Lucide icons at build time: parse each
//! SVG's `d` path (M/L/H/V, absolute + relative), stroke every segment into a
//! filled quad, and emit the icon as a multi-contour symbol (normalized `0..1000`
//! viewbox → `ShapeKind::Vector`). Curve commands (C/Q/A) are not flattened yet,
//! so the curated list is line-only; curve support is a follow-up on the same
//! pipeline. Rendering is via the existing `ShapeKind::Vector` fill — no runtime
//! dependency and no core renderer change.

use std::path::Path;
use std::{env, fs};

/// Lucide icons using only M/L/H/V commands (verified line-based).
const ICONS: &[(&str, &str)] = &[
    ("Menu", "menu"),
    ("Check", "check"),
    ("ArrowRight", "arrow-right"),
    ("ArrowLeft", "arrow-left"),
    ("ArrowUp", "arrow-up"),
    ("ArrowDown", "arrow-down"),
];

const LUCIDE_DIR: &str = "../../../../resources/icons/lucide/icons";
/// Lucide viewbox is 24; stroke-width 2 → half-width 1 unit.
const VIEW: f32 = 24.0;
const STROKE_HALF: f32 = 1.0;

fn main() {
    println!("cargo:rerun-if-changed={LUCIDE_DIR}");

    let mut out = String::from("// @generated by build.rs from Lucide SVGs — do not edit.\n\n");
    out.push_str("/// An imported Lucide line symbol.\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub enum LucideSymbol {\n");
    for (variant, _) in ICONS {
        out.push_str(&format!("    {variant},\n"));
    }
    out.push_str("}\n\n");

    for (variant, file) in ICONS {
        let path = format!("{LUCIDE_DIR}/{file}.svg");
        let svg = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("nexus-widget-icon: read {path}: {e}"));
        let mut contours: Vec<[(u16, u16); 4]> = Vec::new();
        for d in extract_d_strings(&svg) {
            for poly in parse_d(&d) {
                for seg in poly.windows(2) {
                    contours.push(stroke_quad(seg[0], seg[1]));
                }
            }
        }
        assert!(!contours.is_empty(), "nexus-widget-icon: {file} produced no contours");
        out.push_str(&format!(
            "const {}: &[&[(u16, u16)]] = &[\n",
            variant.to_uppercase()
        ));
        for q in &contours {
            out.push_str(&format!(
                "    &[({},{}),({},{}),({},{}),({},{})],\n",
                q[0].0, q[0].1, q[1].0, q[1].1, q[2].0, q[2].1, q[3].0, q[3].1
            ));
        }
        out.push_str("];\n\n");
    }

    out.push_str("pub(crate) fn lucide_contours(sym: LucideSymbol) -> &'static [&'static [(u16, u16)]] {\n    match sym {\n");
    for (variant, _) in ICONS {
        out.push_str(&format!("        LucideSymbol::{variant} => {},\n", variant.to_uppercase()));
    }
    out.push_str("    }\n}\n");

    let dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&dir).join("lucide.rs"), out).expect("write lucide.rs");
}

/// Extract every `d="..."` attribute value (path element data).
fn extract_d_strings(svg: &str) -> Vec<String> {
    let mut out = Vec::new();
    let bytes = svg.as_bytes();
    let mut i = 0;
    while let Some(pos) = svg[i..].find("d=\"") {
        let start = i + pos + 3;
        if let Some(end_rel) = svg[start..].find('"') {
            out.push(svg[start..start + end_rel].to_string());
            i = start + end_rel + 1;
        } else {
            break;
        }
        let _ = bytes;
    }
    out
}

/// Parse an M/L/H/V `d` string into polylines (absolute 24-space points).
/// Unknown commands abort that polyline (curve icons are not in the curated set).
fn parse_d(d: &str) -> Vec<Vec<(f32, f32)>> {
    let toks = tokenize(d);
    let mut polys: Vec<Vec<(f32, f32)>> = Vec::new();
    let mut cur: Vec<(f32, f32)> = Vec::new();
    let (mut x, mut y) = (0.0f32, 0.0f32);
    let mut k = 0;
    let mut cmd = ' ';
    while k < toks.len() {
        match &toks[k] {
            Tok::Cmd(c) => {
                cmd = *c;
                k += 1;
                if cmd == 'Z' || cmd == 'z' {
                    if !cur.is_empty() {
                        polys.push(core_take(&mut cur));
                    }
                }
            }
            Tok::Num(_) => {
                let rel = cmd.is_ascii_lowercase();
                match cmd.to_ascii_uppercase() {
                    'M' => {
                        if !cur.is_empty() {
                            polys.push(core_take(&mut cur));
                        }
                        let (nx, ny) = (num(&toks, &mut k), num(&toks, &mut k));
                        x = if rel { x + nx } else { nx };
                        y = if rel { y + ny } else { ny };
                        cur.push((x, y));
                        cmd = if rel { 'l' } else { 'L' }; // implicit lineto
                    }
                    'L' => {
                        let (nx, ny) = (num(&toks, &mut k), num(&toks, &mut k));
                        x = if rel { x + nx } else { nx };
                        y = if rel { y + ny } else { ny };
                        cur.push((x, y));
                    }
                    'H' => {
                        let nx = num(&toks, &mut k);
                        x = if rel { x + nx } else { nx };
                        cur.push((x, y));
                    }
                    'V' => {
                        let ny = num(&toks, &mut k);
                        y = if rel { y + ny } else { ny };
                        cur.push((x, y));
                    }
                    _ => {
                        // Unsupported (curve) — stop this polyline.
                        k += 1;
                    }
                }
            }
        }
    }
    if !cur.is_empty() {
        polys.push(cur);
    }
    polys
}

fn core_take(v: &mut Vec<(f32, f32)>) -> Vec<(f32, f32)> {
    core::mem::take(v)
}

fn num(toks: &[Tok], k: &mut usize) -> f32 {
    while *k < toks.len() {
        if let Tok::Num(n) = toks[*k] {
            *k += 1;
            return n;
        }
        *k += 1;
    }
    0.0
}

enum Tok {
    Cmd(char),
    Num(f32),
}

fn tokenize(d: &str) -> Vec<Tok> {
    let mut toks = Vec::new();
    let chars: Vec<char> = d.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        if c.is_ascii_alphabetic() {
            toks.push(Tok::Cmd(c));
            i += 1;
        } else if c == '-' || c == '+' || c == '.' || c.is_ascii_digit() {
            let start = i;
            if c == '-' || c == '+' {
                i += 1;
            }
            let mut seen_dot = false;
            while i < chars.len() {
                let d = chars[i];
                if d.is_ascii_digit() {
                    i += 1;
                } else if d == '.' && !seen_dot {
                    seen_dot = true;
                    i += 1;
                } else {
                    break;
                }
            }
            let s: String = chars[start..i].iter().collect();
            toks.push(Tok::Num(s.parse().unwrap_or(0.0)));
        } else {
            i += 1; // separator
        }
    }
    toks
}

/// Stroke a segment into a filled quad (normalized `0..1000`, y down).
fn stroke_quad(a: (f32, f32), b: (f32, f32)) -> [(u16, u16); 4] {
    let (dx, dy) = (b.0 - a.0, b.1 - a.1);
    let len = (dx * dx + dy * dy).sqrt().max(0.0001);
    // Perpendicular unit × half stroke width.
    let (px, py) = (-dy / len * STROKE_HALF, dx / len * STROKE_HALF);
    let pts = [
        (a.0 + px, a.1 + py),
        (b.0 + px, b.1 + py),
        (b.0 - px, b.1 - py),
        (a.0 - px, a.1 - py),
    ];
    let mut out = [(0u16, 0u16); 4];
    for (i, &(x, y)) in pts.iter().enumerate() {
        let nx = (x / VIEW * 1000.0).round().clamp(0.0, 1000.0) as u16;
        let ny = (y / VIEW * 1000.0).round().clamp(0.0, 1000.0) as u16;
        out[i] = (nx, ny);
    }
    out
}
