// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0

// Build scripts fail by panicking (unwrap/expect) — the correct failure mode
// for build-time codegen; the restriction lints target runtime code only.
#![allow(clippy::expect_used, clippy::unwrap_used)]

//! Import the theme-linked icon set at build time (`[icons]` in
//! `resources/themes/base.nxtheme.toml`): `path` names the MAINTAINED vendor
//! repo (lucide, ISC — licence-clean), `[icons.symbols]` maps OUR
//! SwiftUI-style symbol names to file stems. Each SVG's stroke geometry
//! (path M/L/H/V/C/S/Q/T/A + circle/rect/line/polyline/polygon elements) is
//! flattened into polylines (normalized `0..1000` viewbox) and emitted with the
//! set's own stroke width; the painter strokes them with round caps and joins,
//! anti-aliased (`ShapeKind::Stroke`, TASK-0251 P2a step 3). The former import
//! cut every segment into its own filled quad — no joins, no caps — which the
//! one-sample fill turned into stair steps with gaps at 17 px.

use std::path::Path;
use std::{env, fs};

/// Lucide viewbox is 24.
const VIEW: f32 = 24.0;
/// Curve flattening steps (per Bézier/arc segment).
const CURVE_STEPS: usize = 12;

const THEMES_DIR: &str = "../../../../resources/themes";

fn main() {
    println!("cargo:rerun-if-changed={THEMES_DIR}");
    // Repo root, relative to this crate (userspace/ui/widgets/icon).
    let repo_root = Path::new("../../../..");

    let runtime = nexus_theme::ThemeRuntime::load(Path::new(THEMES_DIR))
        .unwrap_or_else(|e| panic!("nexus-widget-icon: load themes: {e:?}"));
    let icons_dir = repo_root
        .join(runtime.icons_path().expect("nexus-widget-icon: [icons] path missing in base theme"));
    println!("cargo:rerun-if-changed={}", icons_dir.display());
    let symbols = runtime.icon_symbols();
    assert!(!symbols.is_empty(), "nexus-widget-icon: [icons.symbols] empty");

    let mut out =
        String::from("// @generated by build.rs from the theme-linked icon set — do not edit.\n\n");
    out.push_str("/// An imported vendor symbol (theme `[icons.symbols]` vocabulary).\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub enum LucideSymbol {\n");
    let variants: Vec<(String, &str, &str)> = symbols
        .iter()
        .map(|(name, file)| (variant_ident(name), name.as_str(), file.as_str()))
        .collect();
    for (variant, _, _) in &variants {
        out.push_str(&format!("    {variant},\n"));
    }
    out.push_str("}\n\n");

    // The set's ONE stroke width (every file declares it on its root `<svg>`; a file that
    // differs fails the build rather than painting at the wrong weight).
    let mut stroke_milli: Option<u16> = None;
    for (variant, _, file) in &variants {
        let path = icons_dir.join(format!("{file}.svg"));
        let svg = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("nexus-widget-icon: read {}: {e}", path.display()));
        let width = svg_stroke_width_milli(&svg);
        match stroke_milli {
            None => stroke_milli = Some(width),
            Some(w) => assert_eq!(w, width, "nexus-widget-icon: {file} has another stroke width"),
        }
        let polylines: Vec<Vec<(u16, u16)>> = svg_polylines(&svg)
            .into_iter()
            .map(|poly| {
                let mut pts: Vec<(u16, u16)> = poly.into_iter().map(normalized).collect();
                pts.dedup();
                pts
            })
            .filter(|pts| !pts.is_empty())
            .collect();
        assert!(!polylines.is_empty(), "nexus-widget-icon: {file} produced no polylines");
        out.push_str(&format!("const LUCIDE_{}: &[&[(u16, u16)]] = &[\n", variant.to_uppercase()));
        for pts in &polylines {
            let body: Vec<String> = pts.iter().map(|(x, y)| format!("({x},{y})")).collect();
            out.push_str(&format!("    &[{}],\n", body.join(",")));
        }
        out.push_str("];\n\n");
    }
    let stroke_milli = stroke_milli.expect("nexus-widget-icon: no symbols");
    out.push_str(&format!(
        "/// The set's stroke width in the normalized `0..1000` viewbox.\npub(crate) const LUCIDE_STROKE_MILLI: u16 = {stroke_milli};\n\n"
    ));

    out.push_str("pub(crate) fn lucide_contours(sym: LucideSymbol) -> &'static [&'static [(u16, u16)]] {\n    match sym {\n");
    for (variant, _, _) in &variants {
        out.push_str(&format!(
            "        LucideSymbol::{variant} => LUCIDE_{},\n",
            variant.to_uppercase()
        ));
    }
    out.push_str("    }\n}\n\n");

    // Name lookup: the DSL's `Icon { symbol: \"chevron.left\" }` vocabulary.
    out.push_str("/// Resolve a theme symbol NAME (SwiftUI-style, `[icons.symbols]`).\n");
    out.push_str("#[must_use]\npub fn lucide_symbol_named(name: &str) -> Option<LucideSymbol> {\n    match name {\n");
    for (variant, name, _) in &variants {
        out.push_str(&format!("        \"{name}\" => Some(LucideSymbol::{variant}),\n"));
    }
    out.push_str("        _ => None,\n    }\n}\n");

    let dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&dir).join("lucide.rs"), out).expect("write lucide.rs");
}

/// `chevron.left` → `ChevronLeft`; legacy aliases keep old code compiling
/// (`checkmark` → `Check`, `xmark` → `Close`-free naming stays additive).
fn variant_ident(name: &str) -> String {
    let mut out = String::new();
    for part in name.split(['.', '-', '_']) {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.push(first.to_ascii_uppercase());
            out.push_str(chars.as_str());
        }
    }
    // Legacy variant names used by existing widgets/tests.
    match out.as_str() {
        "Checkmark" => String::from("Check"),
        _ => out,
    }
}

// ── SVG → polylines ─────────────────────────────────────────────────────────

/// Every stroke polyline of the SVG (path data + shape elements), in
/// absolute 24-space coordinates.
fn svg_polylines(svg: &str) -> Vec<Vec<(f32, f32)>> {
    let mut out = Vec::new();
    for d in extract_attr_values(svg, "d") {
        out.extend(parse_d(&d));
    }
    // <circle cx cy r>
    for tag in extract_tags(svg, "circle") {
        let (cx, cy, r) = (attr_f(&tag, "cx"), attr_f(&tag, "cy"), attr_f(&tag, "r"));
        if r > 0.0 {
            out.push(sample_ellipse(cx, cy, r, r));
        }
    }
    // <ellipse cx cy rx ry>
    for tag in extract_tags(svg, "ellipse") {
        let (cx, cy) = (attr_f(&tag, "cx"), attr_f(&tag, "cy"));
        let (rx, ry) = (attr_f(&tag, "rx"), attr_f(&tag, "ry"));
        if rx > 0.0 && ry > 0.0 {
            out.push(sample_ellipse(cx, cy, rx, ry));
        }
    }
    // <line x1 y1 x2 y2>
    for tag in extract_tags(svg, "line") {
        out.push(vec![
            (attr_f(&tag, "x1"), attr_f(&tag, "y1")),
            (attr_f(&tag, "x2"), attr_f(&tag, "y2")),
        ]);
    }
    // <rect x y width height rx?> — stroked as a (rounded-ignored) outline.
    for tag in extract_tags(svg, "rect") {
        let (x, y) = (attr_f(&tag, "x"), attr_f(&tag, "y"));
        let (w, h) = (attr_f(&tag, "width"), attr_f(&tag, "height"));
        if w > 0.0 && h > 0.0 {
            out.push(vec![(x, y), (x + w, y), (x + w, y + h), (x, y + h), (x, y)]);
        }
    }
    // <polyline points> / <polygon points>
    for tag in extract_tags(svg, "polyline").into_iter().chain(extract_tags(svg, "polygon")) {
        if let Some(points) = attr_value(&tag, "points") {
            let nums: Vec<f32> = points
                .split(|c: char| c.is_whitespace() || c == ',')
                .filter(|s| !s.is_empty())
                .filter_map(|s| s.parse().ok())
                .collect();
            let mut poly: Vec<(f32, f32)> = nums.chunks_exact(2).map(|p| (p[0], p[1])).collect();
            if tag.starts_with("polygon") {
                if let Some(&first) = poly.first() {
                    poly.push(first);
                }
            }
            if poly.len() >= 2 {
                out.push(poly);
            }
        }
    }
    out
}

fn extract_attr_values(svg: &str, attr: &str) -> Vec<String> {
    let needle = format!("{attr}=\"");
    let mut out = Vec::new();
    let mut i = 0;
    while let Some(pos) = svg[i..].find(&needle) {
        let start = i + pos + needle.len();
        if let Some(end_rel) = svg[start..].find('"') {
            out.push(svg[start..start + end_rel].to_string());
            i = start + end_rel + 1;
        } else {
            break;
        }
    }
    out
}

/// Every `<name ...>` tag's attribute text.
fn extract_tags(svg: &str, name: &str) -> Vec<String> {
    let needle = format!("<{name}");
    let mut out = Vec::new();
    let mut i = 0;
    while let Some(pos) = svg[i..].find(&needle) {
        let start = i + pos + needle.len();
        if let Some(end_rel) = svg[start..].find('>') {
            out.push(format!("{name}{}", &svg[start..start + end_rel]));
            i = start + end_rel + 1;
        } else {
            break;
        }
    }
    out
}

fn attr_value(tag: &str, attr: &str) -> Option<String> {
    let needle = format!("{attr}=\"");
    let start = tag.find(&needle)? + needle.len();
    let end = tag[start..].find('"')?;
    Some(tag[start..start + end].to_string())
}

fn attr_f(tag: &str, attr: &str) -> f32 {
    attr_value(tag, attr).and_then(|v| v.parse().ok()).unwrap_or(0.0)
}

fn sample_ellipse(cx: f32, cy: f32, rx: f32, ry: f32) -> Vec<(f32, f32)> {
    let steps = 24;
    (0..=steps)
        .map(|i| {
            let t = i as f32 / steps as f32 * core::f32::consts::TAU;
            (cx + rx * t.cos(), cy + ry * t.sin())
        })
        .collect()
}

// ── path `d` parsing with curve/arc flattening ───────────────────────────────

fn parse_d(d: &str) -> Vec<Vec<(f32, f32)>> {
    let toks = tokenize(d);
    let mut polys: Vec<Vec<(f32, f32)>> = Vec::new();
    let mut cur: Vec<(f32, f32)> = Vec::new();
    let (mut x, mut y) = (0.0f32, 0.0f32);
    let (mut start_x, mut start_y) = (0.0f32, 0.0f32);
    // Previous cubic/quadratic control point (for S/T reflection).
    let mut prev_ctrl: Option<(f32, f32)> = None;
    let mut prev_cmd = ' ';
    let mut k = 0;
    let mut cmd = ' ';
    while k < toks.len() {
        match &toks[k] {
            Tok::Cmd(c) => {
                cmd = *c;
                k += 1;
                if cmd == 'Z' || cmd == 'z' {
                    if !cur.is_empty() {
                        cur.push((start_x, start_y));
                        polys.push(std::mem::take(&mut cur));
                        x = start_x;
                        y = start_y;
                    }
                    prev_cmd = 'Z';
                }
            }
            Tok::Num(_) => {
                let rel = cmd.is_ascii_lowercase();
                let up = cmd.to_ascii_uppercase();
                match up {
                    'M' => {
                        if !cur.is_empty() {
                            polys.push(std::mem::take(&mut cur));
                        }
                        let (nx, ny) = (num(&toks, &mut k), num(&toks, &mut k));
                        x = if rel { x + nx } else { nx };
                        y = if rel { y + ny } else { ny };
                        start_x = x;
                        start_y = y;
                        cur.push((x, y));
                        cmd = if rel { 'l' } else { 'L' };
                    }
                    'L' => {
                        let (nx, ny) = (num(&toks, &mut k), num(&toks, &mut k));
                        x = if rel { x + nx } else { nx };
                        y = if rel { y + ny } else { ny };
                        cur.push((x, y));
                    }
                    'H' => {
                        let nx = num(&toks, &mut k);
                        x = if rel { x + nx } else { nx };
                        cur.push((x, y));
                    }
                    'V' => {
                        let ny = num(&toks, &mut k);
                        y = if rel { y + ny } else { ny };
                        cur.push((x, y));
                    }
                    'C' | 'S' => {
                        let (c1x, c1y) = if up == 'C' {
                            let (a, b) = (num(&toks, &mut k), num(&toks, &mut k));
                            (if rel { x + a } else { a }, if rel { y + b } else { b })
                        } else {
                            // S: first control = reflection of previous ctrl.
                            match (prev_cmd, prev_ctrl) {
                                ('C' | 'S', Some((px, py))) => (2.0 * x - px, 2.0 * y - py),
                                _ => (x, y),
                            }
                        };
                        let (a, b) = (num(&toks, &mut k), num(&toks, &mut k));
                        let (c2x, c2y) = (if rel { x + a } else { a }, if rel { y + b } else { b });
                        let (a, b) = (num(&toks, &mut k), num(&toks, &mut k));
                        let (ex, ey) = (if rel { x + a } else { a }, if rel { y + b } else { b });
                        for i in 1..=CURVE_STEPS {
                            let t = i as f32 / CURVE_STEPS as f32;
                            cur.push(cubic(x, y, c1x, c1y, c2x, c2y, ex, ey, t));
                        }
                        prev_ctrl = Some((c2x, c2y));
                        x = ex;
                        y = ey;
                        prev_cmd = 'C';
                        continue;
                    }
                    'Q' | 'T' => {
                        let (cx, cy) = if up == 'Q' {
                            let (a, b) = (num(&toks, &mut k), num(&toks, &mut k));
                            (if rel { x + a } else { a }, if rel { y + b } else { b })
                        } else {
                            match (prev_cmd, prev_ctrl) {
                                ('Q' | 'T', Some((px, py))) => (2.0 * x - px, 2.0 * y - py),
                                _ => (x, y),
                            }
                        };
                        let (a, b) = (num(&toks, &mut k), num(&toks, &mut k));
                        let (ex, ey) = (if rel { x + a } else { a }, if rel { y + b } else { b });
                        for i in 1..=CURVE_STEPS {
                            let t = i as f32 / CURVE_STEPS as f32;
                            cur.push(quad(x, y, cx, cy, ex, ey, t));
                        }
                        prev_ctrl = Some((cx, cy));
                        x = ex;
                        y = ey;
                        prev_cmd = 'Q';
                        continue;
                    }
                    'A' => {
                        let rx = num(&toks, &mut k);
                        let ry = num(&toks, &mut k);
                        let rot = num(&toks, &mut k).to_radians();
                        let large = num(&toks, &mut k) != 0.0;
                        let sweep = num(&toks, &mut k) != 0.0;
                        let (a, b) = (num(&toks, &mut k), num(&toks, &mut k));
                        let (ex, ey) = (if rel { x + a } else { a }, if rel { y + b } else { b });
                        for p in flatten_arc(x, y, rx, ry, rot, large, sweep, ex, ey) {
                            cur.push(p);
                        }
                        x = ex;
                        y = ey;
                        prev_cmd = 'A';
                        continue;
                    }
                    _ => {
                        k += 1;
                    }
                }
                prev_cmd = up;
                prev_ctrl = None;
            }
        }
    }
    if !cur.is_empty() {
        polys.push(cur);
    }
    polys
}

#[allow(clippy::too_many_arguments)]
fn cubic(
    x0: f32,
    y0: f32,
    x1: f32,
    y1: f32,
    x2: f32,
    y2: f32,
    x3: f32,
    y3: f32,
    t: f32,
) -> (f32, f32) {
    let u = 1.0 - t;
    let (a, b, c, d) = (u * u * u, 3.0 * u * u * t, 3.0 * u * t * t, t * t * t);
    (a * x0 + b * x1 + c * x2 + d * x3, a * y0 + b * y1 + c * y2 + d * y3)
}

fn quad(x0: f32, y0: f32, x1: f32, y1: f32, x2: f32, y2: f32, t: f32) -> (f32, f32) {
    let u = 1.0 - t;
    let (a, b, c) = (u * u, 2.0 * u * t, t * t);
    (a * x0 + b * x1 + c * x2, a * y0 + b * y1 + c * y2)
}

/// SVG elliptical arc → sampled points (endpoint → center parameterization,
/// W3C SVG spec B.2.4; radii scaled up when the endpoints don't fit).
#[allow(clippy::too_many_arguments)]
fn flatten_arc(
    x0: f32,
    y0: f32,
    rx_in: f32,
    ry_in: f32,
    rot: f32,
    large: bool,
    sweep: bool,
    x1: f32,
    y1: f32,
) -> Vec<(f32, f32)> {
    let (mut rx, mut ry) = (rx_in.abs(), ry_in.abs());
    if rx == 0.0 || ry == 0.0 || (x0 == x1 && y0 == y1) {
        return vec![(x1, y1)];
    }
    let (cos_r, sin_r) = (rot.cos(), rot.sin());
    let dx2 = (x0 - x1) / 2.0;
    let dy2 = (y0 - y1) / 2.0;
    let x1p = cos_r * dx2 + sin_r * dy2;
    let y1p = -sin_r * dx2 + cos_r * dy2;
    let lambda = (x1p * x1p) / (rx * rx) + (y1p * y1p) / (ry * ry);
    if lambda > 1.0 {
        let s = lambda.sqrt();
        rx *= s;
        ry *= s;
    }
    let num = (rx * rx) * (ry * ry) - (rx * rx) * (y1p * y1p) - (ry * ry) * (x1p * x1p);
    let den = (rx * rx) * (y1p * y1p) + (ry * ry) * (x1p * x1p);
    let mut coef = if den == 0.0 { 0.0 } else { (num / den).max(0.0).sqrt() };
    if large == sweep {
        coef = -coef;
    }
    let cxp = coef * rx * y1p / ry;
    let cyp = -coef * ry * x1p / rx;
    let cx = cos_r * cxp - sin_r * cyp + (x0 + x1) / 2.0;
    let cy = sin_r * cxp + cos_r * cyp + (y0 + y1) / 2.0;
    let angle = |ux: f32, uy: f32, vx: f32, vy: f32| -> f32 {
        let dot = ux * vx + uy * vy;
        let len = (ux * ux + uy * uy).sqrt() * (vx * vx + vy * vy).sqrt();
        let mut a = (dot / len).clamp(-1.0, 1.0).acos();
        if ux * vy - uy * vx < 0.0 {
            a = -a;
        }
        a
    };
    let theta1 = angle(1.0, 0.0, (x1p - cxp) / rx, (y1p - cyp) / ry);
    let mut dtheta =
        angle((x1p - cxp) / rx, (y1p - cyp) / ry, (-x1p - cxp) / rx, (-y1p - cyp) / ry);
    if !sweep && dtheta > 0.0 {
        dtheta -= core::f32::consts::TAU;
    } else if sweep && dtheta < 0.0 {
        dtheta += core::f32::consts::TAU;
    }
    let steps = CURVE_STEPS;
    (1..=steps)
        .map(|i| {
            let t = theta1 + dtheta * (i as f32 / steps as f32);
            (
                cx + rx * t.cos() * cos_r - ry * t.sin() * sin_r,
                cy + rx * t.cos() * sin_r + ry * t.sin() * cos_r,
            )
        })
        .collect()
}

fn num(toks: &[Tok], k: &mut usize) -> f32 {
    while *k < toks.len() {
        if let Tok::Num(n) = toks[*k] {
            *k += 1;
            return n;
        }
        *k += 1;
    }
    0.0
}

enum Tok {
    Cmd(char),
    Num(f32),
}

fn tokenize(d: &str) -> Vec<Tok> {
    let mut toks = Vec::new();
    let chars: Vec<char> = d.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        if c.is_ascii_alphabetic() {
            toks.push(Tok::Cmd(c));
            i += 1;
        } else if c == '-' || c == '+' || c == '.' || c.is_ascii_digit() {
            let start = i;
            if c == '-' || c == '+' {
                i += 1;
            }
            let mut seen_dot = false;
            while i < chars.len() {
                let d = chars[i];
                if d.is_ascii_digit() {
                    i += 1;
                } else if d == '.' && !seen_dot {
                    seen_dot = true;
                    i += 1;
                } else {
                    break;
                }
            }
            let s: String = chars[start..i].iter().collect();
            toks.push(Tok::Num(s.parse().unwrap_or(0.0)));
        } else {
            i += 1;
        }
    }
    toks
}

/// Stroke a segment into a filled quad (normalized `0..1000`, y down).
/// A 24-space point in the normalized `0..1000` viewbox.
fn normalized((x, y): (f32, f32)) -> (u16, u16) {
    let n = |v: f32| (v / VIEW * 1000.0).round().clamp(0.0, 1000.0) as u16;
    (n(x), n(y))
}

/// The root `<svg>`'s `stroke-width` in the normalized viewbox (the icon set's default 2).
fn svg_stroke_width_milli(svg: &str) -> u16 {
    let root = extract_tags(svg, "svg").into_iter().next().unwrap_or_default();
    let width = attr_value(&root, "stroke-width").and_then(|v| v.parse().ok()).unwrap_or(2.0f32);
    (width / VIEW * 1000.0).round() as u16
}
