// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0

//! CONTEXT: Build script — generates `APP_MANIFEST_CAPS` from the real bundle
//! manifests so abilitymgr enforces exactly each app's declared caps (RFC-0065).
//! OWNERS: @ui @runtime
//! STATUS: Functional
//! API_STABILITY: Unstable
//! TEST_COVERAGE: No tests (build script; the generated table is exercised by `caps.rs` tests)
//!
//! Build script: generates the app → declared-capabilities table
//! (`APP_MANIFEST_CAPS`) from the REAL bundle manifests
//! (`userspace/apps/<app>/manifest.toml` `caps = [...]`) (RFC-0065). The manifests are
//! the single source of truth — the same files `bundlemgrd` derives its registry
//! from — so `abilitymgr` enforces exactly the permissions each app declares,
//! with no hand-maintained duplicate. The generated table is `include!`d by
//! `caps.rs`.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo::rustc-check-cfg=cfg(nexus_env, values(\"os\",\"host\"))");

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    // App SSOT (TASK-0081 consolidation): manifests live IN the app folders.
    let bundles_dir = manifest_dir.join("../../../userspace/apps");
    println!("cargo:rerun-if-changed={}", bundles_dir.display());

    let mut apps: Vec<(String, Vec<String>)> = Vec::new();
    let mut ui_programs: Vec<String> = Vec::new();
    let mut pre_session: Vec<String> = Vec::new();
    let mut exports: Vec<(String, Vec<(String, String)>)> = Vec::new();
    if let Ok(entries) = std::fs::read_dir(&bundles_dir) {
        for entry in entries.flatten() {
            let manifest = entry.path().join("manifest.toml");
            if !manifest.is_file() {
                continue;
            }
            println!("cargo:rerun-if-changed={}", manifest.display());
            if let Some((name, caps)) = read_app(&manifest) {
                let text = std::fs::read_to_string(&manifest).unwrap_or_default();
                let entries = export_entries(&text);
                for (_, permission) in &entries {
                    let prefix = format!("app.{name}.");
                    assert!(
                        permission.starts_with(&prefix) && permission.len() > prefix.len(),
                        "{name}: export permission `{permission}` outside its own namespace"
                    );
                }
                if !entries.is_empty() {
                    exports.push((name.clone(), entries));
                }
                let text_again = std::fs::read_to_string(&manifest).unwrap_or_default();
                if field_value(&text_again, "payload_kind").as_deref() == Some("ui-program") {
                    ui_programs.push(name.clone());
                }
                // The GREETER role is the pre-session surface by definition —
                // abilitymgr's session gate admits it BEFORE login (declarative
                // via bundle_type, never a hardcoded app name).
                if field_value(&text_again, "bundle_type").as_deref() == Some("greeter") {
                    pre_session.push(name.clone());
                }
                apps.push((name, caps));
            }
        }
    }
    apps.sort();
    ui_programs.sort();
    pre_session.sort();
    exports.sort();

    let mut out = String::new();
    out.push_str(
        "// @generated by build.rs from userspace/apps/<app>/manifest.toml — do not edit.\n",
    );
    let _ = writeln!(out, "pub(crate) const APP_MANIFEST_CAPS: &[(&str, &[&str])] = &[");
    for (name, caps) in &apps {
        let _ = write!(out, "    ({name:?}, &[");
        for cap in caps {
            let _ = write!(out, "{cap:?}, ");
        }
        out.push_str("]),\n");
    }
    out.push_str("];\n");

    // Apps whose manifest declares `payload_kind = "ui-program"` — these spawn
    // through the shared app-host runtime (GET_PAYLOAD sourcing, TASK-0080D);
    // manifest-driven, replacing the hand-maintained image_for_app table.
    // Consumed by the os-lite spawn path only (hence the host allow).
    out.push_str("#[allow(dead_code)]\n");
    let _ = writeln!(out, "pub(crate) const APP_UI_PROGRAMS: &[&str] = &[");
    for name in &ui_programs {
        let _ = writeln!(out, "    {name:?},");
    }
    out.push_str("];\n");

    // Apps allowed to launch BEFORE an active session (bundle_type = greeter):
    // the login surface itself. Everything else stays session-gated.
    out.push_str("#[allow(dead_code)]\n");
    let _ = writeln!(out, "pub(crate) const APP_PRE_SESSION: &[&str] = &[");
    for name in &pre_session {
        let _ = writeln!(out, "    {name:?},");
    }
    out.push_str("];\n");

    // v2.2 exports (TASK-0081): app → (ability, app-owned permission) — the
    // fail-closed source for consumer-cap validation and, later, the
    // mediated-then-direct launch path. Namespaces validated ABOVE at build.
    out.push_str("#[allow(dead_code)]\n");
    let _ = writeln!(out, "pub(crate) const APP_EXPORTS: &[(&str, &[(&str, &str)])] = &[");
    for (name, entries) in &exports {
        let _ = write!(out, "    ({name:?}, &[");
        for (ability, permission) in entries {
            let _ = write!(out, "({ability:?}, {permission:?}), ");
        }
        out.push_str("]),\n");
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("app_manifest_caps.rs");
    std::fs::write(&dest, out).expect("write app_manifest_caps.rs");
}

/// Parses `(name, caps[])` from a manifest's `name = "..."` and `caps = [...]`.
fn read_app(manifest: &Path) -> Option<(String, Vec<String>)> {
    let text = std::fs::read_to_string(manifest).ok()?;
    let name = field_value(&text, "name")?;
    let caps = text
        .lines()
        .map(str::trim)
        .find(|l| l.starts_with("caps") && l.contains('='))
        .map(|l| quoted_strings(l))
        .unwrap_or_default();
    Some((name, caps))
}

/// Extracts a scalar `key = "value"` string field.
fn field_value(text: &str, key: &str) -> Option<String> {
    text.lines().find_map(|line| {
        let line = line.trim();
        let rest = line.strip_prefix(key)?.trim_start();
        let rest = rest.strip_prefix('=')?.trim();
        let val = rest.trim_matches('"');
        (!val.is_empty()).then(|| val.to_string())
    })
}

/// Collects every `"..."`-quoted string on a line (the array elements).
fn quoted_strings(line: &str) -> Vec<String> {
    let mut out = Vec::new();
    let bytes = line.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'"' {
            let start = i + 1;
            let mut j = start;
            while j < bytes.len() && bytes[j] != b'"' {
                j += 1;
            }
            if j < bytes.len() {
                out.push(line[start..j].to_string());
            }
            i = j + 1;
        } else {
            i += 1;
        }
    }
    out
}

/// Parses `exports = [{ ability = "…", permission = "…" }, …]` entries.
/// The hand parser is line-based: every `{ … }` item contributes its quoted
/// strings in (ability, permission) order — multi-line arrays are collected
/// until the closing `]`.
fn export_entries(text: &str) -> Vec<(String, String)> {
    let mut in_exports = false;
    let mut strings: Vec<String> = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.starts_with('#') {
            continue;
        }
        if !in_exports {
            if line.starts_with("exports") && line.contains('=') {
                in_exports = true;
                strings.extend(quoted_strings(line));
                if line.ends_with(']') {
                    break;
                }
            }
            continue;
        }
        strings.extend(quoted_strings(line));
        if line.ends_with(']') {
            break;
        }
    }
    strings.chunks_exact(2).map(|pair| (pair[0].clone(), pair[1].clone())).collect()
}
