// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0

fn main() {
    println!("cargo::rustc-check-cfg=cfg(nexus_env, values(\"os\",\"host\"))");

    // TASK-0080D R1: embed the app-host runtime ELF when the build
    // orchestration provides it (`scripts/build.sh` builds app-host first and
    // exports EXECD_APPHOST_ELF). Absent (plain cargo builds/checks), the
    // image table entry stays empty and IMG_APPHOST answers UNSUPPORTED —
    // never a silent fake payload.
    println!("cargo:rerun-if-env-changed=EXECD_APPHOST_ELF");
    let out = std::path::PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out.join("apphost_payload.rs");
    match std::env::var("EXECD_APPHOST_ELF") {
        Ok(path) if !path.trim().is_empty() => {
            println!("cargo:rerun-if-changed={path}");
            std::fs::write(
                &dest,
                format!(
                    "/// app-host runtime ELF (built by scripts/build.sh).\n\
                     pub static APPHOST_ELF: &[u8] = include_bytes!({path:?});\n"
                ),
            )
            .expect("write apphost payload shim");
        }
        _ => {
            std::fs::write(
                &dest,
                "/// No app-host ELF provided at build time (plain cargo build).\n\
                 pub static APPHOST_ELF: &[u8] = &[];\n",
            )
            .expect("write apphost payload shim");
        }
    }

    // P0.2 recv-wake regression gate: embed the probe child ELF when the
    // build orchestration provides it (same pattern as EXECD_APPHOST_ELF).
    // Absent, the probe run is skipped with a visible marker — never faked.
    println!("cargo:rerun-if-env-changed=EXECD_RECVWAKE_ELF");
    let dest = out.join("recvwake_payload.rs");
    match std::env::var("EXECD_RECVWAKE_ELF") {
        Ok(path) if !path.trim().is_empty() => {
            println!("cargo:rerun-if-changed={path}");
            std::fs::write(
                &dest,
                format!(
                    "/// recv-wake probe ELF (built by scripts/build.sh).\n\
                     pub static RECVWAKE_ELF: &[u8] = include_bytes!({path:?});\n"
                ),
            )
            .expect("write recvwake payload shim");
        }
        _ => {
            std::fs::write(
                &dest,
                "/// No recv-wake probe ELF provided at build time (plain cargo build).\n\
                 pub static RECVWAKE_ELF: &[u8] = &[];\n",
            )
            .expect("write recvwake payload shim");
        }
    }

    // TASK-0080C declarative routing: generate the app → declared-caps table
    // (`APP_MANIFEST_CAPS`) from the REAL bundle manifests
    // (`userspace/apps/<app>/manifest.toml` `caps = [...]`) — the same SSOT
    // abilitymgr and bundlemgrd read. execd provisions a spawned app-host's
    // service routes (`nexus-sdk-routes`) ONLY for the caps its manifest
    // declares, so the per-app service wiring is cap-gated and manifest-driven,
    // never hand-maintained.
    let manifest_dir =
        std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let bundles_dir = manifest_dir.join("../../../userspace/apps");
    println!("cargo:rerun-if-changed={}", bundles_dir.display());
    let mut apps: Vec<(String, Vec<String>)> = Vec::new();
    if let Ok(entries) = std::fs::read_dir(&bundles_dir) {
        for entry in entries.flatten() {
            let manifest = entry.path().join("manifest.toml");
            if !manifest.is_file() {
                continue;
            }
            println!("cargo:rerun-if-changed={}", manifest.display());
            if let Some(app) = read_app(&manifest) {
                apps.push(app);
            }
        }
    }
    apps.sort();
    let mut caps_out = String::from(
        "// @generated by build.rs from userspace/apps/<app>/manifest.toml — do not edit.\n\
         pub(crate) const APP_MANIFEST_CAPS: &[(&str, &[&str])] = &[\n",
    );
    for (name, caps) in &apps {
        caps_out.push_str(&format!("    ({name:?}, &["));
        for cap in caps {
            caps_out.push_str(&format!("{cap:?}, "));
        }
        caps_out.push_str("]),\n");
    }
    caps_out.push_str("];\n");
    std::fs::write(out.join("app_manifest_caps.rs"), caps_out)
        .expect("write app_manifest_caps.rs");
}

/// Parses `(name, caps[])` from a manifest's `name = "..."` and `caps = [...]`.
fn read_app(manifest: &std::path::Path) -> Option<(String, Vec<String>)> {
    let text = std::fs::read_to_string(manifest).ok()?;
    let name = field_value(&text, "name")?;
    let caps = text
        .lines()
        .map(str::trim)
        .find(|l| l.starts_with("caps") && l.contains('='))
        .map(quoted_strings)
        .unwrap_or_default();
    Some((name, caps))
}

/// Extracts a scalar `key = "value"` string field.
fn field_value(text: &str, key: &str) -> Option<String> {
    text.lines().find_map(|line| {
        let line = line.trim();
        let rest = line.strip_prefix(key)?.trim_start();
        let rest = rest.strip_prefix('=')?.trim();
        let val = rest.trim_matches('"');
        (!val.is_empty()).then(|| val.to_string())
    })
}

/// Collects every `"..."`-quoted string on a line (the array elements).
fn quoted_strings(line: &str) -> Vec<String> {
    let mut out = Vec::new();
    let bytes = line.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'"' {
            let start = i + 1;
            let mut j = start;
            while j < bytes.len() && bytes[j] != b'"' {
                j += 1;
            }
            if j < bytes.len() {
                out.push(line[start..j].to_string());
            }
            i = j + 1;
        } else {
            i += 1;
        }
    }
    out
}
