// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0
//
//! CONTEXT: Build-time exposure table for ingressd (RFC-0092 §1). Compiles
//! every `[[expose."<subject>"]]` of the policy SSOT (`policies/*`) through
//! the SAME `expose.rs` the host `policy` crate and policyd's build.rs use,
//! so the gateway's data-plane table can never drift from the authority.
//! OWNERS: @runtime @security
//! STATUS: Experimental
//! TEST_COVERAGE: tests/ingress_host/ (`shipped_policy_table_is_consistent`)
//! INVARIANTS:
//! - deterministic, bounded (≤ 64 entries — a bound is a build failure)
//! - subject ids are FNV-1a of the canonical name (the one policy hash)

// Build scripts are allowed to panic on misconfiguration.
#![allow(clippy::expect_used)]

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[path = "../../../userspace/policy/src/expose.rs"]
#[allow(dead_code)]
mod expose;
#[path = "../../../userspace/policy/src/learn_record.rs"]
#[allow(dead_code)]
mod learn_record;
#[path = "../../../userspace/policy/src/schema.rs"]
#[allow(dead_code)]
mod schema;

use expose::{Expose, Proto};
use learn_record::service_id_from_name;

/// Only the sections this table needs are typed; the rest of the policy
/// vocabulary is validated by policyd's build.rs (same files, same grammar).
#[derive(Debug, Default, Deserialize)]
struct RawPolicy {
    #[serde(default)]
    expose: BTreeMap<String, Vec<expose::RawExpose>>,
}

#[derive(Debug, Deserialize)]
struct RawPolicyRoot {
    version: u32,
    #[serde(default)]
    include: Vec<String>,
}

fn main() {
    println!("cargo::rustc-check-cfg=cfg(nexus_env, values(\"os\",\"host\"))");
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR missing");
    let policy_dir = Path::new(&manifest_dir)
        .join("../../../policies")
        .canonicalize()
        .expect("failed to resolve policies");
    let exposes = load_exposes(&policy_dir);
    emit_table(&exposes);
}

fn load_exposes(dir: &Path) -> BTreeMap<String, Vec<Expose>> {
    let root_path = dir.join("nexus.policy.toml");
    let root_data =
        fs::read_to_string(&root_path).expect("failed to read policies/nexus.policy.toml");
    let root: RawPolicyRoot =
        toml::from_str(&root_data).expect("failed to parse policies/nexus.policy.toml");
    assert!(root.version == 1, "unsupported policy root version");
    let mut files = Vec::new();
    for include in root.include {
        assert!(
            !include.contains("..") && !Path::new(&include).is_absolute(),
            "policy include escapes policies root"
        );
        let path = dir.join(include);
        assert!(
            path.is_file() && path.extension().and_then(|s| s.to_str()) == Some("toml"),
            "policy include is not a TOML file"
        );
        files.push(path);
    }
    files.sort();
    println!("cargo::rerun-if-changed={}", root_path.display());
    for shared in ["schema.rs", "expose.rs", "learn_record.rs"] {
        println!(
            "cargo::rerun-if-changed={}",
            Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../../userspace/policy/src")
                .join(shared)
                .display()
        );
    }
    let mut exposes: BTreeMap<String, Vec<Expose>> = BTreeMap::new();
    for path in files {
        println!("cargo::rerun-if-changed={}", path.display());
        let data = fs::read_to_string(&path).expect("failed to read policy file");
        let parsed: RawPolicy =
            toml::from_str(&data).unwrap_or_else(|_| panic!("failed to parse {}", path.display()));
        for (service, raw) in parsed.expose {
            let compiled = expose::compile_exposes(&service, &raw).unwrap_or_else(|err| {
                panic!("invalid expose for {service} in {}: {err}", path.display())
            });
            exposes.insert(service.trim().to_ascii_lowercase(), compiled);
        }
    }
    expose::check_exposes_unique(exposes.iter().map(|(k, v)| (k.as_str(), v.as_slice())))
        .unwrap_or_else(|err| panic!("invalid expose set: {err}"));
    exposes
}

fn emit_table(exposes: &BTreeMap<String, Vec<Expose>>) {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR missing"));
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by ingressd/build.rs. DO NOT EDIT.\n");
    out.push_str("/// Every declared exposure, canonical (subject, port, proto) order.\n");
    out.push_str("pub const EXPOSE_ENTRIES: &[super::ExposeEntry] = &[\n");
    for (subject, list) in exposes {
        let subject_id = service_id_from_name(subject.as_bytes());
        for e in list {
            let cidrs: Vec<String> = e
                .cidr_allow
                .iter()
                .map(|c| {
                    format!(
                        "super::Cidr {{ addr: [{}, {}, {}, {}], len: {}u8 }}",
                        c.addr[0], c.addr[1], c.addr[2], c.addr[3], c.len
                    )
                })
                .collect();
            let proto = match e.proto {
                Proto::Tcp => "super::Proto::Tcp",
                Proto::Udp => "super::Proto::Udp",
            };
            out.push_str(&format!(
                "    super::ExposeEntry {{ subject_id: 0x{subject_id:016x}u64, port: {}u16, proto: {proto}, cidr_allow: &[{}], rate_per_s: {}u32, burst: {}u32, backend: {}u16 }},\n",
                e.port,
                cidrs.join(", "),
                e.rate_per_s,
                e.burst,
                e.backend
            ));
        }
    }
    out.push_str("];\n");
    fs::write(out_dir.join("expose_table.rs"), out).expect("failed to write expose_table.rs");
}
