// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0

//! Build script: rasterizes each app bundle's REAL icon artwork
//! (`userspace/apps/<id>/assets/icon.svg`, declared in the bundle manifest as
//! `icon_svg = "assets/icon.svg"`) into straight-alpha RGBA sprites at every
//! tile size the shell uses (64 grid / 44 dock / 32 taskbar). Same house
//! style as the windowd cursor/chrome bake: nexus-svg renders at 4×
//! supersampling, a box average downscales, alpha is unassociated. The
//! manifest is the SSOT — an app without `icon_svg` simply has no sprite and
//! the shell tile keeps its gradient+glyph fallback.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// Tile sizes the shell renders (AppTile / DockTile / TaskbarTile).
const SIZES: &[u32] = &[64, 44, 32];
/// Supersampling factor for crisp AA at small sizes.
const SS: u32 = 4;

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let apps_dir = manifest_dir.join("../../apps");
    println!("cargo:rerun-if-changed={}", apps_dir.display());

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if let Ok(read) = std::fs::read_dir(&apps_dir) {
        for entry in read.flatten() {
            let manifest = entry.path().join("manifest.toml");
            if !manifest.is_file() {
                continue;
            }
            println!("cargo:rerun-if-changed={}", manifest.display());
            let Ok(text) = std::fs::read_to_string(&manifest) else { continue };
            let field = |key: &str| -> Option<String> {
                text.lines().find_map(|line| {
                    let line = line.trim();
                    let rest = line.strip_prefix(key)?.trim_start();
                    let rest = rest.strip_prefix('=')?.trim();
                    let val = rest.trim_matches('"');
                    (!val.is_empty()).then(|| val.to_string())
                })
            };
            let (Some(name), Some(icon_svg)) = (field("name"), field("icon_svg")) else {
                continue;
            };
            let svg_path = entry.path().join(&icon_svg);
            if svg_path.is_file() {
                println!("cargo:rerun-if-changed={}", svg_path.display());
                entries.push((name, svg_path));
            } else {
                println!(
                    "cargo:warning=app '{name}': icon_svg '{icon_svg}' missing — no sprite baked"
                );
            }
        }
    }
    entries.sort();

    let mut out = String::from(
        "// @generated by build.rs from userspace/apps/*/manifest.toml icon_svg — do not edit.\n\n",
    );
    let mut table = String::new();
    for (id, svg_path) in &entries {
        let svg = std::fs::read_to_string(svg_path)
            .unwrap_or_else(|e| panic!("app-icons: read {}: {e}", svg_path.display()));
        for &size in SIZES {
            let hi = nexus_svg::render_svg_at(&svg, size * SS, size * SS)
                .unwrap_or_else(|e| panic!("app-icons: rasterize {id}@{size}: {e:?}"));
            let premul = box_average_downscale(&hi.buffer, hi.width, hi.height, SS);
            let rgba = straight_rgba_from_premul_bgra(&premul);
            let ident = format!("SPRITE_{}_{}", id.to_uppercase().replace('-', "_"), size);
            let _ = writeln!(out, "static {ident}: [u8; {}] = [", rgba.len());
            for chunk in rgba.chunks(16) {
                out.push_str("    ");
                for b in chunk {
                    let _ = write!(out, "{b}, ");
                }
                out.push('\n');
            }
            out.push_str("];\n");
            let _ = writeln!(table, "        ({id:?}, {size}) => Some(&{ident}),");
        }
    }
    let _ = writeln!(
        out,
        "pub(crate) fn sprite_bytes(id: &str, size: u32) -> Option<&'static [u8]> {{\n    \
         match (id, size) {{\n{table}        _ => None,\n    }}\n}}"
    );
    let out_path = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("app_icons.rs");
    std::fs::write(&out_path, out).unwrap();
    let _ = Path::new("");
}

/// Box-average `factor`× downscale (premultiplied BGRA) — the windowd bake's
/// downscaler, verbatim semantics.
fn box_average_downscale(src: &[u8], sw: u32, sh: u32, factor: u32) -> Vec<u8> {
    let dw = sw / factor;
    let dh = sh / factor;
    let n = factor * factor;
    let mut out = vec![0u8; (dw * dh * 4) as usize];
    for y in 0..dh {
        for x in 0..dw {
            let mut acc = [0u32; 4];
            for sy in 0..factor {
                for sx in 0..factor {
                    let i = (((y * factor + sy) * sw + (x * factor + sx)) * 4) as usize;
                    for c in 0..4 {
                        acc[c] += src[i + c] as u32;
                    }
                }
            }
            let o = ((y * dw + x) * 4) as usize;
            for c in 0..4 {
                out[o + c] = (acc[c] / n) as u8;
            }
        }
    }
    out
}

/// Premultiplied BGRA → straight-alpha RGBA (the scene painter blends
/// straight `Rgba8` per pixel).
fn straight_rgba_from_premul_bgra(src: &[u8]) -> Vec<u8> {
    let mut out = vec![0u8; src.len()];
    for (i, px) in src.chunks_exact(4).enumerate() {
        let (b, g, r, a) = (px[0] as u32, px[1] as u32, px[2] as u32, px[3] as u32);
        let un = |c: u32| -> u8 {
            if a == 0 {
                0
            } else if a >= 255 {
                c.min(255) as u8
            } else {
                ((c * 255 + a / 2) / a).min(255) as u8
            }
        };
        let o = i * 4;
        out[o] = un(r);
        out[o + 1] = un(g);
        out[o + 2] = un(b);
        out[o + 3] = a as u8;
    }
    out
}
