[package]
name = "nexus-background"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
redox-log = "0.1"
orbclient = "0.3"
orbimage  = "0.1"
dirs = "5.0.0"

# Wichtig: UNBEDINGT un-conditional (nicht target-spezifisch)
redox_event = "0.4.1"
libredox    = { version = "0.1.3", default-features = false, features = ["std", "call"] }
libnexus    = { path = "../../../libs/libnexus/source" }
