// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0

#![allow(clippy::unwrap_used)]

//! Build-time MSDF atlas generator.
//! Renders each printable ASCII glyph as a 32×32 signed distance field,
//! packs them into a single BGRA atlas texture, and emits a glyph metrics
//! table for runtime sampling.

use std::env;
use std::fs::{self, File};
use std::io::Write;
use std::path::Path;

const INTER_FONT: &str = "../../../resources/fonts/inter/docs/font-files/InterVariable.ttf";
const GLYPH_SIZE: u32 = 32;
const ATLAS_COLS: u32 = 32; // 32 glyphs per row → 1024 px wide
const FIRST_CHAR: u32 = 32; // space
const LAST_CHAR: u32 = 126; // ~
const GLYPH_COUNT: u32 = LAST_CHAR - FIRST_CHAR + 1;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed={INTER_FONT}");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = env::var_os("OUT_DIR").ok_or("missing OUT_DIR")?;
    let out_dir = Path::new(&out_dir);

    let font_bytes = fs::read(INTER_FONT)?;
    let font = fontdue::Font::from_bytes(font_bytes, fontdue::FontSettings::default())
        .map_err(|err| std::io::Error::other(format!("parse Inter font: {err:?}")))?;

    let atlas_rows = GLYPH_COUNT.div_ceil(ATLAS_COLS);
    let atlas_width = ATLAS_COLS * GLYPH_SIZE;
    let atlas_height = atlas_rows * GLYPH_SIZE;

    let mut atlas = vec![0u8; (atlas_width * atlas_height * 4) as usize];
    let mut metrics = Vec::with_capacity(GLYPH_COUNT as usize);

    // Emit atlas binary first
    let atlas_path = out_dir.join("msdf_atlas.bgra");
    let atlas_display = atlas_path.display().to_string();
    println!("cargo:rustc-env=MSDF_ATLAS_PATH={atlas_display}");

    for idx in 0..GLYPH_COUNT {
        let ch = char::from_u32(FIRST_CHAR + idx).unwrap();
        let (metrics_entry, sdf) = render_glyph_sdf(&font, ch, GLYPH_SIZE)?;
        metrics.push(metrics_entry);

        // Pack into atlas
        let col = idx % ATLAS_COLS;
        let row = idx / ATLAS_COLS;
        let base_x = col * GLYPH_SIZE;
        let base_y = row * GLYPH_SIZE;

        for gy in 0..GLYPH_SIZE {
            for gx in 0..GLYPH_SIZE {
                let src = (gy * GLYPH_SIZE + gx) as usize;
                let dst = ((base_y + gy) * atlas_width + (base_x + gx)) as usize * 4;
                let sd = sdf[src]; // 0-255 mapped: 128 = edge
                atlas[dst] = sd;
                atlas[dst + 1] = sd;
                atlas[dst + 2] = sd;
                atlas[dst + 3] = sd;
            }
        }
    }

    fs::write(&atlas_path, &atlas)?;

    // Emit metrics table as Rust source
    let metrics_path = out_dir.join("msdf_metrics.rs");
    let mut f = File::create(&metrics_path)?;

    writeln!(f, "// Auto-generated by build.rs — MSDF glyph metrics")?;
    writeln!(f)?;
    writeln!(f, "use crate::GlyphMetrics;")?;
    writeln!(f)?;
    writeln!(f, "// Atlas: {atlas_width}×{atlas_height} BGRA, {GLYPH_COUNT} glyphs")?;
    writeln!(f)?;
    writeln!(f, "/// Number of glyphs in the atlas.")?;
    writeln!(f, "pub const MSDF_GLYPH_COUNT: u32 = {GLYPH_COUNT};")?;
    writeln!(f, "/// First character code in the atlas.")?;
    writeln!(f, "pub const MSDF_FIRST_CHAR: u32 = {FIRST_CHAR};")?;
    writeln!(f, "/// Atlas width in pixels.")?;
    writeln!(f, "pub const MSDF_ATLAS_WIDTH: u32 = {atlas_width};")?;
    writeln!(f, "/// Atlas height in pixels.")?;
    writeln!(f, "pub const MSDF_ATLAS_HEIGHT: u32 = {atlas_height};")?;
    writeln!(f, "/// Glyph cell size in pixels.")?;
    writeln!(f, "pub const MSDF_GLYPH_SIZE: u32 = {GLYPH_SIZE};")?;
    writeln!(f)?;
    writeln!(f, "/// Atlas pixel data (BGRA, {atlas_width}×{atlas_height}).")?;
    writeln!(f, "pub static MSDF_ATLAS: &[u8] = include_bytes!(env!(\"MSDF_ATLAS_PATH\"));")?;
    writeln!(f)?;
    writeln!(f, "/// Per-glyph metrics, indexed by `(char_code - MSDF_FIRST_CHAR)`.")?;
    writeln!(f, "pub static MSDF_METRICS: &[GlyphMetrics] = &[")?;
    for (i, m) in metrics.iter().enumerate() {
        let (col, row) = (i as u32 % ATLAS_COLS, i as u32 / ATLAS_COLS);
        writeln!(
            f,
            "    GlyphMetrics {{ atlas_col: {col}, atlas_row: {row}, advance: {advance:.1}, bearing_x: {bx:.1}, bearing_y: {by:.1}, width: {w}, height: {h} }},",
            advance = m.advance,
            bx = m.bearing_x,
            by = m.bearing_y,
            w = m.width,
            h = m.height
        )?;
    }
    writeln!(f, "];")?;

    Ok(())
}

struct GlyphMetrics {
    advance: f32,
    bearing_x: f32,
    bearing_y: f32,
    width: u32,
    height: u32,
}

/// Render a single glyph as a 32×32 signed distance field.
/// Returns metrics + SDF bytes (0-255, 128 = edge).
fn render_glyph_sdf(
    font: &fontdue::Font,
    ch: char,
    size: u32,
) -> Result<(GlyphMetrics, Vec<u8>), Box<dyn std::error::Error>> {
    let scale = size as f32;
    let (metrics, bitmap) = font.rasterize(ch, scale);

    let sdf = if bitmap.is_empty() {
        // Whitespace: all outside (0)
        vec![0u8; (size * size) as usize]
    } else {
        // Compute SDF from rendered bitmap
        // First, embed the bitmap into a size×size grid centered on the glyph
        let mut glyph_buf = vec![0u8; (size * size) as usize];
        let glyph_width = metrics.width as u32;
        let glyph_height = metrics.height as u32;

        let offset_x = (size.saturating_sub(glyph_width) / 2) as i32;
        let offset_y = ((size as i32) + metrics.bounds.ymin as i32)
            .max(0)
            .min(size.saturating_sub(glyph_height) as i32);

        for gy in 0..glyph_height {
            for gx in 0..glyph_width {
                let src = (gy * glyph_width + gx) as usize;
                let dst_x = offset_x + gx as i32;
                let dst_y = offset_y + gy as i32;
                if dst_x >= 0 && dst_x < size as i32 && dst_y >= 0 && dst_y < size as i32 {
                    let dst = (dst_y as u32 * size + dst_x as u32) as usize;
                    glyph_buf[dst] = bitmap[src]; // 0-255 coverage
                }
            }
        }

        // Compute SDF: for each pixel, distance to nearest edge
        compute_sdf(&glyph_buf, size)
    };

    // Scale bearing to SDF size
    let scale_ratio = size as f32 / scale;
    let metrics_entry = GlyphMetrics {
        advance: metrics.advance_width * scale_ratio,
        bearing_x: metrics.bounds.xmin * scale_ratio,
        bearing_y: -metrics.bounds.ymin * scale_ratio,
        width: metrics.width as u32,
        height: metrics.height as u32,
    };

    Ok((metrics_entry, sdf))
}

/// Compute a signed distance field from a binary (0/255) glyph buffer.
/// Output: 0 = deepest outside, 128 = edge, 255 = deepest inside.
/// Using a simple 8SSEDT-inspired two-pass algorithm for integer distance.
fn compute_sdf(glyph: &[u8], size: u32) -> Vec<u8> {
    let n = size as usize;
    let max_dist = (size as i32).max(32); // clamp max distance
    let mut outer = vec![max_dist; n * n];
    let mut inner = vec![max_dist; n * n];

    // Initialize: edge pixels get 0, inside gets INF, outside gets INF
    for y in 0..n {
        for x in 0..n {
            let idx = y * n + x;
            let is_inside = glyph[idx] >= 128;
            if is_inside {
                // Check if edge (has outside neighbor)
                let mut is_edge = false;
                for dy in -1i32..=1i32 {
                    for dx in -1i32..=1i32 {
                        let nx = x as i32 + dx;
                        let ny = y as i32 + dy;
                        if nx >= 0 && nx < n as i32 && ny >= 0 && ny < n as i32 {
                            if glyph[(ny as usize) * n + nx as usize] < 128 {
                                is_edge = true;
                            }
                        } else {
                            is_edge = true; // border of image = outside
                        }
                    }
                }
                if is_edge {
                    inner[idx] = 0;
                }
            } else {
                // Check if edge (has inside neighbor)
                let mut is_edge = false;
                for dy in -1i32..=1i32 {
                    for dx in -1i32..=1i32 {
                        let nx = x as i32 + dx;
                        let ny = y as i32 + dy;
                        if nx >= 0
                            && nx < n as i32
                            && ny >= 0
                            && ny < n as i32
                            && glyph[(ny as usize) * n + nx as usize] >= 128
                        {
                            is_edge = true;
                        }
                    }
                }
                if is_edge {
                    outer[idx] = 0;
                }
            }
        }
    }

    // Two-pass distance transform for outer
    dt_pass(&mut outer, n);
    // Two-pass distance transform for inner
    dt_pass(&mut inner, n);

    // Combine: map distance to 0-255, 128 = edge
    let mut sdf = vec![0u8; n * n];
    for i in 0..n * n {
        let d_outer = outer[i];
        let d_inner = inner[i];
        // Signed distance: negative inside, positive outside
        let signed: f32 = if glyph[i] >= 128 {
            d_inner as f32 // inside → positive → maps to > 128 (white)
        } else {
            -(d_outer as f32) // outside → negative → maps to < 128 (black)
        };
        // Map [-max_dist, +max_dist] to [0, 255] with 128 at edge
        let clamped = signed.clamp(-max_dist as f32, max_dist as f32);
        let mapped = ((clamped / max_dist as f32) * 127.0 + 128.0) as u8;
        sdf[i] = mapped;
    }

    sdf
}

/// Two-pass Euclidean distance transform (8SSEDT approximation using Manhattan + diagonal).
/// Modifies `dist` in-place: after pass 1 (top-left to bottom-right) and pass 2 (bottom-right to top-left),
/// each cell contains the approximate Euclidean distance to the nearest zero cell.
fn dt_pass(dist: &mut [i32], n: usize) {
    let max_dist = (n as i32).max(32);

    // Forward pass: top-left to bottom-right
    for y in 0..n {
        for x in 0..n {
            let idx = y * n + x;
            if dist[idx] == 0 {
                continue;
            }
            let mut best = max_dist;
            // Check top, left, top-left, top-right (for forward pass, top-right comes from prev row)
            if y > 0 {
                best = best.min(dist[(y - 1) * n + x].saturating_add(1));
                if x > 0 {
                    best = best.min(dist[(y - 1) * n + (x - 1)].saturating_add(1));
                }
                if x + 1 < n {
                    best = best.min(dist[(y - 1) * n + (x + 1)].saturating_add(1));
                }
            }
            if x > 0 {
                best = best.min(dist[y * n + (x - 1)].saturating_add(1));
            }
            dist[idx] = best.min(dist[idx]);
        }
    }

    // Backward pass: bottom-right to top-left
    for y in (0..n).rev() {
        for x in (0..n).rev() {
            let idx = y * n + x;
            if dist[idx] == 0 {
                continue;
            }
            let mut best = dist[idx];
            if y + 1 < n {
                best = best.min(dist[(y + 1) * n + x].saturating_add(1));
                if x > 0 {
                    best = best.min(dist[(y + 1) * n + (x - 1)].saturating_add(1));
                }
                if x + 1 < n {
                    best = best.min(dist[(y + 1) * n + (x + 1)].saturating_add(1));
                }
            }
            if x + 1 < n {
                best = best.min(dist[y * n + (x + 1)].saturating_add(1));
            }
            dist[idx] = best;
        }
    }
}
