# Minimal network configuration

include = ["../minimal-net.toml"]

# Override the default settings here

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 256

# Package settings
[packages]
nexus-assets = {}
nexus = {}
#orbital = {}
nexus-term = {}
#orbutils-background = {}
#orbutils-launcher = {}
#orbutils-orblogin = {}
nexus-login = {}
nexus-background = {}
nexus-launcher = {}

[[files]]
path = "/usr/lib/init.d/20_nexus"
data = """
export VT 3
nexus-background &
nexus nexus-login nexus-launcher
unset VT
"""

# Override console config to not switch to VT 2
[[files]]
path = "/usr/lib/init.d/30_console"
data = """
getty 2
getty /scheme/debug/no-preserve -J
"""
