[toolchain]
channel = "1.75.0"
components = ["rustfmt", "clippy", "rust-src"]
targets = ["riscv64imac-unknown-none-elf"]
profile = "minimal"

[metadata.tools-nightly]
channel = "nightly-2024-02-01"
components = ["rustfmt", "clippy", "miri"]
