// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0

//! CONTEXT: bakes the `[quota."<subject>"]` declarations of `policies/*.toml`
//! (RFC-0072 amendment, TASK-0043) into statefsd's `quota_table.rs` —
//! `QUOTA_ENTRIES: &[statefs::quota::QuotaRule]`. The grammar is the shared
//! `userspace/policy/src/schema.rs` (included by path, like policyd's
//! build.rs), the subject hash the shared `learn_record::service_id_from_name`;
//! an invalid or overlapping declaration fails the build, never boots.
//! OWNERS: @runtime @security
//! STATUS: Experimental
//! API_STABILITY: Internal
//! TEST_COVERAGE: policy corpus (`policies/tests/*quota*`); the OS proof
//!   `SELFTEST: quota deny ok` consumes the emitted table

#![allow(clippy::expect_used)]

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[path = "../../../userspace/policy/src/learn_record.rs"]
#[allow(dead_code)]
mod learn_record;
#[path = "../../../userspace/policy/src/schema.rs"]
#[allow(dead_code)]
mod schema;

use learn_record::service_id_from_name;
use schema::Quota;

/// Only the quota section matters here; the other sections are validated by
/// the host `policy` crate and policyd's build.
#[derive(Debug, Default, Deserialize)]
struct RawPolicy {
    #[serde(default)]
    quota: BTreeMap<String, schema::RawQuota>,
}

#[derive(Debug, Deserialize)]
struct RawPolicyRoot {
    version: u32,
    #[serde(default)]
    include: Vec<String>,
}

fn main() {
    println!("cargo::rustc-check-cfg=cfg(nexus_env, values(\"os\",\"host\"))");
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR missing");
    let policy_dir = Path::new(&manifest_dir)
        .join("../../../policies")
        .canonicalize()
        .expect("failed to resolve policies");
    for shared in ["schema.rs", "learn_record.rs"] {
        println!(
            "cargo::rerun-if-changed={}",
            Path::new(&manifest_dir).join("../../../userspace/policy/src").join(shared).display()
        );
    }
    let quotas = load_quotas(&policy_dir);
    emit_quota_table(&quotas);
}

fn load_quotas(dir: &Path) -> BTreeMap<String, Quota> {
    let root_path = dir.join("nexus.policy.toml");
    let root_data =
        fs::read_to_string(&root_path).expect("failed to read policies/nexus.policy.toml");
    let root: RawPolicyRoot =
        toml::from_str(&root_data).expect("failed to parse policies/nexus.policy.toml");
    assert!(root.version == 1, "unsupported policy root version");
    println!("cargo::rerun-if-changed={}", root_path.display());
    let mut files = Vec::new();
    for include in root.include {
        assert!(
            !include.contains("..") && !Path::new(&include).is_absolute(),
            "policy include escapes policies root"
        );
        let path = dir.join(include);
        assert!(path.is_file(), "policy include is not a file");
        println!("cargo::rerun-if-changed={}", path.display());
        files.push(path);
    }
    files.sort();
    let mut quotas: BTreeMap<String, Quota> = BTreeMap::new();
    for path in files {
        let data = fs::read_to_string(&path).expect("failed to read policy file");
        let parsed: RawPolicy =
            toml::from_str(&data).unwrap_or_else(|_| panic!("failed to parse {}", path.display()));
        for (subject, raw) in parsed.quota {
            let quota = schema::compile_quota(&raw).unwrap_or_else(|err| {
                panic!("invalid quota for {subject} in {}: {err}", path.display())
            });
            quotas.insert(subject.trim().to_ascii_lowercase(), quota);
        }
    }
    schema::check_quotas_disjoint(quotas.iter().map(|(k, v)| (k.as_str(), v)))
        .unwrap_or_else(|err| panic!("quota declarations: {err}"));
    quotas
}

fn emit_quota_table(quotas: &BTreeMap<String, Quota>) {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR missing"));
    let dest = out_dir.join("quota_table.rs");
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by statefsd/build.rs from policies/*.toml. DO NOT EDIT.\n");
    out.push_str("use statefs::quota::QuotaRule;\n\n");
    out.push_str("pub const QUOTA_ENTRIES: &[QuotaRule] = &[\n");
    for (subject, q) in quotas {
        let sid = service_id_from_name(subject.as_bytes());
        let prefixes: Vec<String> =
            q.prefixes.iter().map(|p| format!("\"{}\"", p.escape_default())).collect();
        out.push_str(&format!(
            "    QuotaRule {{ subject: 0x{sid:016x}u64, prefixes: &[{}], soft_bytes: {}u64, hard_bytes: {}u64 }},\n",
            prefixes.join(", "),
            q.soft_bytes,
            q.hard_bytes
        ));
    }
    out.push_str("];\n");
    fs::write(&dest, out).expect("failed to write quota_table.rs");
}
