[theme]
current = "light"

[icons]
power.shutdown = "actions/system-shut-down"
power.restart = "actions/system-restart"
power.sleep = "actions/system-sleep"
session.logout = "actions/system-log-out"
notifications.button = "system/notifications"
notifications.mails = "system/mails"
notifications.chats = "system/messages"
notifications.calls = "system/calls"
controlcenter.button = "system/control-center"
files.copy = "system/copy"
files.delete = "system/delete"
files.move = "system/move"
files.new = "system/add"
files.sort_direction = "system/sort-direction"
files.sort_type = "system/sort-type"
login.back = "system/back"
menu.bigger = "system/bigger"
menu.smaller = "system/smaller"
menu.search = "system/search"
filemanager.back = "system/back"
filemanager.forward = "system/forward"
filemanager.layout = "system/layout"
filemanager.actions = "system/actions"
filemanager.more = "system/show-more"

[system]
avatar = "system/avatar"
window_hide = "system/window_hide"
window_hide_unfocused = "system/window_hide_unfocused"
window_max = "system/window_max"
window_max_unfocused = "system/window_max_unfocused"
window_close = "system/window_close"
window_close_unfocused = "system/window_close_unfocused"

[cursor]
cursor = "system/left_ptr"
bottom_left_corner = "system/bottom_left_corner"
bottom_right_corner = "system/bottom_right_corner"
bottom_side = "system/bottom_side"
left_side = "system/left_side"
right_side = "system/right_side"

[places]
current = "places/current"
home = "places/start-here"
documents = "places/documents"
downloads = "places/downloads"
pictures = "places/fotos"
music = "places/audio"
videos = "places/videos"
trash = "places/trash-bin"
storage.nx_cloud = "places/nx-cloud"
storage.network = "places/network-storage"
storage.google_drive = "places/google-drive"
storage.computer = "places/internal-storage"
storage.sd_card = "places/sd-card"
#storage.usb = "places/usb-stick"
#storage.external_drive = "places/external-drive"