cursor = "cursor/default"
handpointing = "cursor/handpointing"
handopen = "cursor/handopen"
handgrabbing = "cursor/handgrabbing"
help = "cursor/help"
bottom_left_corner = "cursor/resizesouthwest"
bottom_right_corner = "cursor/resizesoutheast"
bottom_side = "cursor/resizesouth"
left_side = "cursor/resizewest"
right_side = "cursor/resizeeast"
top_left_corner = "cursor/resizenorthwest"
top_right_corner = "cursor/resizenortheast"
top_side = "cursor/resizenorth"
add_cell = "cursor/cell"
open_context_menu = "cursor/contextualmenu"
makealias = "cursor/makealias"
move = "cursor/move"
notallowed = "cursor/notallowed"
proof = "cursor/proof"
screenshotselection = "cursor/screenshotselection"
screenshotwindow = "cursor/screenshotwindow"
textcursor = "cursor/textcursor"
textcursorvertical = "cursor/textcursorvertical"
zoomin = "cursor/zoomin"
zoomout = "cursor/zoomout"

window_max               = "actions/window_max"
window_max_unfocused     = "actions/window_max_unfocused"
window_close             = "actions/window_close"
window_close_unfocused   = "actions/window_close_unfocused"
window_hide              = "actions/window_hide"
window_hide_unfocused    = "actions/window_hide_unfocused"

[theme]
current = "light"

[icons]
avatar = "system/avatar-default"
power.shutdown = "actions/system-shut-down"
power.restart = "actions/system-restart"
power.sleep = "actions/system-sleep"
session.logout = "actions/session-logout"
notifications.button = "actions/notifications"
notifications.mails = "status/mails"
notifications.chats = "status/messages"
notifications.calls = "status/calls"
controlcenter.button = "actions/control-center"
controlcenter.dark = "actions/moon"
controlcenter.light = "actions/sun"
controcenter.mode = "actions/mobile-desktop"
files.copy = "actions/copy"
files.delete = "actions/delete"
files.move = "actions/move"
files.new = "actions/add"
files.sort_direction = "actions/sort-direction"
files.sort_type = "actions/sort-type"
login.back = "actions/back"
menu.bigger = "actions/bigger"
menu.smaller = "actions/smaller"
menu.search = "actions/search"
filemanager.back = "actions/back"
filemanager.forward = "actions/forward"
filemanager.layout = "actions/layout"
filemanager.actions = "actions/more"
filemanager.more = "actions/show-more"
start = "system/start"
overview = "system/overview"
current = "places/current"
home = "places/home"
documents = "places/documents"
downloads = "places/downloads"
pictures = "places/fotos"
music = "places/audio"
videos = "places/videos"
trash = "places/trash-bin"
storage.nx_cloud = "places/nx-cloud"
storage.network = "places/network-storage"
storage.google_drive = "places/google-drive"
storage.computer = "places/internal-storage"
storage.sd_card = "places/sd-card"
settings = "actions/settings"
apps.unknown = "apps/unknown"
#storage.usb = "places/usb-stick"
#storage.external_drive = "places/external-drive"

[backgrounds]
login = "backgrounds/login"
desktop = "backgrounds/desktop"

[defaults.acrylic]
downscale = 4
tint = "#33FFFFFF"      # ARGB-ish hex (we parse as RGBA; this is a light white tint)
noise_alpha = 16

[colors]
# Surfaces
surface_bg              = { rgba = [250,250,250,255], acrylic = { enabled = false } }
surface_muted_bg        = { rgba = [245,245,245,255], acrylic = { enabled = false } }
surface_elev1_bg        = { rgba = [255,255,255,240], acrylic = { enabled = true,  blur_px = 16 } }

# Text/Icon
text_fg                 = "#0A0A0A"
text_highlight_fg       = { rgba = [255,255,255,51] } # 20%
text_muted_fg           = "#5A5A5A"
text_inverse_fg         = "#FFFFFF"
icon_fg                 = "#222222"
icon_muted_fg           = "#7A7A7A"

# Brand & Links (optional)
link_fg                 = "#0066CC"
link_fg_hover           = "#0050A8"

# Window
window_bg               = { rgba = [255,255,255,154], acrylic = { enabled = true } }
window_titlebar_bg      = { rgba = [255,255,255,154], acrylic = { enabled = true } }
window_border           = "#E4E4E4"
window_content_bg       = { rgba = [255,255,255,134], acrylic = { enabled = true } } # 60%

# Menu
menu_bar_bg             = { rgba = [255,255,255,191], acrylic = { enabled = true} } # 75%
menu_surface_sm_bg      = { rgba = [255,255,255,128], acrylic = { enabled = true } } # 50%
menu_surface_lg_bg      = { rgba = [0,0,0,64], acrylic = { enabled = true } } # 25%
menu_icon_bg_hover      = { rgba = [255,255,255,26] } # 10%
menu_bar_icon_active = "#000000"
menu_bar_icon_bg_hover  = { rgba = [255,255,255,26] } # 10%
menu_bar_devider        = { rgba = [255,255,255,89] } # 35%

# Panels/COntrolcenter+Notifications
actionbar_bg            = { rgba = [255,255,255,89], acrylic = { enabled = true, blur_px = 16 } } # 35%
panel_bg                = { rgba = [255,255,255,26], acrylic = { enabled = true, blur_px = 16 } } # 10%
button_hover_veil       = { rgba = [0,0,0,26], acrylic = { enabled = true, blur_px = 16 } } # 10%

# Notifications
notification_pill_bg         = { rgba = [255,255,255,191], acrylic = { enabled = true, blur_px = 16 } } # 75%
notification_pill_lower1_bg = { rgba = [255,255,255,178], acrylic = { enabled = true, blur_px = 16 } } # 70%

# Control Center
control_center_group_bg         = { rgba = [255,255,255,128], acrylic = { enabled = true} } # 50%
control_center_item_bg_active   = { rgba = [255,255,255,191], acrylic = { enabled = true} } # 75%
control_center_item_fg_muted    = { rgba = [0,0,0,51], acrylic = { enabled = true} } # 20%

# Inputs
input_bg                = { rgba = [255,255,255,128] } # 50%
input_fg                = "#111111"
input_placeholder_fg    = "#8A8A8A"

# Buttons
button_bg               = { rgba = [255,255,255,191] } # 75%
button_bg_hover         = { rgba = [255,255,255,128] } # 50%
button_bg_muted        = { rgba = [0,0,0,51] } # 20%
button_fg               = "#111111"

# System states
selection_bg            = "#CCE7FF"
selection_fg            = "#0A0A0A"
focus_ring              = "#0078D7"
disabled_fg             = "#A8A8A8"
disabled_bg             = "#F5F5F5"

# Semantic feedback
success_bg              = "#E7F6EC"
success_fg              = "#1E7F3D"
warning_bg              = "#FFF7E5"
warning_fg              = "#A05A00"
danger_bg               = "#FDE7E9"
danger_fg               = "#A61B2B"

# Structure
border                  = "#E4E4E4"
border_muted            = "#EEEEEE"
divider                 = "#E4E4E4"
shadow_color            = { rgba = [0,0,0,64] }

# Overlays
overlay_scrim_bg        = { rgba = [0,0,0,102] } # ~40% für Modals
tooltip_bg              = "#111111"
tooltip_fg              = "#FFFFFF"

# Scrollbars
scrollbar_track_bg      = "#F0F0F0"
scrollbar_thumb_bg      = "#D0D0D0"
scrollbar_thumb_bg_hover= "#BEBEBE"

# 10% = 26, 20% = 51, 25% = 64, 35% = 89, 50% = 128, 70% = 178, 75% = 191, 80% = 204, 90% = 230, 100% = 255
