[theme]
current = "light"

[icons]
power.shutdown = "actions/system-shut-down"
power.restart = "actions/system-restart"
power.sleep = "actions/system-sleep"
session.logout = "actions/session-logout"
notifications.button = "actions/notifications"
notifications.mails = "status/mails"
notifications.chats = "status/messages"
notifications.calls = "status/calls"
controlcenter.button = "actions/control-center"
files.copy = "actions/copy"
files.delete = "actions/delete"
files.move = "actions/move"
files.new = "actions/add"
files.sort_direction = "actions/sort-direction"
files.sort_type = "actions/sort-type"
login.back = "actions/back"
menu.bigger = "actions/bigger"
menu.smaller = "actions/smaller"
menu.search = "actions/search"
filemanager.back = "actions/back"
filemanager.forward = "actions/forward"
filemanager.layout = "actions/layout"
filemanager.actions = "actions/more"
filemanager.more = "actions/show-more"

[cursor]
cursor = "cursor/default"
handpointing = "cursor/handpointing"
handopen = "cursor/handopen"
handgrabbing = "cursor/handgrabbing"
help = "cursor/help"
bottom_left_corner = "cursor/resizesouthwest"
bottom_right_corner = "cursor/resizesoutheast"
bottom_side = "cursor/resizesouth"
left_side = "cursor/resizewest"
right_side = "cursor/resizeeast"
top_left_corner = "cursor/resizenorthwest"
top_right_corner = "cursor/resizenortheast"
top_side = "cursor/resizenorth"
add_cell = "cursor/cell"
open_context_menu = "cursor/contextualmenu"
makealias = "cursor/makealias"
move = "cursor/move"
notallowed = "cursor/notallowed"
proof = "cursor/proof"
screenshotselection = "cursor/screenshotselection"
screenshotwindow = "cursor/screenshotwindow"
textcursor = "cursor/textcursor"
textcursorvertical = "cursor/textcursorvertical"
zoomin = "cursor/zoomin"
zoomout = "cursor/zoomout"

[system]
start = "system/start"
overview = "system/overview"
avatar = "system/avatar-default"
window_hide = "actions/window_hide"
window_hide_unfocused = "actions/window_hide_unfocused"
window_max = "actions/window_max"
window_max_unfocused = "actions/window_max_unfocused"
window_close = "actions/window_close"
window_close_unfocused = "actions/window_close_unfocused"


[places]
current = "places/current"
home = "places/home"
documents = "places/documents"
downloads = "places/downloads"
pictures = "places/fotos"
music = "places/audio"
videos = "places/videos"
trash = "places/trash-bin"
storage.nx_cloud = "places/nx-cloud"
storage.network = "places/network-storage"
storage.google_drive = "places/google-drive"
storage.computer = "places/internal-storage"
storage.sd_card = "places/sd-card"
#storage.usb = "places/usb-stick"
#storage.external_drive = "places/external-drive"

[backgrounds]
login = "backgrounds/login"
desktop = "backgrounds/desktop"