#!/usr/bin/env bash
# Copyright 2026 Open Nexus OS Contributors
# SPDX-License-Identifier: Apache-2.0
#
# CONTEXT: P0.1 layout-fragility gate — proves the boot survives image-size
# perturbation. Byte-shifts in the kernel/init image once broke DISTANT
# subsystems silently (StackPool cursor corruption → StackExhausted; the
# zero-guards in task/mod.rs and alloc_init_page are scars of it). The boot
# now carries loud tripwires (`KERNEL: layout ok` + headroom, STACK-POOL /
# VMO-POOL value reports); this gate perturbs the image and demands the
# ladder stays green — so a re-emergence is caught in CI, not in a user boot.
#
# Usage: scripts/contract-image-layout.sh   (expects a completed build)
set -euo pipefail
cd "$(dirname "$0")/.."

# The pad is appended to a TRACKED, always-compiled file and reverted via
# git afterwards — a standalone module file would need registration and can
# silently end up dead (never compiled = placebo gate).
PAD_HOST="source/kernel/neuron/src/diag/log.rs"
cleanup() { git checkout -q -- "$PAD_HOST" 2>/dev/null || true; }
trap cleanup EXIT

BASE_IMAGE_END=""

run_boot() {
  local tag="$1"
  RUN_TIMEOUT=40s timeout 70 just start-vnc >"build/logs/perturb-$tag.log" 2>&1 || true
  local log
  log="$(ls -td build/logs/manual--* | head -1)/uart.log"
  if ! grep -q "KERNEL: layout ok" "$log"; then
    echo "contract-image-layout: FAIL ($tag) — no 'KERNEL: layout ok' marker"; exit 1
  fi
  if grep -qE "StackExhausted|STACK-POOL|VMO-POOL exhausted|LAYOUT:" "$log"; then
    echo "contract-image-layout: FAIL ($tag) — layout tripwire fired:"; grep -E "StackExhausted|STACK-POOL|VMO-POOL|LAYOUT:" "$log"; exit 1
  fi
  if ! grep -q "full-window color visible" "$log"; then
    echo "contract-image-layout: FAIL ($tag) — visible chain missing"; exit 1
  fi
  local image_end
  image_end="$(grep -o 'image_end=0x[0-9a-f]*' "$log" | head -1)"
  if [[ "$tag" == "baseline" ]]; then
    BASE_IMAGE_END="$image_end"
  elif [[ "$image_end" == "$BASE_IMAGE_END" ]]; then
    # A pad that does not move the image is a PLACEBO gate (linker GC ate
    # it once already — no_mangle keeps it; this check keeps US honest).
    echo "contract-image-layout: FAIL ($tag) — pad did not land ($image_end unchanged)"; exit 1
  fi
  echo "contract-image-layout: OK ($tag) — $image_end $(grep -o 'headroom=[0-9]*K' "$log")"
}

echo "== baseline =="
run_boot baseline

for pad in 4096 8192 65536; do
  echo "== perturb +${pad}B =="
  git checkout -q -- "$PAD_HOST"
  {
    echo "// @generated by contract-image-layout.sh — perturbation payload, reverted after the run."
    echo "#[used]"
    echo "#[no_mangle]"
    echo "#[link_section = \".rodata\"]"
    echo "pub static LAYOUT_PAD: [u8; $pad] = [0xA5; $pad];"
  } >> "$PAD_HOST"
  env EMBED_INIT_ELF="$PWD/target/riscv64imac-unknown-none-elf/release/init-lite" \
    RUSTFLAGS='--check-cfg=cfg(nexus_env,values("host","os")) --cfg nexus_env="os"' \
    cargo build -p neuron-boot --target riscv64imac-unknown-none-elf --release >/dev/null 2>&1
  run_boot "pad$pad"
done

cleanup
env EMBED_INIT_ELF="$PWD/target/riscv64imac-unknown-none-elf/release/init-lite" \
  RUSTFLAGS='--check-cfg=cfg(nexus_env,values("host","os")) --cfg nexus_env="os"' \
  cargo build -p neuron-boot --target riscv64imac-unknown-none-elf --release >/dev/null 2>&1
echo "contract-image-layout: ALL GREEN (baseline + 3 perturbations)"
