// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0

//! CONTEXT: Build script — generates `APP_REGISTRY` from the real bundle
//! manifests so the Apps menu reflects installed bundles, not a const (RFC-0065).
//! OWNERS: @ui @runtime
//! STATUS: Functional
//! API_STABILITY: Unstable
//! TEST_COVERAGE: No tests (build script; the registry is exercised by bundlemgrd `os_lite` tests)
//!
//! Build script: generates the installed-app registry (`APP_REGISTRY`) from the
//! REAL app bundle manifests (`bundles/<app>/manifest.toml`) instead of a
//! hand-maintained const in source (RFC-0065). The manifests are the single
//! source of truth: an app appears in the Apps menu iff it has a bundle manifest,
//! so a phantom entry (e.g. an app that does not exist) cannot drift in. The
//! generated table is `include!`d by `os_lite.rs`.
//!
//! This is build-time enumeration of the shipped bundle set (appropriate for the
//! no_std service, which cannot read a filesystem at runtime). The future install
//! pipeline feeds the embedded `.nxb` set through this same table.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo::rustc-check-cfg=cfg(nexus_env, values(\"os\",\"host\"))");

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    // bundlemgrd lives at source/services/bundlemgrd → repo root is three up.
    let bundles_dir = manifest_dir.join("../../../bundles");
    println!("cargo:rerun-if-changed={}", bundles_dir.display());

    let mut apps: Vec<(String, String)> = Vec::new();
    if let Ok(entries) = std::fs::read_dir(&bundles_dir) {
        for entry in entries.flatten() {
            let manifest = entry.path().join("manifest.toml");
            if !manifest.is_file() {
                continue;
            }
            println!("cargo:rerun-if-changed={}", manifest.display());
            if let Some((id, label)) = read_app(&manifest) {
                apps.push((id, label));
            }
        }
    }
    // Deterministic order (directory iteration order is unspecified).
    apps.sort();

    let mut out = String::new();
    out.push_str("// @generated by build.rs from bundles/<app>/manifest.toml — do not edit.\n");
    let _ = writeln!(
        out,
        "pub(crate) const APP_REGISTRY: [(&str, &str); {}] = [",
        apps.len()
    );
    for (id, label) in &apps {
        let _ = writeln!(out, "    ({id:?}, {label:?}),");
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("app_registry.rs");
    std::fs::write(&dest, out).expect("write app_registry.rs");
}

/// Parses the bundle `name` from a manifest's `name = "..."` line and derives a
/// display label (capitalized name). Returns `None` if no name is found.
fn read_app(manifest: &Path) -> Option<(String, String)> {
    let text = std::fs::read_to_string(manifest).ok()?;
    let name = text.lines().find_map(|line| {
        let line = line.trim();
        let rest = line.strip_prefix("name")?.trim_start();
        let rest = rest.strip_prefix('=')?.trim();
        // strip surrounding quotes
        let val = rest.trim_matches('"');
        if val.is_empty() {
            None
        } else {
            Some(val.to_string())
        }
    })?;
    let label = capitalize(&name);
    Some((name, label))
}

/// "chat" -> "Chat". ASCII first-letter capitalization (app ids are lowercase).
fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}
