[package]
name = "nexus-login"
version = "0.1.0"
edition = "2021"

[dependencies]
#chrono = "0.4.6"
#mime_guess = "1.8.6"
#mime = "0.2.6"
orbclient = "0.3.47"
orbfont = "0.1.8"
orbimage = "0.1.17"
orbtk = "0.2.29"
redox_users = "0.4"
redox-log = "0.1"
log = "0.4.14"
dirs = "5.0.0"
libc = "0.2.50"
libnexus = { path = "../../../libs/libnexus/source" }

[target.'cfg(target_os = "redox")'.dependencies]
redox_event = "0.4.1"
libredox = { version = "0.1.3", default-features = false, features = ["std", "call"] }
