[package]
name = "settingsd"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
settings = { path = "../../../userspace/settings", default-features = false, features = ["backend-os"] }

