// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0

//! Generate the typed color-token snapshots from the `.nxtheme.toml` SSOT
//! (RFC-0070 D3). This kills the previously hand-authored `BaseTokens` values,
//! which had drifted from the theme files. Emits one `<qualifier>_color` fn per
//! theme, resolving each semantic `ColorToken` role through the theme's
//! qualifier chain. `LengthToken` (radii/spacing) stays a hand-authored scale
//! until the invariant `[scale]` sections land (token-reconciliation.md step 2).

use std::path::Path;
use std::{env, fs};

use nexus_theme::{Material, Qualifier, ThemeRuntime};

/// Repo `resources/themes`, relative to this crate (`userspace/ui/theme-tokens`).
const THEMES_DIR: &str = "../../../resources/themes";

/// `MaterialToken` level → `[material.*]` name. Frosted backdrop saturation is a
/// fixed 140% (the material files carry no saturation key).
const MATERIALS: &[(&str, &str)] = &[
    ("Panel", "glassPanel"),
    ("Card", "glassCard"),
    ("Subtle", "glassSubtle"),
    ("Window", "glassWindow"),
    ("Overlay", "glassOverlay"),
];
const GLASS_SATURATION: u32 = 140;

/// Semantic `ColorToken` role → `.nxtheme.toml` token name. The single place the
/// runtime role vocabulary binds to authored token names.
const ROLES: &[(&str, &str)] = &[
    ("Surface", "surface"),
    ("SurfaceVariant", "surfaceAlt"),
    ("OnSurface", "fg"),
    ("OnSurfaceVariant", "mutedFg"),
    ("Accent", "accent"),
    ("OnAccent", "accentFg"),
    ("Border", "border"),
    ("Shadow", "shadow"),
    ("Background", "bg"),
    ("Primary", "primary"),
    ("OnPrimary", "primaryFg"),
    ("Danger", "danger"),
    ("OnDanger", "dangerFg"),
    ("Warning", "warning"),
    ("Success", "success"),
    ("Info", "info"),
    ("OnWarning", "warningFg"),
    ("OnSuccess", "successFg"),
    ("OnInfo", "infoFg"),
    ("FocusRing", "focusRing"),
    ("IslandBg", "islandBg"),
    ("Scrim", "scrim"),
    ("Destructive", "destructive"),
    ("OnDestructive", "destructiveFg"),
];

fn main() {
    println!("cargo:rerun-if-changed={THEMES_DIR}");

    let mut runtime = ThemeRuntime::load(Path::new(THEMES_DIR))
        .unwrap_or_else(|e| panic!("nexus-theme-tokens: load {THEMES_DIR}: {e:?}"));

    let mut generated = String::from(
        "// @generated by build.rs from resources/themes/*.nxtheme.toml — do not edit.\n\n",
    );

    for (fn_prefix, qualifier) in [
        ("base", Qualifier::Base),
        ("dark", Qualifier::Dark),
        ("light", Qualifier::Light),
        ("highcontrast", Qualifier::HighContrast),
    ] {
        runtime.set_qualifier(qualifier);
        generated.push_str(&format!(
            "pub(crate) fn {fn_prefix}_color(token: ColorToken) -> Rgba8 {{\n    match token {{\n"
        ));
        for (role, token_name) in ROLES {
            let c = runtime.resolve(token_name).unwrap_or_else(|e| {
                panic!("nexus-theme-tokens: role {role} → token '{token_name}': {e:?}")
            });
            generated.push_str(&format!(
                "        ColorToken::{role} => Rgba8::new({}, {}, {}, {}),\n",
                c.r, c.g, c.b, c.a
            ));
        }
        generated.push_str("    }\n}\n\n");
    }

    // Glass materials → GlassSurface per qualifier (pre-composite color × alpha).
    for (fn_prefix, qualifier) in [
        ("base", Qualifier::Base),
        ("dark", Qualifier::Dark),
        ("light", Qualifier::Light),
        ("highcontrast", Qualifier::HighContrast),
    ] {
        runtime.set_qualifier(qualifier);
        generated.push_str(&format!(
            "pub(crate) fn {fn_prefix}_glass(token: MaterialToken) -> GlassSurface {{\n    match token {{\n"
        ));
        for (variant, mat_name) in MATERIALS {
            let g = match runtime.resolve_material(mat_name) {
                Some(Material::Glass(g)) => g.clone(),
                _ => panic!("nexus-theme-tokens: material '{mat_name}' missing or not glass"),
            };
            let alpha = |a: f32| (a.clamp(0.0, 1.0) * 255.0).round() as u8;
            let tint_bottom = match g.tint_bottom_color {
                Some(c) => format!(
                    "Some(Rgba8::new({}, {}, {}, {}))",
                    c.r,
                    c.g,
                    c.b,
                    alpha(g.tint_bottom_alpha.unwrap_or(1.0))
                ),
                None => "None".to_string(),
            };
            let border = match g.border_color {
                Some(c) => format!(
                    "Some(Rgba8::new({}, {}, {}, {}))",
                    c.r,
                    c.g,
                    c.b,
                    alpha(g.border_alpha.unwrap_or(1.0))
                ),
                None => "None".to_string(),
            };
            generated.push_str(&format!(
                "        MaterialToken::{variant} => GlassSurface {{ tint: Rgba8::new({}, {}, {}, {}), tint_bottom: {}, edge: Rgba8::new({}, {}, {}, {}), border: {}, blur_radius: {}, saturation: {}, downsample: {} }},\n",
                g.tint_color.r, g.tint_color.g, g.tint_color.b, alpha(g.tint_alpha),
                tint_bottom,
                g.edge_highlight_color.r, g.edge_highlight_color.g, g.edge_highlight_color.b, alpha(g.edge_highlight_alpha),
                border, g.blur_radius_dp, GLASS_SATURATION, g.downsample_factor,
            ));
        }
        generated.push_str("    }\n}\n\n");
    }

    // Length scale (theme-invariant → resolve at Base). BorderThin is the fixed
    // 1px hairline (no authored token).
    runtime.set_qualifier(Qualifier::Base);
    let radius = |name: &str| {
        runtime
            .resolve_radius(name)
            .unwrap_or_else(|| panic!("nexus-theme-tokens: [radius] '{name}' missing"))
    };
    let spacing = |name: &str| {
        runtime
            .resolve_spacing(name)
            .unwrap_or_else(|| panic!("nexus-theme-tokens: [spacing] '{name}' missing"))
    };
    generated.push_str(&format!(
        "pub(crate) fn scale_length(token: LengthToken) -> FxPx {{\n    match token {{\n\
         \x20       LengthToken::RadiusSmall => FxPx::new({}),\n\
         \x20       LengthToken::RadiusMedium => FxPx::new({}),\n\
         \x20       LengthToken::RadiusLarge => FxPx::new({}),\n\
         \x20       LengthToken::SpacingSmall => FxPx::new({}),\n\
         \x20       LengthToken::SpacingMedium => FxPx::new({}),\n\
         \x20       LengthToken::SpacingLarge => FxPx::new({}),\n\
         \x20       LengthToken::BorderThin => FxPx::new(1),\n    }}\n}}\n",
        radius("small") as i32,
        radius("medium") as i32,
        radius("large") as i32,
        spacing("small") as i32,
        spacing("medium") as i32,
        spacing("large") as i32,
    ));

    // Typography scale (theme-invariant → resolve at Base).
    let type_scale: &[(&str, &str)] = &[
        ("Xs", "xs"),
        ("Sm", "sm"),
        ("Base", "base"),
        ("Md", "md"),
        ("Lg", "lg"),
        ("Xl", "xl"),
        ("Xxl", "xxl"),
        ("Xxxl", "xxxl"),
        ("Display", "display"),
    ];
    generated.push_str("pub(crate) fn type_size(token: TypographyToken) -> FxPx {\n    match token {\n");
    for (variant, name) in type_scale {
        let px = runtime
            .resolve_scale("typography", name)
            .unwrap_or_else(|| panic!("nexus-theme-tokens: [typography] '{name}' missing"));
        generated.push_str(&format!(
            "        TypographyToken::{variant} => FxPx::new({}),\n",
            px as i32
        ));
    }
    generated.push_str("    }\n}\n\n");

    // Motion durations in ms (theme-invariant → resolve at Base; a
    // reduced-motion theme would override [motion] to 0).
    let motion_scale: &[(&str, &str)] = &[
        ("Instant", "instant"),
        ("Swift", "swift"),
        ("Quick", "quick"),
        ("Base", "base"),
        ("Slow", "slow"),
    ];
    generated.push_str(
        "pub(crate) fn motion_duration_ms(token: MotionDurationToken) -> u32 {\n    match token {\n",
    );
    for (variant, name) in motion_scale {
        let ms = runtime
            .resolve_scale("motion", name)
            .unwrap_or_else(|| panic!("nexus-theme-tokens: [motion] '{name}' missing"));
        generated
            .push_str(&format!("        MotionDurationToken::{variant} => {ms},\n"));
    }
    generated.push_str("    }\n}\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("generated_tokens.rs"), generated)
        .expect("write generated_tokens.rs");
}
