// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0

// Build scripts fail by panicking (unwrap/expect) — the correct failure mode
// for build-time codegen; the restriction lints target runtime code only.
#![allow(clippy::expect_used, clippy::unwrap_used)]

//! Build script: bakes the platform's file-type icon artwork
//! (`resources/mimetypes/*.svg`) into straight-alpha RGBA sprites at file-row
//! sizes, and generates the extension→stem / mime→stem resolution tables from
//! the mime SSOT (`resources/mimetypes/mimetypes.toml`, RFC-0073). Same house
//! style as `nexus-app-icons`: nexus-svg renders at 4× supersampling, a box
//! average downscales, alpha is unassociated. The `.toml` is the SSOT — the
//! resolution chain (exact → class-generic → octet-stream) is folded in HERE so
//! the runtime is a pure table lookup and every generated stem is a real SVG.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;

/// File-row / list sizes (stash renders ~24 px badges; larger kept for reuse).
const SIZES: &[u32] = &[48, 32, 24];
/// Supersampling factor for crisp AA at small sizes.
const SS: u32 = 4;
/// Ultimate fallback stem — `application-octet-stream.svg` must always exist.
const UNKNOWN: &str = "application-octet-stream";

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let mime_dir = manifest_dir.join("../../../resources/mimetypes");
    println!("cargo:rerun-if-changed={}", mime_dir.display());

    // 1. Collect the available icon stems (filename without `.svg`).
    let mut svgs: BTreeMap<String, PathBuf> = BTreeMap::new();
    let read = std::fs::read_dir(&mime_dir)
        .unwrap_or_else(|e| panic!("mime-icons: read_dir {}: {e}", mime_dir.display()));
    for entry in read.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) == Some("svg") {
            if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                println!("cargo:rerun-if-changed={}", path.display());
                svgs.insert(stem.to_string(), path.clone());
            }
        }
    }
    assert!(
        svgs.contains_key(UNKNOWN),
        "mime-icons: {UNKNOWN}.svg (the ultimate fallback) is missing"
    );

    // 2. Parse the SSOT: [types] ext → (mime, icon?) and [fallbacks] class → stem.
    let toml_path = mime_dir.join("mimetypes.toml");
    println!("cargo:rerun-if-changed={}", toml_path.display());
    let toml = std::fs::read_to_string(&toml_path)
        .unwrap_or_else(|e| panic!("mime-icons: read {}: {e}", toml_path.display()));
    let (types, fallbacks) = parse_mimetypes(&toml);

    // 3. Resolve every ext/mime to an EXISTING stem (chain folded at build time).
    let resolve = |mime: &str, icon: Option<&str>| -> String {
        if let Some(icon) = icon {
            if svgs.contains_key(icon) {
                return icon.to_string();
            }
        }
        let derived = mime.replace(['/', '+'], "-");
        if svgs.contains_key(&derived) {
            return derived;
        }
        let class = mime.split('/').next().unwrap_or("");
        if let Some(fb) = fallbacks.get(class) {
            if svgs.contains_key(fb) {
                return fb.clone();
            }
        }
        fallbacks
            .get("unknown")
            .filter(|s| svgs.contains_key(*s))
            .cloned()
            .unwrap_or_else(|| UNKNOWN.to_string())
    };

    // SSOT consistency guard (RFC-0073): an explicit `icon = "…"` override that
    // names a missing SVG is an authoring bug — fail the build loudly rather
    // than silently falling through to a generic.
    for (ext, (_mime, icon)) in &types {
        if let Some(icon) = icon {
            assert!(
                svgs.contains_key(icon),
                "mime-icons: extension '{ext}' overrides icon = '{icon}' but \
                 resources/mimetypes/{icon}.svg does not exist"
            );
        }
    }

    let mut ext_to_stem: Vec<(String, String)> = Vec::new();
    let mut mime_to_stem: BTreeMap<String, String> = BTreeMap::new();
    for (ext, (mime, icon)) in &types {
        let stem = resolve(mime, icon.as_deref());
        ext_to_stem.push((ext.clone(), stem.clone()));
        mime_to_stem.entry(mime.clone()).or_insert(stem);
    }
    ext_to_stem.sort();

    // 4. Bake every present SVG at every size + emit the generated module.
    let mut out =
        String::from("// @generated by build.rs from resources/mimetypes/ — do not edit.\n\n");
    let mut sprite_table = String::new();
    for (stem, path) in &svgs {
        let svg = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("mime-icons: read {}: {e}", path.display()));
        for &size in SIZES {
            let hi = nexus_svg::render_svg_at(&svg, size * SS, size * SS)
                .unwrap_or_else(|e| panic!("mime-icons: rasterize {stem}@{size}: {e:?}"));
            let premul = box_average_downscale(&hi.buffer, hi.width, hi.height, SS);
            let rgba = straight_rgba_from_premul_bgra(&premul);
            let ident = format!("SPRITE_{}_{}", ident_of(stem), size);
            let _ = writeln!(out, "static {ident}: [u8; {}] = [", rgba.len());
            for chunk in rgba.chunks(16) {
                out.push_str("    ");
                for b in chunk {
                    let _ = write!(out, "{b}, ");
                }
                out.push('\n');
            }
            out.push_str("];\n");
            let _ = writeln!(sprite_table, "        ({stem:?}, {size}) => Some(&{ident}),");
        }
    }
    let _ = writeln!(
        out,
        "pub(crate) fn sprite_bytes(stem: &str, size: u32) -> Option<&'static [u8]> {{\n    \
         match (stem, size) {{\n{sprite_table}        _ => None,\n    }}\n}}"
    );

    // Interned stem: maps any stem string back to its 'static form (so a
    // source token that IS already a stem resolves without an ext/mime lookup).
    let mut stem_table = String::new();
    for stem in svgs.keys() {
        let _ = writeln!(stem_table, "        {stem:?} => Some({stem:?}),");
    }
    let _ = writeln!(
        out,
        "pub(crate) fn stem_static(stem: &str) -> Option<&'static str> {{\n    \
         match stem {{\n{stem_table}        _ => None,\n    }}\n}}"
    );

    // ext → stem (lowercase keys; caller lowercases input).
    let mut ext_table = String::new();
    for (ext, stem) in &ext_to_stem {
        let _ = writeln!(ext_table, "        {ext:?} => {stem:?},");
    }
    let _ = writeln!(
        out,
        "pub(crate) fn stem_for_ext(ext: &str) -> &'static str {{\n    \
         match ext {{\n{ext_table}        _ => {UNKNOWN:?},\n    }}\n}}"
    );

    // mime → stem.
    let mut mime_table = String::new();
    for (mime, stem) in &mime_to_stem {
        let _ = writeln!(mime_table, "        {mime:?} => {stem:?},");
    }
    let _ = writeln!(
        out,
        "pub(crate) fn stem_for_mime(mime: &str) -> &'static str {{\n    \
         match mime {{\n{mime_table}        _ => {UNKNOWN:?},\n    }}\n}}"
    );

    // Baked size list + a couple of provenance counts for the self-test.
    let sizes_lit = SIZES.iter().map(|s| s.to_string()).collect::<Vec<_>>().join(", ");
    let _ = writeln!(out, "pub(crate) const BAKED_SIZES: &[u32] = &[{sizes_lit}];");
    let _ =
        writeln!(out, "#[allow(dead_code)]\npub(crate) const STEM_COUNT: usize = {};", svgs.len());
    let _ = writeln!(
        out,
        "#[allow(dead_code)]\npub(crate) const EXT_COUNT: usize = {};",
        ext_to_stem.len()
    );

    let out_path = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("mime_icons.rs");
    std::fs::write(&out_path, out).unwrap();
}

/// A Rust-identifier-safe upper-snake form of a stem (`text-x-c` → `TEXT_X_C`).
fn ident_of(stem: &str) -> String {
    stem.to_uppercase().chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '_' }).collect()
}

/// Minimal parser for `mimetypes.toml`: only the `[types]` inline-table rows
/// and the flat `[fallbacks]` rows we control. Returns
/// (`ext → (mime, icon?)`, `class → stem`).
#[allow(clippy::type_complexity)]
fn parse_mimetypes(
    toml: &str,
) -> (BTreeMap<String, (String, Option<String>)>, BTreeMap<String, String>) {
    let mut types: BTreeMap<String, (String, Option<String>)> = BTreeMap::new();
    let mut fallbacks: BTreeMap<String, String> = BTreeMap::new();
    let mut section = "";
    for raw in toml.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(name) = line.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
            section = match name.trim() {
                "types" => "types",
                "fallbacks" => "fallbacks",
                _ => "",
            };
            continue;
        }
        let Some(eq) = line.find('=') else { continue };
        let key = line[..eq].trim().trim_matches('"').to_string();
        let value = line[eq + 1..].trim();
        match section {
            "types" => {
                let Some(mime) = extract_field(value, "mime") else { continue };
                let icon = extract_field(value, "icon");
                types.insert(key, (mime, icon));
            }
            "fallbacks" => {
                fallbacks.insert(key, value.trim().trim_matches('"').to_string());
            }
            _ => {}
        }
    }
    (types, fallbacks)
}

/// Pulls `<field> = "value"` out of an inline table body.
fn extract_field(body: &str, field: &str) -> Option<String> {
    let at = body.find(field)?;
    let after = &body[at + field.len()..];
    let eq = after.find('=')?;
    let rest = after[eq + 1..].trim_start();
    let rest = rest.strip_prefix('"')?;
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

/// Box-average `factor`× downscale (premultiplied BGRA) — the app-icons bake's
/// downscaler, verbatim semantics.
fn box_average_downscale(src: &[u8], sw: u32, sh: u32, factor: u32) -> Vec<u8> {
    let dw = sw / factor;
    let dh = sh / factor;
    let n = factor * factor;
    let mut out = vec![0u8; (dw * dh * 4) as usize];
    for y in 0..dh {
        for x in 0..dw {
            let mut acc = [0u32; 4];
            for sy in 0..factor {
                for sx in 0..factor {
                    let i = (((y * factor + sy) * sw + (x * factor + sx)) * 4) as usize;
                    for c in 0..4 {
                        acc[c] += src[i + c] as u32;
                    }
                }
            }
            let o = ((y * dw + x) * 4) as usize;
            for c in 0..4 {
                out[o + c] = (acc[c] / n) as u8;
            }
        }
    }
    out
}

/// Premultiplied BGRA → straight-alpha RGBA (the scene painter blends straight
/// `Rgba8` per pixel).
fn straight_rgba_from_premul_bgra(src: &[u8]) -> Vec<u8> {
    let mut out = vec![0u8; src.len()];
    for (i, px) in src.chunks_exact(4).enumerate() {
        let (b, g, r, a) = (px[0] as u32, px[1] as u32, px[2] as u32, px[3] as u32);
        let un = |c: u32| -> u8 {
            if a == 0 {
                0
            } else if a >= 255 {
                c.min(255) as u8
            } else {
                ((c * 255 + a / 2) / a).min(255) as u8
            }
        };
        let o = i * 4;
        out[o] = un(r);
        out[o + 1] = un(g);
        out[o + 2] = un(b);
        out[o + 3] = a as u8;
    }
    out
}
