[package]
name = "nexus-idl-cli"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
clap = { version = "4", features = ["derive"], optional = true }

[features]
default = []
cli = ["clap"]
