name: CLA Check

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: CLA Assistant
        uses: cla-assistant/github-action@v2.3.1
        with:
          path-to-signatures: 'signed_clas.json'
          path-to-document: '.github/cla-template.md'
          branch: 'neuron-foundation'
          allowlist: 'dependabot[bot],renovate[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_TOKEN }}
