// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0
//
//! CONTEXT: Build-time generator for a deterministic system-test `.nxs` archive.
//! OWNERS: @runtime
//! STATUS: Experimental
//! API_STABILITY: Unstable
//! TEST_COVERAGE: No tests
//!
//! This keeps the on-device selftest asset in sync with schema and payload changes.

// Build scripts may use expect/unwrap since failures are hard errors.
#![allow(clippy::expect_used)]

use std::{env, fmt::Write as _, fs, path::PathBuf};

use capnp::message::Builder;
use capnp::serialize;
use ed25519_dalek::{Signer, SigningKey};
use sha2::{Digest, Sha256};
use tar::{Builder as TarBuilder, EntryType, Header};

use exec_payloads::HELLO_MANIFEST_NXB;
use updates::system_set_capnp::system_set_index;

// SECURITY: bring-up test key for deterministic selftests (NOT production custody).
const TEST_SIGNING_KEY_SEED: [u8; 32] = [7u8; 32];

// Keep the selftest `.nxs` small so OTA staging stays fast under QEMU emulation.
// This payload is NOT executed; it is only hashed and packaged.
const TEST_PAYLOAD: &[u8] = b"open-nexus-os selftest payload v1\n";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../../../userspace/exec-payloads/src/hello_elf.rs");
    println!("cargo:rerun-if-changed=../../../userspace/exec-payloads/build.rs");
    println!("cargo:rerun-if-changed=../../../tools/nexus-idl/schemas/system-set.capnp");
    println!("cargo:rerun-if-changed=../../../tools/nexus-idl/schemas/manifest.capnp");
    println!("cargo:rerun-if-changed=proof-manifest.toml");
    // P4-08: SELFTEST_PROFILE is read by os_lite::profile via option_env!;
    // signal cargo to rebuild whenever it changes so `just ci-os-runtime-quick`
    // (etc) picks up the right binary on second invocation.
    println!("cargo:rerun-if-env-changed=SELFTEST_PROFILE");

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let nxs_bytes = build_system_test_nxs();
    fs::write(out_dir.join("system-test.nxs"), nxs_bytes)?;

    // P4-03: generate `markers_generated.rs` from `proof-manifest.toml`.
    // `markers.rs` includes this via `include!(concat!(env!("OUT_DIR"), …))`.
    let manifest_src = fs::read_to_string("proof-manifest.toml")
        .expect("read proof-manifest.toml");
    let manifest = nexus_proof_manifest::parse(&manifest_src)
        .expect("parse proof-manifest.toml");
    let generated = render_markers(&manifest);
    fs::write(out_dir.join("markers_generated.rs"), generated)?;
    Ok(())
}

/// Render `markers_generated.rs` content from a parsed manifest.
///
/// One `pub(crate) const M_<KEY>: &str = "<literal>"` per declared marker, in
/// manifest declaration order. Phase / profile metadata is intentionally NOT
/// emitted yet — P4-04 wires emit-site migration, P4-05/P4-08 wire profile
/// dispatch and harness consumption respectively.
fn render_markers(manifest: &nexus_proof_manifest::Manifest) -> String {
    let mut out = String::new();
    out.push_str("// @generated by build.rs from `proof-manifest.toml` — DO NOT EDIT.\n");
    out.push_str("// Schema version: ");
    out.push_str(&manifest.meta.schema_version);
    out.push_str("\n// Default profile: ");
    out.push_str(&manifest.meta.default_profile);
    out.push_str("\n// Marker count: ");
    let _ = write!(out, "{}", manifest.markers().count());
    out.push_str("\n\n");
    for marker in manifest.markers() {
        let key = marker.const_key();
        let _ = writeln!(
            out,
            "/// {} (phase: {})",
            escape_doc(&marker.literal),
            marker.phase
        );
        let _ = writeln!(
            out,
            "pub(crate) const M_{}: &str = {};",
            key,
            rust_string_literal(&marker.literal)
        );
    }
    out
}

/// Escape a marker literal for use inside a `///` doc comment line.
fn escape_doc(s: &str) -> String {
    s.replace(['\n', '\r'], " ")
}

/// Emit a Rust string literal for `s`, escaping `\\` and `"`.
fn rust_string_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{{{:x}}}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn build_system_test_nxs() -> Vec<u8> {
    let signing_key = SigningKey::from_bytes(&TEST_SIGNING_KEY_SEED);
    let publisher = signing_key.verifying_key().to_bytes();

    let index_bytes = build_index(&publisher, HELLO_MANIFEST_NXB, TEST_PAYLOAD);
    let signature = signing_key.sign(&index_bytes);
    let signature_bytes = signature.to_bytes();

    let mut tar = TarBuilder::new(Vec::new());
    append_file(&mut tar, "system.nxsindex", &index_bytes);
    append_file(&mut tar, "system.sig.ed25519", &signature_bytes);

    let dir_name = "demo.hello.nxb/";
    append_dir(&mut tar, dir_name);
    append_file(&mut tar, "demo.hello.nxb/manifest.nxb", HELLO_MANIFEST_NXB);
    append_file(&mut tar, "demo.hello.nxb/payload.elf", TEST_PAYLOAD);

    tar.into_inner().expect("system-test.nxs bytes")
}

fn build_index(publisher: &[u8; 32], manifest: &[u8], payload: &[u8]) -> Vec<u8> {
    let mut builder = Builder::new_default();
    let mut root = builder.init_root::<system_set_index::Builder>();
    root.set_schema_version(1);
    root.set_system_version("1.0.0");
    root.set_publisher(publisher);
    root.set_timestamp_unix_ms(0);

    let mut bundles = root.reborrow().init_bundles(1);
    let mut entry = bundles.reborrow().get(0);
    entry.set_name("demo.hello");
    entry.set_version("0.0.1");
    entry.set_manifest_sha256(&sha256(manifest));
    entry.set_payload_sha256(&sha256(payload));
    entry.set_payload_size(payload.len() as u64);

    let mut out = Vec::new();
    serialize::write_message(&mut out, &builder).expect("system.nxsindex encode");
    out
}

fn sha256(bytes: &[u8]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let digest = hasher.finalize();
    let mut out = [0u8; 32];
    out.copy_from_slice(&digest);
    out
}

fn append_file(builder: &mut TarBuilder<Vec<u8>>, path: &str, bytes: &[u8]) {
    let mut header = Header::new_gnu();
    header.set_entry_type(EntryType::Regular);
    header.set_size(bytes.len() as u64);
    header.set_mode(0o644);
    header.set_uid(0);
    header.set_gid(0);
    header.set_mtime(0);
    header.set_cksum();
    builder.append_data(&mut header, path, bytes).expect("append file");
}

fn append_dir(builder: &mut TarBuilder<Vec<u8>>, path: &str) {
    let mut header = Header::new_gnu();
    header.set_entry_type(EntryType::Directory);
    header.set_size(0);
    header.set_mode(0o755);
    header.set_uid(0);
    header.set_gid(0);
    header.set_mtime(0);
    header.set_cksum();
    builder.append_data(&mut header, path, &[] as &[u8]).expect("append dir");
}
