// Copyright 2026 Open Nexus OS Contributors
// SPDX-License-Identifier: Apache-2.0
//
//! CONTEXT: Build-time generator for the proof-manifest marker constants.
//! (TASK-0179 retired the embedded system-test `.nxs` blobs: staging is
//! path-based now — `nx image fixtures` ships the containers on the data
//! partition instead of baking them into the selftest image.)
//! OWNERS: @runtime
//! STATUS: Experimental
//! API_STABILITY: Unstable
//! TEST_COVERAGE: No tests
//!
//! This keeps the on-device selftest asset in sync with schema and payload changes.
//! ADR: docs/adr/0027-selftest-client-two-axis-architecture.md

// Build scripts may use expect/unwrap since failures are hard errors.
#![allow(clippy::expect_used)]

use std::{env, fmt::Write as _, fs, path::PathBuf};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../../../tools/nexus-idl/schemas/manifest.capnp");
    // P5-00: schema-v2 split layout. Watch the root manifest plus every
    // `[include]`-resolved file (parser exposes `Manifest::source_files`).
    // Also watch the directories themselves so that *adding* a new
    // `markers/<phase>.toml` triggers a rebuild even on the first invocation.
    println!("cargo:rerun-if-changed=proof-manifest");
    println!("cargo:rerun-if-changed=proof-manifest/markers");
    println!("cargo:rerun-if-changed=proof-manifest/profiles");
    // Legacy fallback: `os_lite::profile` still accepts a compile-time
    // `SELFTEST_PROFILE` when no runtime `fw_cfg` override is present.
    println!("cargo:rerun-if-env-changed=SELFTEST_PROFILE");

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);

    // P4-03 (extended in P5-00): generate `markers_generated.rs` from the
    // proof-manifest. `markers.rs` includes this via
    // `include!(concat!(env!("OUT_DIR"), …))`.
    let manifest_root = PathBuf::from("proof-manifest/manifest.toml");
    let manifest = nexus_proof_manifest::parse_path(&manifest_root)
        .expect("parse proof-manifest/manifest.toml");
    // Emit one rerun-if-changed per included file so build cache is
    // invalidated on any phase / profile / marker file edit.
    for src in &manifest.source_files {
        println!("cargo:rerun-if-changed={}", src.display());
    }
    let generated = render_markers(&manifest);
    fs::write(out_dir.join("markers_generated.rs"), generated)?;
    Ok(())
}

/// Render `markers_generated.rs` content from a parsed manifest.
///
/// One `pub(crate) const M_<KEY>: &str = "<literal>"` per declared marker, in
/// manifest declaration order. Phase / profile metadata is intentionally NOT
/// emitted yet — P4-04 wires emit-site migration, P4-05/P4-08 wire profile
/// dispatch and harness consumption respectively.
fn render_markers(manifest: &nexus_proof_manifest::Manifest) -> String {
    let mut out = String::new();
    out.push_str("// @generated by build.rs from `proof-manifest/manifest.toml` (schema v2) — DO NOT EDIT.\n");
    out.push_str("// Schema version: ");
    out.push_str(&manifest.meta.schema_version);
    out.push_str("\n// Default profile: ");
    out.push_str(&manifest.meta.default_profile);
    out.push_str("\n// Marker count: ");
    let _ = write!(out, "{}", manifest.markers().count());
    out.push_str("\n\n");
    for marker in manifest.markers() {
        let key = marker.const_key();
        let _ = writeln!(out, "/// {} (phase: {})", escape_doc(&marker.literal), marker.phase);
        let _ = writeln!(
            out,
            "pub(crate) const M_{}: &str = {};",
            key,
            rust_string_literal(&marker.literal)
        );
    }
    out
}

/// Escape a marker literal for use inside a `///` doc comment line.
fn escape_doc(s: &str) -> String {
    s.replace(['\n', '\r'], " ")
}

/// Emit a Rust string literal for `s`, escaping `\\` and `"`.
fn rust_string_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{{{:x}}}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
